### ISSUE TITLE
HTTP server too many open files

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#1006]
The node in explorer server got the following error logs:

[skycoin.gnet:ERROR] accept tcp [::]:6000: accept4: too many open files

http: Accept error: accept tcp 127.0.0.1:6420: accept4: too many open files; retrying in 1s

Maybe caused by http interface leaving connections open, need further test.

**Comment by gz-c** [comment]
This might be fixed now by the connection timeout configuration

**Comment by gz-c** [comment]
I think this is fixed now, hasn't come up again since adding connection timeouts
