### ISSUE TITLE
Test failed in Go 1.10

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#1013]
Update Go to 1.10, and run `go test ./...` from project root:

2018/02/28 17:00:56 decode txid err: encoding/hex: invalid byte: U+0068 'h'
2018/02/28 17:00:56 decode params failed: invalid character 'a' looking for beginning of value
2018/02/28 17:00:56 decode params failed: EOF
2018/02/28 17:00:56 decode params failed: invalid character 'a' looking for beginning of value
--- FAIL: Test_injectTransactionHandler (0.00s)
    --- FAIL: Test_injectTransactionHandler/invalid_params:_invalid_raw_transaction (0.00s)
        Error Trace:    transaction_test.go:221
    	Error:      	Not equal:
    	            	expected: webrpc.Response{ID:(*string)(nil), Jsonrpc:"2.0", Error:(*webrpc.RPCError)(0xc420099d70), Result:json.RawMessage(nil)}
    	            	actual: webrpc.Response{ID:(*string)(nil), Jsonrpc:"2.0", Error:(*webrpc.RPCError)(0xc420099e60), Result:json.RawMessage(nil)}

    	            	Diff:
    	            	--- Expected
    	            	+++ Actual
    	            	@@ -3,3 +3,3 @@
    	            	  Jsonrpc: (string) (len=3) "2.0",
    	            	- Error: (*webrpc.RPCError)(invalid raw transaction: encoding/hex: odd length hex string [code: -32602]),
    	            	+ Error: (*webrpc.RPCError)(invalid raw transaction: encoding/hex: invalid byte: U+0067 'g' [code: -32602]),
    	            	  Result: (json.RawMessage) <nil>
2018/02/28 17:00:56 internal server error
2018/02/28 17:00:56 Invalid address length
2018/02/28 17:00:56 Invalid address length
2018/02/28 17:00:56 empty request params
2018/02/28 17:00:56 decode params failed:invalid character 'i' looking for beginning of value
2018/02/28 17:00:56 Start webrpc on http://127.0.0.1:8081
2018/02/28 17:00:56 Detected DNS rebind attempt - configured-host=127.0.0.1:8081 header-host=example.com
2018/02/28 17:00:56 Webrpc service closed
FAIL
FAIL	github.com/skycoin/skycoin/src/api/webrpc	0.240s
ok  	github.com/skycoin/skycoin/src/cipher	(cached)
?   	github.com/skycoin/skycoin/src/cipher/base58	[no test files]
ok  	github.com/skycoin/skycoin/src/cipher/chacha20	(cached)
ok  	github.com/skycoin/skycoin/src/cipher/chacha20/go-chacha20	(cached)
?   	github.com/skycoin/skycoin/src/cipher/chacha20/go-chacha20/chacha	[no test files]
ok  	github.com/skycoin/skycoin/src/cipher/encoder	(cached)
?   	github.com/skycoin/skycoin/src/cipher/go-bip39	[no test files]
?   	github.com/skycoin/skycoin/src/cipher/ripemd160	[no test files]
ok  	github.com/skycoin/skycoin/src/cipher/secp256k1-go	(cached)
ok  	github.com/skycoin/skycoin/src/cipher/secp256k1-go/secp256k1-go2	(cached)
ok  	github.com/skycoin/skycoin/src/coin	(cached)
ok  	github.com/skycoin/skycoin/src/consensus	(cached)
?   	github.com/skycoin/skycoin/src/consensus/public_broadcast_channel	[no test files]
ok  	github.com/skycoin/skycoin/src/daemon	(cached)
ok  	github.com/skycoin/skycoin/src/daemon/gnet	(cached)
ok  	github.com/skycoin/skycoin/src/daemon/pex	(cached)
?   	github.com/skycoin/skycoin/src/daemon/strand	[no test files]
2018/02/28 17:00:56 Droplet string conversion failed: Value is too large
2018/02/28 17:00:56 CSRF token invalid: invalid token
2018/02/28 17:00:56 CSRF token invalid: token has expired
2018/02/28 17:00:56 CSRF token invalid: invalid token
2018/02/28 17:00:56 CSRF token invalid: token not initialized
2018/02/28 17:00:56 CSRF token invalid: invalid token
2018/02/28 17:00:56 CSRF token invalid: token has expired
2018/02/28 17:00:56 CSRF token invalid: invalid token
2018/02/28 17:00:56 CSRF token invalid: token not initialized
2018/02/28 17:00:56 CSRF token invalid: invalid token
2018/02/28 17:00:56 CSRF token invalid: token has expired
2018/02/28 17:00:56 CSRF token invalid: invalid token
2018/02/28 17:00:56 CSRF token invalid: token not initialized
2018/02/28 17:00:56 CSRF token invalid: invalid token
2018/02/28 17:00:56 CSRF token invalid: token has expired
2018/02/28 17:00:56 CSRF token invalid: invalid token
2018/02/28 17:00:56 CSRF token invalid: token not initialized

**Comment by therealssj** [comment]
https://github.com/skycoin/skycoin/pull/1015
