### ISSUE TITLE
Remove SendOr404 and SendOr500

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1021]
`httphelper.SendOr404` and `httphelper.SendOr500` need to be removed. They don't work properly due to typed nils.

See: https://play.golang.org/p/sCLTQjpaR3I

The check for nil will have to be in the caller.  So all `wh.SendOr404(w, m)` calls become:

```go
if m == nil {
    wh.Error404(w, m)
    return
}

wh.SendJSONOr500(logger, w, m)
```

**Comment by therealssj** [comment]
why do we even 404 on this?
if the result is empty shouldn't we just return an empty response?

**Comment by gz-c** [comment]
>If the function coinSupply encounters an error and returns supply as nil

If it had an error it should return `nil, err` and treat it as a 500

The `Error404` call on `nil` coinSupply is a bug, HTTP responses cannot be written twice
