### ISSUE TITLE
make build-libc modifies libskycoin.h

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1027]
`make build-libc` (which is called implicitly via `make check`) modifies the `include/libskycoin.h` file.  This file contains a machine-specific path.
The `typedef _GoString_ GoString` change may be due to the use of go1.10

```
diff --git a/include/libskycoin.h b/include/libskycoin.h
index 31cad3a5..6b01e0b9 100644
--- a/include/libskycoin.h
+++ b/include/libskycoin.h
@@ -2,10 +2,22 @@

 /* package command-line-arguments */

+
+#line 1 "cgo-builtin-prolog"
+
+#include <stddef.h> /* for ptrdiff_t below */
+
+#ifndef GO_CGO_EXPORT_PROLOGUE_H
+#define GO_CGO_EXPORT_PROLOGUE_H
+
+typedef struct { const char *p; ptrdiff_t n; } _GoString_;
+
+#endif
+
 /* Start of preamble from import "C" comments.  */


-#line 3 "/Users/olemis/Documents/workspace/work/go/src/github.com/skycoin/skycoin/lib/cgo/main.go"
+#line 3 "/Users/steve/.gopath/src/github.com/skycoin/skycoin/lib/cgo/main.go"


 typedef unsigned char Ripemd160[20];
@@ -50,7 +62,7 @@ typedef double _Complex GoComplex128;
 */
 typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

-typedef struct { const char *p; GoInt n; } GoString;
+typedef _GoString_ GoString;
 typedef void *GoMap;
 typedef void *GoChan;
 typedef struct { void *t; void *v; } GoInterface;
```

**Comment by olemis** [comment]
In general, modification of `include/libskycoin.h` should be expected since it is generated by `make build-libc` . Nonetheless the file changes depending on local state (golfing version , architecture , etc ...) . I'll deal with this as part of this issue .

**Comment by olemis** [comment]
Since `libskycoin.h` is platform specific I'm starting to think it should be `.gitignore`'d . What d'u think @gz-c ?

**Comment by gz-c** [comment]
yes, although the exported go api has to declared somewhere?

**Comment by olemis** [comment]
+1 will do something about it , but for 0.22 ignoring it should be the way to go .
