### ISSUE TITLE
make check fails on OS X due to make build-libc

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1028]
This fails on OS X, the solution is to do `brew install snaipe/soft/criterion`

* The README should be updated to include this instruction for OS X machines wishing to build libskycoin
* libskycoin should not be built by default in `make check`.  Travis should perform the libskycoin test separately

```
mkdir -p build/usr/tmp build/usr/lib build/usr/include
mkdir -p build/libskycoin bin include
rm -Rf build/libskycoin/*
go build -buildmode=c-shared  -o build/libskycoin/libskycoin.so ./lib/cgo/main.go
go build -buildmode=c-archive -o build/libskycoin/libskycoin.a  ./lib/cgo/main.go
mv build/libskycoin/libskycoin.h include/
cp lib/cgo/tests/*.c build/libskycoin/
gcc -o bin/test_libskycoin_shared build/libskycoin/*.c -lskycoin                    -lcriterion -Iinclude -Ibuild/usr/include -L build/libskycoin -Lbuild/usr/lib
build/libskycoin/check_cipher.c:2:10: fatal error: 'criterion/criterion.h' file not found
#include <criterion/criterion.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [test-libc] Error 1
```

**Comment by gz-c** [comment]
Upon further review, 

`make install-deps-libc` should be documented in the "Client Libraries" section https://github.com/skycoin/skycoin#client-libraries of the README.

This section also says:

>Skycoin implements client libraries which export core functionality for usage from other programming languages. Read the corresponding README file for further details.

This corresponding README file should be linked to.

`make install-deps-libc` should detect OS X and use `brew install snaipe/soft/criterion`

**Comment by gz-c** [comment]
#1029 removes `make test-libc` from the list of targets for `make test`.  Travis will still run these tests.

**Comment by olemis** [comment]
@gz-c dependencies to run `make test-libc` are installed by the `make install-deps-libc` target . The later is not executed by the former because Criterion may be installed globally .

I did not use `brew install` version for MacOS X before because [I had some issues with that approach](https://github.com/Snaipe/homebrew-soft/issues/1#issuecomment-361086712) .

Should I use [Debian / Ubuntu packages](https://github.com/Snaipe/Criterion#packages) on Linux ?

**Comment by gz-c** [comment]
Since `make test-libc` is separated, it is sufficient to document installation instructions in the README
