### ISSUE TITLE
在并发发起交易的时候，出现错误

### ISSUE THREAD

**Issue by ChenYunerer** [skycoin/skycoin#1062]
在并发发起交易的时候，出现错误：http.go:241 Get balance failed: get unconfirmed spending failed when checking addresses balance: get unconfirmed spend error:unconfirmed transaction's IN: 4a7a48857dd1a12fda8757f673eace1dc1228d4594ca8b3df7f9e2df779e98bc is not in unspent pool

**Comment by iketheadore** [comment]
Don't spend coins before the previous spending transaction is confirmed.

**Comment by ChenYunerer** [comment]
I try to send transaction from different wallet at the same time, than i get the error

**Comment by iketheadore** [comment]
If you're sending from different wallet but with the same seed, this error means you can't double spend the same output.  

If two wallet have the same seed, they have the same unspent outputs, if `thread1` already spent `output1`, when `thread2` try to spend the `output1` again, you will get the above error.

**Comment by ChenYunerer** [comment]
I find another error : http: Accept error : accept tcp [::]10020:accept4: too many opern files; retrying in 1s, then I can not process transactions until I restart

**Comment by gz-c** [comment]
How long have you been running the node? How many requests have you made to it?  Which API port are you using?

**Comment by ChenYunerer** [comment]
I running the node about 30min, and made more than1000 requests using "/wallet/spend" api

**Comment by gz-c** [comment]
How do you make the request? Are you closing the request connection from your client?

**Comment by ChenYunerer** [comment]
I send http request by OkHttpClient, I don`t need to close connection by myself.  I changed system open file limit from 1024 to 8192,  After that I did not encounter this problem
