### ISSUE TITLE
Document all REST API endpoints in gui/README.md

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1065]
First, make a list of all undocumented REST API endpoints and share them here in a comment. Then begin documenting them.

**Comment by Vavilen** [comment]
Documented REST API endpoints:
- [x] /csrf
- [x] /version
- [x] /outputs
- [x] /balance
- [ ] /wallet
- [x] /wallet/create
- [x] /wallet/newAddress
- [x] /wallet/balance
- [x] /wallet/spend
- [ ] /wallet/transactions
- [x] /wallet/update
- [ ] /wallets
- [ ] /wallets/folderName
- [x] /wallet/newSeed
- [ ] /blockchain/metadata
- [ ] /blockchain/progress
- [x] /block
- [x] /blocks
- [x] /last_blocks
- [ ] /network/connection
- [ ] /network/connections
- [ ] /network/defaultConnections
- [ ] /network/connections/trust
- [ ] /network/connections/exchange
- [x] /pendingTxs
- [x] /transaction
- [x] /transactions
- [x] /injectTransaction
- [ ] /resendUnconfirmedTxns
- [x] /rawtx
- [x] /uxout
- [x] /address_uxouts
- [x] /explorer/address
- [x] /coinSupply
- [x] /richlist
- [x] /addresscount

**Comment by gz-c** [comment]
Already documented `/network` endpoints, updated the checkboxes

**Comment by Vavilen** [comment]
PR #1079
