### ISSUE TITLE
Integration tests against node with -disable-wallet-api

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1104]
Add a new integration test mode "wallet-disabled".  Node setup can be automated like the stable tests.

The node should be run with `-disable-wallet-api`.

The integration tests should confirm that none of the `/wallet` related APIs work, that the main index.html page does not load, and that a new wallet file is not created.

GUI checklist:

- [x] `/wallet`
- [x] `/wallet/create`
- [x] `/wallet/newAddress`
- [x] `/wallet/balance`
- [x] `/wallet/spend`
- [x] `/wallet/transactions`
- [x] `/wallet/update`
- [x]  `/wallet/newSeed`
- [x] `/wallets`
- [x] `/wallets/folderName`
- [x] No new wallet is created
- [x] No main index.html page is loaded

**Comment by iketheadore** [comment]
So we need to add a new script file in `ci-scripts`, like `integration-test-disable-wallet-api.sh`?

**Comment by gz-c** [comment]
`integration-test-disable-wallet-api.sh` and a matching `make` command

**Comment by iketheadore** [comment]
ok, I will add it.

**Comment by gz-c** [comment]
@iketheadore pr merged, update checklist
