### ISSUE TITLE
Temporary wallet load feature

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1109]
User should be able to load a wallet temporarily:

* Checkbox during "Load Wallet" to load the wallet temporarily
* After loading, wallet is stored unencrypted in memory 
* Wallet is not saved to disk

This allows users to restore a wallet from seed, perform some transaction with it and exit the client without retaining any wallet file on disk.

**Comment by iketheadore** [comment]
@Senyoret1 would you mind to implement this feature, the API for creating a temporary wallet is: `/api/v1/wallet/createTemp`.
