### ISSUE TITLE
[test] [util] Annotated hex dump

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#1110]
- [x] Render hex dump of binary buffer considering annotations
  * Helper function for hex dumps in `src/util` having three parametres
  * First parameter should be the object containing the data
  * Second one should be the annotations i.e. a list of `(index, name)` tuples where index is the buffer offset of the annotation and `name` its caption
  * Third parameter should be an instance of `io.Writer`
- [ ] Transform `MessageHexDump` function accordingly

**Comment by olemis** [comment]
@stdevEdu is there a patch for this already ?

**Comment by olemis** [comment]
@stdevEdu is there a patch for this already ?

**Comment by stdevEdu** [comment]
Performing PR :)

**Comment by olemis** [comment]
@stdevEdu is there a patch for this already ?
