### ISSUE TITLE
Ability to view unspent outputs for a wallet and addresses

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1120]
Transactions spend "unspent outputs" which affect how coinhours are burned.  Add a way to view these unspent outputs.  Related to #872

**Comment by mahansky** [comment]
How is this different from "Outputs" that's in the wallet now?

**Comment by gz-c** [comment]
They're not organized by wallet.

Also, we may want a way to see the outputs for a given address from a wallet, from the wallet page
