### ISSUE TITLE
The dollar price in banner won't be shown until all blocks are synchronized

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#1124]
![image](https://user-images.githubusercontent.com/2589926/37698444-f8cc03d0-2d1d-11e8-9909-fab5fc33055a.png)

**Comment by mahansky** [comment]
Just to be sure, you want there to be a price of 1 SKY in USD (since the whole balance is not available at that point)?

**Comment by gz-c** [comment]
yes just the amount in the parentheses, maybe put a dash where the pending balance would be
