### ISSUE TITLE
Return api errors in an error object

### ISSUE THREAD

**Issue by samuelvisscher** [skycoin/skycoin#1131]
This issue is a work in progress, please don't pick up before consulting with me or @gz-c 

Rewrite error responses to contain an error object, suggestion:

```
{
  "error": {
    "code": "duplicate_wallet_on_load",
    "message": "You already have a wallet based on this seed"
  }
}
```

**Comment by gz-c** [comment]
Part of #420

**Comment by gz-c** [comment]
This has begun for `/api/v2` responses
