### ISSUE TITLE
Preview/confirm transaction view in UI 

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1145]
Before sending, display a confirmation dialogue which shows all details of the transaction, including coinhours to be sent.

This requires a `/createRawTransaction` endpoint.

If we rely on something such as `/spend?preview=true`, then we must make sure that `/spend` is deterministic. This would be complicated and require additional parameters.

Instead, the API calls will need to be like:

`/createRawTransaction` - client displays this to the user
`/injectTransaction` - client provides the transaction to spend it

**Comment by samuelvisscher** [comment]
It would be really great if the underlying method could be used to create raw transactions in the web cipher and the mobile cipher. This would, for example, be possible if we would allow the underlying method to receive a list of inputs, destination address, destination amount, change address, or alternatively list of inputs and list of outputs.

**Comment by gz-c** [comment]
That should be handled by #872
