### ISSUE TITLE
decide on a uri-scheme to identify skycoin addresses

### ISSUE THREAD

**Issue by Skvuddudutt** [skycoin/skycoin#1147]
It would be good to have a standardised way of identifying a URI containing a skycoin address, for example "skycoin://". It could be used for registering system-wide handlers for skycoin addresses which is very useful in QR-codes used by mobile wallets.

**Comment by gz-c** [comment]
Need to figure out how to register these in OSX, Linux and Windows

**Comment by danielstrand** [comment]
yeah sure eventually. However this is really just a request for deciding on a schema. Actual implementation can be done separately. In my case it is for use in and iOS wallet where it is trivial to register these things.

**Comment by gz-c** [comment]
Is there any precedent for other coins?

**Comment by danielstrand** [comment]
I’m sure there are many. The only one I am immediately aware of is bip21 for bitcoin: https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki

**Comment by danielstrand** [comment]
Note that bip21 and the related ones are pretty large in an effort to standardize many behaviors and give many options for configuring. It might be easier for skycoin the make a more limited standard initially (maybe just dest-address and amount) which can then be a slander upon in the future.

**Comment by danielstrand** [comment]
Goddamn autocorrect 🙄 It should be expanded upon, not slandered upon...

**Comment by gz-c** [comment]
We can base this off of bip21, following the same rules set out there

We will add an `hours` field in addition to `amount`, `label` and `message`.

`skycoin:2hYbwYudg34AjkJJCRVRcMeqSWHUixjkfwY`
