### ISSUE TITLE
Transaction api response not clear

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#1153]
* What exactly is `TransactionResult.Time` vs `TransactionResult.Transaction.Timestamp` 
* Is `gui.NewReadableTransaction` broken? It uses `TransactionResult.Time` instead of `TransactionResult.Transaction.Timestamp` when creating a `gui.ReadableTransaction`
* `gui.getTransactionByID` returns `TransactionResult` but does not set the Time
* `time` field name is vague
* `time` field possibly belongs in `status` section
* `time` field is being used with two distinct meanings: for block time [confirmed txn] and received time [unconfirmed txn]

**Comment by therealssj** [comment]
@iketheadore

**Comment by iketheadore** [comment]
The time in `TransactionResult` is the same as it in `TransactionResult.Transaction.Timestamp`, can be refactored in versioned api.
