### ISSUE TITLE
Backwards compatible log messages with logrus

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#1161]
After #858 :

- [x] Hide module, and priority fields out of text messages (suggested by @iketheadore in #1149 )
- [x] Include log level in prefix
- [x] Add constant for `CRITICAL` priority .

**Comment by gz-c** [comment]
"Hide module, and priority fields out of text messages "
if you need these for machine parsing, it can be an option

**Comment by stdevStark** [comment]
The data already stays in entry but is not printed to stdout
