### ISSUE TITLE
bug in wallet address calculation

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#1175]
If I have a wallet and I add the private key of one of the addresses of that wallet to a new wallet then the balance is counted twice
<img width="1105" alt="screen shot 2018-04-02 at 3 29 52 am" src="https://user-images.githubusercontent.com/8619106/38177959-4db1be92-3626-11e8-85c2-2c36112383fe.png">

**Comment by gz-c** [comment]
Frontend might be using the /wallet/balance API which calculates each wallet's balance independently.  They'd need to use a different API to get the outputs across all wallets and tally up the coins themselves while deduplicating outputs
