### ISSUE TITLE
Compile Criterion in make install-deps-libc

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#1182]
Aforementioned make target currently downloads Citerion binaries . Those do not include functions needed by the test suite (e.g. assertions for custom types) . Instead Criterion bleeding branch should be checked out , compiled and installed locally in `./build` .

**Comment by stdevEdu** [comment]
@olemis, please close this issue. I don't know why it didn't close automatically...

**Comment by olemis** [comment]
fixed in #1195
