### ISSUE TITLE
ng serve removes dist folder

### ISSUE THREAD

**Issue by mahansky** [skycoin/skycoin#1208]
After running `npm start` or `ng serve --proxy-config proxy.config.js`, dist folder gets deleted, what is not ideal since it's tracked by git.

Possible solution is to change output dir to something else as mentioned [here](https://github.com/angular/angular-cli/issues/4366#issuecomment-277258810)

**Comment by gz-c** [comment]
what about ng serve --delete-output-path false

**Comment by mahansky** [comment]
Yeah, that works just fine!

**Comment by gz-c** [comment]
can you update the frontend readme with this instruction

**Comment by mahansky** [comment]
What should be written there? I think that this is expected behaviour

**Comment by gz-c** [comment]
nothing, i thought it needed the user to add the flag, it's in the script already
