### ISSUE TITLE
Refactor gui gateway methods

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#1213]
```
GetUxOutByID(id cipher.SHA256) (*historydb.UxOut, error)
GetAddrUxOuts(addr cipher.Address) ([]*historydb.UxOutJSON, error)
```
would be better if both had the similar return type of `historydb.UxOut` 
`GetAddrUxOuts` should just convert `historydb.UxOut` to `historydb.UxOutJSON` before sending the response

Also there is no method to get `UxOut` for multiple addresses
maybe change `GetAddrUxOuts(addr cipher.Address)`  to `GetAddrUxOuts(addr []cipher.Address)`?

**Comment by stgleb** [comment]
I can take this one
