### ISSUE TITLE
Wallet API returns boolean as string

### ISSUE THREAD

**Issue by mahansky** [skycoin/skycoin#1220]
@iketheadore #1189 

Endpoints `/wallet`, `/wallets`, `/wallets/create` return `encrypted` as string instead of boolean as other endpoints.

Expected output:
```diff
{
    "meta": {
        "coin": "skycoin",
        "cryptoType": "",
-       "encrypted": "false",
+       "encrypted": false,
        "filename": "***",
        "label": "Wallet",
        "lastSeed": "",
        "secrets": "",
        "seed": "",
        "tm": "1523265861",
        "type": "deterministic",
        "version": "0.1"
    },
    "entries": [
        {
            "address": "***",
            "public_key": "***",
            "secret_key": ""
        }
    ]
}
```

**Comment by iketheadore** [comment]
The `meta` field of wallet is type of `map[stirng]string`, so all it's value are strings.

**Comment by gz-c** [comment]
api should not care about internals of wallet package, convert to the correct output in the gui layer

**Comment by iketheadore** [comment]
ok, I will convert it to boolean

**Comment by gz-c** [comment]
remove the seed, last seed, secrets keys as well
