### ISSUE TITLE
Problem with making libc because of dependant types

### ISSUE THREAD

**Issue by stdevEclipse** [skycoin/skycoin#1221]
Some functions depend on types that need to be converted to C in order for the function to be converted

**Functions that depend on external libraries:**

- Visor/Visor/* depends on bolt.DB  "github.com/boltdb/bolt"
- Daemon/Daemon/* depends on Visor
- api/cli/cli.NewApp depends on App, App depends on App "github.com/urfave/cli"
- gui/gui/CreateHTTPS depends on Daemon
- util/elapse/elapse/* depends on logging.Logger
- util/http/httphelper/* depends on logging.Logger
- util/logging/logging/* depends logging.Logger "github.com/sirupsen/logrus"

**Function that depend on GO standard libraries**

- cipher/secp256k1-go/secp256k1-go2/secp256k1go/* depend on Number, Number depends on big/Math
- daemon/gnet/gnet/* depends on bytes.Buffer, net.Conn, time.Time
- daemon/pex/pex/* depends on time.Duration
- gui/gui/CSRFCheck depend sync.RWMutex
- wallet/wallet/* depend on sync.sync.RWMutex

**Comment by gz-c** [comment]
Do we need to expose all of this in libc? Only the cipher package and subpackages are really needed for language integration

**Comment by stdevEclipse** [comment]
That is what I think.

**Comment by olemis** [comment]
@stdevEclipse I think the goal of this issue is the same as #1191 . Therefore I'm closing this issue and invite you to follow the conversation over there .
