### ISSUE TITLE
Show calculated hours instead of raw hours in outputs

### ISSUE THREAD

**Issue by mahansky** [skycoin/skycoin#1239]
Example output of API:
```json
{
  "hash": "ffb1a1d666e98e8af2699437cb86d54566a26d72c5188f9b04445a579011c820",
  "time": 1523788076,
  "block_seq": 22853,
  "src_tx": "fa5331f38ed0df9871b83aec140b448666b56d3976d52ef3acb7346a3ae12f9c",
  "address": "2GgFvqoyk9RjwVzj8tqfcXVXB4orBwoc9qv",
  "coins": "563.000000",
  "hours": 293,
  "calculated_hours": 13981
}
```

Frontend shows `hours` instead of `calculated_hours` in Outputs, is that ok or should it be the other way?

**Comment by gz-c** [comment]
can it show both?

**Comment by mahansky** [comment]
sure, what about column names? because "Hours" and "Calculated hours" is a bit confusing. Calculated hours are being burned, I would say they are more important.

**Comment by gz-c** [comment]
show calculated hours by default for the user, the original hours are mostly of interest for diagnostic
