### ISSUE TITLE
Prevent browser from suggesting to save wallet password

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1249]
After encrypting a wallet, chrome suggests to save the password with no username.  This should be disabled if possible.

This may solve it:
https://stackoverflow.com/questions/32369/disable-browser-save-password-functionality/37292424#37292424

[This issue does not apply until #1230 is merged]

**Comment by mahansky** [comment]
That solution doesn't seem to work, I found `autocomplete="new-password"` which works, but is not supported in all browsers (works in Chrome).
