### ISSUE TITLE
Implement transaction notes API in backend

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1256]
Frontend design has a "note" field when sending, but this does nothing because the backend does not support it.

Backend APIs should expose method(s) for setting and retrieving notes for specific transactions.  Notes should be saved in the data dir.

**Comment by olemis** [comment]
so do notes go away if the wallet directory is removed ?

**Comment by gz-c** [comment]
Notes should be saved in data dir not wallet dir, since notes are tied to specific transactions and not to wallets
