### ISSUE TITLE
In the Create Wallet panel, add instruction to write the seed down in a safe place

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1262]
Don't store it on a computer etc

We could probably copy this from another wallet that gives such an instruction like electrum

**Comment by mahansky** [comment]
I found this warning in the design files
![screen shot 2018-04-18 at 15 03 05](https://user-images.githubusercontent.com/1536298/38933567-a513b190-4319-11e8-81e6-bcd79de40c80.png)

But this modal from setup wizard could be also reused
![screen shot 2018-04-18 at 15 02 56](https://user-images.githubusercontent.com/1536298/38933568-a53aaea8-4319-11e8-9310-da488c7f90dd.png)

**Comment by gz-c** [comment]
We can use the warning in the first picture
