### ISSUE TITLE
Use string translation object for frontend

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1263]
Use the string translation object thing that i18n uses so we can support multiple languages and also make it easier to modify the frontend for other coins (e.g. so they can replace SKY with their coin's label with one line)

**Comment by Senyoret1** [comment]
This comment may be relevant: https://github.com/skycoin/skycoin-explorer/issues/165#issuecomment-383255241

**Comment by gz-c** [comment]
ngx-translate was used in explorer, @Senyoret1 is that fine to use here too?

**Comment by Senyoret1** [comment]
I guess so. Nothing comes to mind against it.
