### ISSUE TITLE
go 1.10.x sometimes fails in travis with no clear reason [flaky]

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1272]
Sometimes the travis build for go 1.10.x fails in the integration test script.

However, there is no clear reason for failure, just the exit code is wrong.  No other output suggests a failure.

It fails different ways,

Example one, `GUI_FAIL=1`:
https://gist.github.com/gz-c/e317fd55fdd05364711f74e72d3bb26a 

Example two, `make: *** [integration-test-stable] Error 1`:
https://gist.github.com/gz-c/fd5ab7359636a0d6820c87048222ef07
Travis Job: https://travis-ci.org/skycoin/skycoin/jobs/367960333

**Comment by gz-c** [comment]
The log output from the gui tests are being truncated, see https://travis-ci.org/skycoin/skycoin/jobs/368419111#L2188

**Comment by gz-c** [comment]
Update:

- verbose test output has been disabled so the logs are not truncated
- multiple `make integration-test-*` calls are now done in travis, requiring a node to be built, run, and stopped multiple times

New, possibly related failure:

https://gist.github.com/gz-c/3b195881ea3ae0117376b19fb3a7fdd8

The 2nd `make integration-test-*` attempt fails to start the node due to occupied port, however the logs suggest that the node shut down fine in the previous run

**Comment by iketheadore** [comment]
Fixed in https://github.com/skycoin/skycoin/pull/1543
