### ISSUE TITLE
Randomize web interface port when running as desktop wallet

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1275]
If an attacker has access to the machine, they could bind to the standard port while the backend node is off, and in some cases, this could result in the wallet communicating to a malicious backend.  Randomize the web interface port when running as a desktop wallet to reduce the feasibility of this attack.

**Comment by olemis** [comment]
@stdevHan can you fix this asap ?

**Comment by gz-c** [comment]
Requires #1542 to complete
