### ISSUE TITLE
Use 401 response to detect invalid password and display message, separate from 400 error messages

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1295]
Depends on #1290

**Comment by mahansky** [comment]
Is #1293 sufficient or should I be explicit about 401?

**Comment by gz-c** [comment]
@mahansky 

Guideline to error codes:
400 - request data problem, use the request body if not empty, itll include the error message
401 - "invalid Password"
403 - "API Disabled"
404 - "Wallet does not exist"
500 - flash the red error banner if we still have it

for all of the endpoints that take password
