### ISSUE TITLE
(Wallet) Create 2 wallets with the same seed

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1298]
Surely this is super low priority, but if the user creates a wallet with a seed and then tries to create or load a second wallet with the same seed, the wallet is not created and the create button shows the loading animation indefinitely , without displaying an error message.

**Comment by gz-c** [comment]
@Senyoret1 does the API return an error?

**Comment by iketheadore** [comment]
This API would return error if try to create wallet with the same seed.

**Comment by gz-c** [comment]
@Senyoret1 is that actually the format of the JSON response?

**Comment by Senyoret1** [comment]
No, it is the JSON representation of the error object generated in TypeScript (the object has more information, I just copied portion of it). In fact, I don't know exactly how the JSON returned by the node is. Sorry for not clarifying it.
