### ISSUE TITLE
The minimum length of the seeds is very short

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1300]
When creating or loading a wallet, it is possible to manually write the seed. At this time, the form have validators requiring the seed to have at least one character. Maybe, for security, the validators should force the user to use a much larger number of characters, maybe 40.

Another option could be to disable the ability of the user for editing the seed when creating a new wallet.

Since the option for loading a wallet is, basically, the same as creating a new one, the validation should probably be when creating and when loading a wallet, but that could cause problems for anyone with a previously created wallet with a short seed, and it seems unlikely that a users would use the option to load a wallet just to create a new one. Because of this, the requirement for more characters could be active just when creating a new wallet.

If any of those changes is implemented, it must be incorporated into https://github.com/skycoin/skycoin/pull/1238 or a new pr after https://github.com/skycoin/skycoin/pull/1238 is merged.

**Comment by gz-c** [comment]
We want to allow the user to edit the seed.  One use case is adding your own secret password to the end of the seed.  In this way, you can add a layer of protection to a paper seed, by only memorizing a reduced password (some users do this).
