### ISSUE TITLE
API endpoints to decode and validate an encoded transaction

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1306]
`POST /transaction/decode`
`POST /transaction/validate`

JSON body: `{"encoded_transaction": "..."}`

Returns the transaction decoded as JSON (preferably use the transaction object returned by `POST /wallet/transaction` that will be added by #1223, otherwise a visor.ReadableTransaction)

Error 400 if invalid JSON, encoded_transaction is missing or cannot be decoded to bytes
Error 422 if transaction validation fails

*This spec needs some refinement*

**Comment by iketheadore** [comment]
The `POST /wallet/transaction` response contains the encoded transaction, do we still need to return the encoded_transaction string.

**Comment by iketheadore** [comment]
Maybe we can just return `CreatedTransaction` struct

**Comment by gz-c** [comment]
Can omit encoded transaction from the response.

I don't know if we need two separate endpoints. Maybe only validate. But even if transaction is not valid, it can still be decoded, and maybe there is a use for that.

**Comment by iketheadore** [comment]
Yes, invalid transaction can still be decoded. For now, it's useless I think, as the `POST /wakket/transaction` returns the transaction details with the encoded transaction string. 

Maybe we can only have the `/transaction/validate`, and return decoded transaction with an additional field of `validate` to indicate whether the transaction is validate. The decode transaction details can be used for caller to check if the `encoded_transaction` in `POST /wallet/transaction` response does perform the same action as it shows in the transaction field.

**Comment by gz-c** [comment]
It's useful because we will have a system where a transaction is created offline, then the user takes the encoded transaction (maybe through QR code) and loads it into an online wallet. We would want to be able to show them the transaction details again before sending.  There are similar use cases like this.

I am thinking we should have one endpoint that both verifies and decodes.

If the transaction is decodable, it includes the transaction in the JSON response.
If the transaction is not valid, it includes "error" in the JSON response and uses code 422.

However, we don't normally return JSON for non-200 responses (although we should). So this has an inconsistency with the rest of the API, which can make the client implementation more complicated.

Maybe this endpoint should always return JSON for non-200 responses, and not only 422.  In that case we would use some standard object like

```json
{"error": "...", "data": "..."}
```

for the response.

In API v2, we would use this format for all responses.

**Comment by iketheadore** [comment]
OK, we can have the `/transaction/decode` endpoint and the use 

```json
{"error": "...", "data": "..."}
```
for the response

**Comment by gz-c** [comment]
Use `/transaction/verify`, if we need to offer decode without verify later, we'll put that on `/transaction/decode`
