### ISSUE TITLE
Add -enable-gui option

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1318]
This option will enable the serving of static GUI content.  Run it by default in run.sh and electron.

**Comment by iketheadore** [comment]
So we should remove the control of static GUI content from -enable-wallet-api option, as we now if -enable-wallet-api is false, the static GUI contents are disabled.

**Comment by gz-c** [comment]
-enable-wallet-api=false would also force -enable-gui=false, but if -enable-wallet-api=true, then let the user separately do -enable-gui=false if they want.  This way they can have the wallet API, but not have the UI.
