### ISSUE TITLE
Tool to monitor peers.txt IP addresses

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1329]
Create a tool (either a new cli command or a new `cmd/` binary) that takes in a list of peers (ip:ports, newline separated, skipping comments and empty lines (a function exists somewhere in the `daemon` or `pex` package to parse this format)).  The tool connects to each of the peers, waits for the introduction packet (or times out) and produces a report with the status of the peer (unreachable, reachable, sent_introduction, introduction_parameters).  Introduction_parameters were added in v0.25.0 so will be absent for earlier peer versions.

The initial purpose is to check the status of peers in https://downloads.skycoin.net/blockchain/peers.txt

**Comment by stdevHan** [comment]
@gz-c  the file peers.txt to modify is `$DATA_DIR/peers.txt` or `skycoin/skycoin/peers.txt` ?

**Comment by olemis** [comment]
@stdevHan IMO monitoring should be for $DATA_DIR/peers.txt . @gz-c cmiiw

**Comment by stdevHan** [comment]
@gz-c  What would be the threshold? or would only be deleted what they have no connection and are not trusted?

**Comment by olemis** [comment]
@stdevHan thresholds , parameters , ... everything that can be configurable , should be .

**Comment by gz-c** [comment]
This tool is for us to use, not for everyone to use.  We want to make sure the peers.txt bootstrap file is kept clean. 

The input is a file with a list of ip:ports.

It should connect to each ip:port and receive an introduction message, then disconnect.  If we are unable to connect or do not receive an introduction message within some timeout (say, 5 seconds, make this configurable) report the ip:port as bad.  If easy, include the time it takes to establish the connection, and the time to receive the introduction message.

**Comment by olemis** [comment]
@gz-c sorry for not understanding this correctly but some context was missing . @stdevHan will get this done . Thanks for clarifying this .
