### ISSUE TITLE
(Wallet) Error messages formating.

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1353]
The error messages returned by the node have a format similar to this "400 Bad Request - Error message". ButtonComponent removes the unnecessary first part using this: https://github.com/skycoin/skycoin/blob/develop/src/gui/static/src/app/utils/index.ts#L1 . However, the error messages displayed with the snackbar still show the errors as they are returned by the node.
![photo_2018-04-20_06-38-03](https://user-images.githubusercontent.com/34079003/39140620-224e8b44-46f3-11e8-8da3-2a400bd04094.jpg)
Ideally, error messages should be processed the same as in ButtonComponent.

**Comment by gz-c** [comment]
I think it is useful to see the error code, at least if the code is not 400

**Comment by mahansky** [comment]
Are you using the latest code? It is already there
https://github.com/skycoin/skycoin/blob/da6877a09c32e986e199e72e891e3c1da60c5f53/src/gui/static/src/app/components/pages/send-skycoin/send-skycoin.component.ts#L68 

![screen shot 2018-04-24 at 16 45 41](https://user-images.githubusercontent.com/1536298/39194913-f9a24ad6-47de-11e8-93fb-1e6353fbcb16.png)

Also, error codes can be more confusing than helpful for non-dev users. After all, if you need to debug something, you can always open DevTools.

**Comment by Senyoret1** [comment]
My bad, I had the problem noted for a long time and I did not verify that it had been solved. I suppose the issue can be closed, unless @gz-c wants some change.

**Comment by mahansky** [comment]
#1373 formats only 400 and 403 error messages
