### ISSUE TITLE
Wallet does not show error when add address fails

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1386]
Steps to reproduce:

On Windows,

Run the wallet software
Create a new wallet
Shutdown the wallet software
In the windows file explorer, make the wallet file "hidden"
Run the wallet software again
Try to add a new address

This could probably be replicated on OSX and Linux by removing read and write permissions from the file instead of marking it "hidden".

Result:
- No address is added
- No error is displayed

In the logs, we see the error:

2018-04-25T23:32:20-05:00] ERROR [gui]: 400 Bad Request - open C:\Users\name\.skycoin\wallets\2018_04_25_02e3.wlt: Access is denied.
[2018-04-25T23:32:20-05:00] ERROR [gui]: 400 POST /wallet/newAddress 9.025ms body="400 Bad Request - open C:\Users\name\.skycoin\wallets\2018_04_25_02e3.wlt: Access is denied."

**Comment by Senyoret1** [comment]
The issues was solved in https://github.com/skycoin/skycoin/pull/1391 . However, as reported by @mahansky in telegram, a .wlt.tmp file is created with the new address and it is possible to see the new address after refreshing the browser. Keeping that in mind, it is still necessary to fix the problem in the backend.
