### ISSUE TITLE
[lib] Restore libskycoin.h in README link

### ISSUE THREAD

**Issue by stdevEdu** [skycoin/skycoin#1394]
Readme: https://github.com/simelo/skycoin/tree/develop/lib/cgo/README.md
broken link: https://github.com/simelo/skycoin/blob/develop/include/libskycoin.h

**Comment by gz-c** [comment]
Status?

**Comment by gz-c** [comment]
@olemis

**Comment by gz-c** [comment]
libskycoin moved to github.com/skycoin/libskycoin
