### ISSUE TITLE
Wallet state is inconsistent after modification if wallet save fails

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1397]
Following on #1386 

When modifying a wallet, the final save can fail if the wallet file does not have write permissions [e.g. if the file is "hidden" on windows].  This leaves the internal wallet in an inconsistent state, since the internal wallet will have the new changes but the saved wallet does not. 

Rollback functionality could be difficult and bug prone, but investigate if it is possible (by working with copies of *Wallet and delaying the service.Wallets update).

If rollback functionality is not simple, another option is to test if the wallet file is writeable before performing the operation.

**Comment by therealssj** [comment]
can't we check beforehand whether we have the correct permissions or not?

**Comment by gz-c** [comment]
We'll probably do that; rollback would be the ideal solution but may not be worth the complexity (although it may be simple since we work with copies of the wallet object, it could be that we are updating the wallet.Service object too soon)
