### ISSUE TITLE
[api] [gui] Implement multicall API endpoint

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#1413]
Implement a `multicall` API endpoint so as to package several API calls into a single one .

Existing specs and implementations:

- [XML-RPC multicall RFC](http://web.archive.org/web/20060824100531/http://www.xmlrpc.com/discuss/msgReader$1208)
- [Trac XML-RPC](https://trac-hacks.org/wiki/XmlRpcPlugin#PythonEnd-UserUsage)
- [Magento SOAP API](https://devdocs.magento.com/guides/m1x/api/soap/introduction.html#Introduction-APIMethods)
- [Drupal API](https://api.drupal.org/api/examples/xmlrpc_example%21xmlrpc_example.module/function/xmlrpc_example_client_multicall_submit/7.x-1.x)
- [Flask XML-RPC](https://pythonhosted.org/Flask-XML-RPC/)
- [Kaltura](https://knowledge.kaltura.com/kaltura-api-usage-guidelines)
- [Facebook](https://developers.facebook.com/docs/graph-api/making-multiple-requests#simple)

**Comment by therealssj** [comment]
prolly version the api https://github.com/skycoin/skycoin/issues/485
then make it part of a `/v2` along with these https://github.com/skycoin/skycoin/issues/420

**Comment by gz-c** [comment]
What is the purpose?

**Comment by gz-c** [comment]
https://developers.facebook.com/docs/graph-api/making-multiple-requests#simple

**Comment by gz-c** [comment]
there's a few different batch API approaches, Facebook's seems the simplest, using json. Google's uses delimiters between full http request and response bodies which would require trickier middleware work on both ends to encode and decode

**Comment by olemis** [comment]
Beware of the fact that starting March 2019, in the case of Google APIs [only homogeneus batch requests can be grouped in same call](https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html). If such a situation happens , API sets #1897 might be helpful .

**Comment by gz-c** [comment]
the change in google is due to their own architecture constraints which don't apply here. it's fine for us to implement a batch call, although websockets might achieve the same or better performance (or http2?)

**Comment by olemis** [comment]
@gz-c does web sockets limit the solution to the browser , nodejs and similar environments ?

**Comment by gz-c** [comment]
@olemis i dont think so
