### ISSUE TITLE
Fix electron node.js integration enabled warning

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1414]
The first warning in the screenshot should be eliminated; node.js integration is supposed to be disabled

<img width="1010" alt="screen shot 2018-05-02 at 11 25 23 am" src="https://user-images.githubusercontent.com/26845312/39504136-346728bc-4dfc-11e8-9644-dc9d0612164c.png">

**Comment by gz-c** [comment]
Here is the electron security checklist:

https://electronjs.org/docs/tutorial/security#checklist-security-recommendations

We need to go through this and make sure everything follows this at minimum

**Comment by iketheadore** [comment]
I can't see the electron warning, weird.

**Comment by mahansky** [comment]
I don't see the warning either + it is disabled 
https://github.com/skycoin/skycoin/blob/b07816e7c0ed326850c5d54838dee16473b26eb3/electron/src/electron-main.js#L144

**Comment by gz-c** [comment]
Apparently this warning is only appearing in builds I've made locally
