### ISSUE TITLE
CLI does not work anymore

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#1418]
We removed the port `6430`

Not sure where we moved rpc too

**Comment by olemis** [comment]
@gz-c what shall be done ? Shall we bring JSON-RPC back ?

**Comment by gz-c** [comment]
We didn't remove port 6430.  Port 6430 is disabled by default (`-rpc-interface=false`) when running via electron or using `run.sh`.

**Comment by therealssj** [comment]
https://github.com/skycoin/skycoin/pull/1321#pullrequestreview-117620696
Ah I got confused becoz of this PR!
I remembered reading that we were removing 6430 but didnt realize it wasnt merged yet.
Once the above PR is merged we do need to change the cli port.
