### ISSUE TITLE
Advanced spend UI

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1423]
Create a new UI view for "advanced spend" which allows the user to control the parameters of the `POST /wallet/transaction` API.

We need to design the UI for this first.

Parameters:

- Which addresses to spend from (must be from the same wallet)
- Multiple destination addresses with coins.  Hours can be optionally specified.  If hours are specified for one they must be specified for all.
- Change address
- "Automatic" hours allocation.  Allow control of share factor percentage.

In the future, we'll let them choose which outputs to spend, but the API doesn't support this yet.

**Comment by therealssj** [comment]
A slider would look cool for share factor allocation with real time display of coinhours being allocated

**Comment by gz-c** [comment]
I'm thinking the slider would be buried
Something like,

```
[x] Automatic [ ] Manual
(+) Automatic options
(-) Automatic options
    Mode: [Share]
    [-----o-----] 50% Coin Hour Sharing
    [----------o] 100% Coin Hour Sharing
```

i.e. Clicking "automatic options" would expand selector panel for "mode" and "share_factor".  "mode" would be a drop down selector and when mode is "share" then it would display the share factor slider.

Choosing "Manual" would hide the "automatic options" button.

**Comment by mahansky** [comment]
What do you think about something like this?
Addresses are multi-select, destinations can be added/removed
Coins input will be shown/hidden based on checkbox below

![screen shot 2018-05-17 at 16 09 43](https://user-images.githubusercontent.com/1536298/40182915-cbb8ebb4-59ec-11e8-8c84-2e659b938e37.png)

**Comment by gz-c** [comment]
I'd have to use the addresses selector to say, it's not obvious how that works looking the input.

Value slider should show the %

Note that when using automatic hours, destination hours can't be provided.  So the "hours" should be hidden in that case.  I think the options for automatic hours allocation should be hidden by default.

**Comment by mahansky** [comment]
When you click the addresses, there is a selection like this one:
![screen shot 2018-05-18 at 12 42 29](https://user-images.githubusercontent.com/1536298/40230735-fb757b04-5a98-11e8-9b34-3c02699dbb67.png)

And I know about the hours input, I just wanted to show everything at once.

**Comment by gz-c** [comment]
We'll have to show the coins and hours per address too

**Comment by mahansky** [comment]
It can be appended to every address, similarly to wallets
`address - 20 SKY (100 hours)`
