### ISSUE TITLE
Add Content-Security-Policy header to HTTP responses

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1426]
`Content-Security-Policy: script-src 'self' <host>`

Also add a cli flag, `-disable-csp`, which will disable this header.

**Comment by mahansky** [comment]
`ng serve` uses `eval()` which violates this CSP

I can think of two solutions
1. add header on server side, but only when the app is running in "production" mode (after build)
2. add meta tag to index.html using javascript

Also, going a bit further, if the first option is selected, CSP policy could be improved to contain hashes of js files

**Comment by gz-c** [comment]
What is `ng serve` used for? development?

**Comment by gz-c** [comment]
If it's only a development thing, we can add a cli flag to disable it

**Comment by mahansky** [comment]
Yes, it's just for development, cli flag is ok
