### ISSUE TITLE
Skycoin-dev image with GUI VSCode IDE

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#1434]
Build a Docker image with [Visual Studio Code](https://code.visualstudio.com) added , considering either [VS Code](https://github.com/hackenfreude/docker-vscode/issues/new) [image](https://hub.docker.com/r/hackenfreude/vscode/) or [Jess Frazelle's Dockerfile](https://github.com/jessfraz/dockerfiles/tree/master/vscode) .

- [ ] Parameterize base image to build from either `skycoin/skycoindev-cli:develop` or `skycoin/skycoindev-cli:dind`
- [ ] Include / automate repo-info metadata
- [ ] Mention VS Code image in [development Docker images section](https://github.com/skycoin/skycoin/blob/develop/README.md#development-image) .

**Comment by olemis** [comment]
@stdevYuniers pls remind me to assign you this issue once you accept joining Skycoin org .

**Comment by stdevYuniers** [comment]
@olemis please, assign this issue to me
