### ISSUE TITLE
Cipher output test suite

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1436]
Create a test suite that compares the output of cipher operations against "golden" files, i.e. data generated once with a current version.  This is to ensure the output of cipher does not change.

Use a set of 10 random seeds.  5 of them should be generated with `bip39.NewDefaultMnemomic()` and 5 should be generated with `cipher.SumSHA256(cipher.RandByte(1024))`.
Generate 10 deterministic <pub, sec, addr> sets from each of these seeds.  Check that the same values are always generated.

Use a set of 10 different random SHA256 hashes (generate 32 random byte and convert to `cipher.SHA256`). Add the null hash (all 0s), and a hash of all 1s to this list.
For each hash and secret key, generate a signature.  Check that the signature matches the known signatures.

Structure the golden file data such that it can be reused for other library implementations to test their output. e.g. libskycoin could use this data to verify that its cipher library is correct.

Additional specific tests, add a golden file for each:

- Using a seed of length 1, generate 10 addresses
- Using a random seed, generate 1000 addresses. Since this file would be large, don't add signatures, this one is only for checking address generation.

**Comment by olemis** [comment]
another target could be skycoin/skycoin-cipher-web library

**Comment by gz-c** [comment]
Golden files to create:

- inputs.golden, which contains a newline-separate list of base64 encoded random byte arrays as described above

- For each seed, a new golden file seed-$n.golden, with the data saved as json in this format:
```json
{"seed": "...", "keys": [{"address": "...", "secret": "...", "public": "...", "signatures": ["..."]}]}
```

Where "signatures" array is the signatures of the data from `inputs.golden`
