### ISSUE TITLE
[cipher] [encoder] Support for decoding maps

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#1437]
It seems that `cipher/encoder` can encode maps

https://github.com/skycoin/skycoin/blob/b4789ec47b8f7fbb2c19f208adca326ec9a85b1c//src/cipher/encoder/encoder.go#L865

https://github.com/skycoin/skycoin/blob/b4789ec47b8f7fbb2c19f208adca326ec9a85b1c/src/cipher/encoder/encoder.go#L421

But can not decode them

https://github.com/skycoin/skycoin/blob/b4789ec47b8f7fbb2c19f208adca326ec9a85b1c/src/cipher/encoder/encoder.go#L619

https://github.com/skycoin/skycoin/blob/b4789ec47b8f7fbb2c19f208adca326ec9a85b1c/src/cipher/encoder/encoder.go#L746

Methods of decoder do not handle `reflect.Map`. Struct with map field can be encoded, by attempt to decode it back will lead to panic.

**Comment by gz-c** [comment]
Must make sure that the map encoder actually works

**Comment by olemis** [comment]
@gz-c tests included in #1439 .
