### ISSUE TITLE
Client should use /wallet/balance instead of /balance endpoint

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1450]

**Comment by mahansky** [comment]
`/balance` is required, since it is used to show balance of each address in a wallet

**Comment by therealssj** [comment]
maybe we should modify `/wallet/balance` to have the overall balance as well the balance of the underlying address.
does not make sense to make so many calls

**Comment by gz-c** [comment]
Yes, we should change /wallet/balance, new issue #1462

**Comment by gz-c** [comment]
@mahansky /wallet/balance includes balances for individual addresses now
