### ISSUE TITLE
Instead of cleaning up the seed input value, warn the user if the seed needs cleaning

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1459]
Instead of transforming the seed input (replacing multiple spaces, trimming), display a warning to the user if their seed would be different after transformation.

The user should still be allowed to use these values as seeds.

**Comment by therealssj** [comment]
trimming around the seed makes sense

**Comment by gz-c** [comment]
Can probably leave the trimming around the seed, but I did not realize we were also changing multiple spaces between words, which can be valid, we don't want to transforms the user's input unexpectedly.

Although I'd rather the trimming around the seed be limited to stripping a single \n or \r\n off of the end

**Comment by therealssj** [comment]
oh. didnt know we were doing that. bad practice for sure. should definitely just stick to trimming around like u said.
