### ISSUE TITLE
(Proposal) Wallet screen design

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1466]
https://github.com/skycoin/skycoin/pull/1411 made good improvements to the UX. However, here are some aditional changes that could be added improve the UX a little more (please open it in full size):

![wallets](https://user-images.githubusercontent.com/34079003/39849857-6cb7bd04-53dc-11e8-81b0-747d57e0e2b6.png)

The idea is to put each wallet in a separate box, to avoid the visual congestion of the current design, and place the operation buttons on the top, as was suggested in https://github.com/skycoin/skycoin/issues/1250. A detail to keep in mind is that it may be good to put the buttons below as well if the wallet has many addresses.

It is relatively difficult to place the buttons above without making the design confusing, that is why the change in appearance is a bit pronounced. However, design has a lot to do with opinion, so I just leave this for consideration.

**Comment by Senyoret1** [comment]
There should be no problem in modifying that. At this moment it is just a bitmap made with an image editor.

**Comment by mahansky** [comment]
I like it as well, there is just one thing I would change:
![screen shot 2018-05-10 at 12 32 02](https://user-images.githubusercontent.com/1536298/39865944-ebdf7b0e-544e-11e8-9e50-db54cf9397f3.png)
It looks good when the wallet is closed, but after you open it and you see the table layout with headers, it is a bit off. I wonder what it would look like with the original "headers" so wallets wouldn't have it written there.
Also, the headers could be reused in another table views (pending txs, outputs).

**Comment by Senyoret1** [comment]
Thanks for the feedback. I made two small variations.

This has better alignment between the internal elements and a little less space between wallets:

![change1](https://user-images.githubusercontent.com/34079003/39968016-3901fc80-5694-11e8-81de-6388ef3fe7ed.png)

This other has the header at the top, like the current design, and a little less space between wallets, like the previous one:

![change2](https://user-images.githubusercontent.com/34079003/39968024-59f1fa12-5694-11e8-99e5-4541f0425c63.png)

I think the first one is more cluttered, but adding extra information sometimes helps to avoid confusion, while the second one looks cleaner and more organized. Please, let me know what you think.
