### ISSUE TITLE
Save application version to the database

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1467]
Save the application version (e.g. 0.23.0) to the bolt db in a meta bucket.

We can use this later to handle things like db migrations, or skip database verification on start (the missing signatures issue was a problem with a specific version and verification slows down startup).

**Comment by gz-c** [comment]
Keep in mind this must consider what happens if a user runs an older version against a newer database.  In general, it is not safe.

**Comment by gz-c** [comment]
I've implemented a prototype of this and I'm not sure it's worth the added code.

Hypothetically it can be used to skip DB verification most of the time, but running an older version on a newer DB will always trigger the possibility of corruption.

The general implementation is that,

On startup, the DB is checked for a saved app version.

Then, if:

* -verify-db is true, or
* no version was in the database, or
* the version in the database is older than the current version, or
* the database is marked as dirty

Then a database verification is triggered.

If -reset-corrupt-db is set, then the DB will be reset if verification fails, and the application will continue.  Otherwise, the application will exit on verification error.

Finally, the application version will be saved to the database if:

* There was no version already saved in the database, or
* The current version is higher than the version saved in the database

If the current version is *lower* than the version saved in the database (i.e., running an older version), then a "dirty" flag is set in the database (which will cause a reverification every time the app in run until the dirty flag is unset).

The dirty flag is unset at the end, and only if the current application version is greater than or equal to the version that was initially saved in the database.


However, versions 23 and earlier will not perform any of this.  If they did, they would mark the database as "dirty" when they are run on a database that has a version 24 or higher.
Therefore, if any of these versions are run after running a newer version, then when the newer version is run again, it would skip verification.  Therefore we would need to force -verify-db, at least until we can assume that nobody is switching to some older version after running a newer version (which mostly affects devs).  This assumption might be ok to make, and we could leave -verify-db on for a few releases then turn it off and let the db version check take over.

**Comment by iketheadore** [comment]
We need to add this to speed up node startup, as it now takes about 9 seconds in database verification, and will continue to increase as the block grows.
