### ISSUE TITLE
wallet outputs page design

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#1480]
I think the outputs page can take some design improvements
For starters, make it less stretched out just like other pages shown below, more rounded borders and same greyish white color as in the History page

just a nice to have, nothing major
Outputs page:
<img width="1677" alt="screen shot 2018-05-12 at 1 32 32 am" src="https://user-images.githubusercontent.com/8619106/39944561-c1dd863e-5584-11e8-8836-2093421c9e70.png">

History page: 
<img width="1679" alt="screen shot 2018-05-12 at 1 40 28 am" src="https://user-images.githubusercontent.com/8619106/39944764-7a0c579e-5585-11e8-9f23-188cc1f376af.png">

Send page:
![screen shot 2018-05-12 at 1 40 05 am](https://user-images.githubusercontent.com/8619106/39944770-7d27c2c4-5585-11e8-9d67-3746fb5ae82d.png)

**Comment by Senyoret1** [comment]
In fact, not only the outputs page needs improvement, but all the pages that can be accessed from the buttons in the upper right corner. Just a day ago the outputs page was changed in the web wallet (https://github.com/skycoin/skycoin-web/pull/107) and the result was this:

![outputs](https://user-images.githubusercontent.com/34079003/39952716-2535aa50-556b-11e8-98f5-38395b9bc87b.png)

That change could serve as a base, although the desktop wallet has much more information and needs something more complex.

**Comment by mahansky** [comment]
Sure thing, first step was to get rid of datatables, second step is to make it all look the same.

I feel like showing page name under navbar just takes a lot of space and attention. Currently, it's hidden at the very top of the wallet.

Other than that, the outputs table looks okay, I think I could try to merge some ideas from #1466 and this to show the outputs.
