### ISSUE TITLE
coin template creator tool

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#1485]
This is a part of https://github.com/skycoin/skycoin/issues/1474

The goal is to create a copy of https://github.com/skycoin/skycoin/tree/develop/cmd/skycoin/skycoin.go automatically with provided inputs

The values to be changed are(add more if any):
- `GenesisAddressStr`
- `BlockchainPubkeyStr`
- `GenesisCoinVolume`
- `GenesisTimestamp` (exact timestamp value is not important)
- `DataDirectory`
- `GenesisSignatureStr`
- `DefaultConnections` 

And the uxid here
https://github.com/skycoin/skycoin/blob/e915716d4decb8aa163898b93a841232159d414c/cmd/skycoin/skycoin.go#L776

But its not really necessary as the coin distribution will be handled by the tool https://github.com/skycoin/skycoin/issues/1468

---

- Create a `template` folder in the repo root and create a file `coin.template` inside it
- Copy over the contents of https://github.com/skycoin/skycoin/tree/develop/cmd/skycoin/skycoin.go
   into `coin.template` and put placeholders like `GenesisSignatureStr = "<GENESISSIGNATURESTR>"` etc
- Create a cli tool which will read a configuration file using https://github.com/skycoin/skycoin/issues/1484 and replace the placeholders in `coin.template` and create a new file `cmd/<coin>/<coin>.go` with the content of `coin.template`

**Comment by gz-c** [comment]
Use https://golang.org/pkg/text/template/
