### ISSUE TITLE
Displaying Skywire miners number and distribution map

### ISSUE THREAD

**Issue by BoyangZhu** [skycoin/skycoin#1487]
It’d be great to have the number of official miners that have shipped so far listed on the Skycoin/Skywire website.
And after the testnet launch it also could be nice to add the number of DIY miners connected, to show how vibrant the community and user base is, and have these numbers updating in real-time.
Someone else also suggested that the skywire nodes google map could be on the website, showing how global the network is.
These info are available in telegram Channels and on reddit. But for most people their first stop is usually the skycoin website. If these info are packaged and presented nicely front and forward they will be very effective at telling people the story of Skycoin/Skywire.

**Comment by gz-c** [comment]
@BoyangZhu sorry, not this repo, on https://github.com/skycoin/skycoin.net, which is the website repo
