### ISSUE TITLE
Tell the users that the history page shows amounts in USD at the current rate

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1494]
The history page in the wallet shows the amount of coins that have been sent or received, as well as their value in USD, calculated according to the current exchange rate. It would be good to tell the user this last fact, that the value in USD is calculated according to the current exchange rate, not the exchange rate at the moment when the transaction was made, to avoid confusion.

This change should be made after https://github.com/skycoin/skycoin/pull/1408

**Comment by mahansky** [comment]
What about something simple like this?

![screen shot 2018-05-15 at 14 18 41](https://user-images.githubusercontent.com/1536298/40056239-01b2cf58-584b-11e8-87ce-6e71def2b1ec.png)

**Comment by Senyoret1** [comment]
If that message appears when placing the mouse on top, I think it's fine, especially considering the asterisk. Now, English is not my strong point, so I may be wrong, but I'm not sure if "Price" is the right word for the UI, because it gives the idea of "spending" both for incoming and outgoing transactions. Maybe it could just say "Calculated at the current rate".

**Comment by gz-c** [comment]
"Calculated at the current rate" is fine
