### ISSUE TITLE
API endpoints to create unsigned transaction and sign unsigned transaction from wallet

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1513]
The endpoint to create an unsigned transaction will be like `POST /wallet/transaction`, except that it will not sign the transaction (so the password will not be required).

The endpoint to sign and unsigned transaction will accept a rawtx and wallet data necessary to sign the transaction with.

This will allow us to implement electrum's send page style, which has "Preview" and "Send" buttons. While "Send" directly sends (after entering password), "Preview" offers the option to "Sign" the previewed transaction, which then displays a signed, encoded transaction that the user can take and broadcast from elsewhere. After "Sign", the user also has the option to "Broadcast".

**Comment by gz-c** [comment]
Useful for web and mobile wallets and exchange integrations

**Comment by gz-c** [comment]
We'll also extend the signing to be able to specify specific inputs to sign, which is necessary to support coinjoin

**Comment by olemis** [comment]
@stdevStark should be submitting something in  the next few days
