### ISSUE TITLE
Design two-stages upgrade to fix the mix port issue

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#1517]
Steps to fix mix port issue:

- [ ] v24:Remove message size check so that we can accept message with extra fields. If genesis hash is present in message, parse it and reject if not matching. Requires #1576

- [ ] v25: Add genesis hash in INTR message,  disconnect the connection if receiving INTR message with different genesis hash. Accept the INTR message without genesis hash. 

- [ ] v26: Disconnect if receiving INTR message without genesis hash; disconnect if the genesis hash in INTR message doesn’t match.

Then
<=v23:  can connect to <=v24 [will reject incoming >=v25 because of extra field]
v24: can connect to <=v25 [would accept >=v26, but >=v26 will disconnect because of missing field]
v25: can connect to v24, v25 [would accept <=v23, but <=v23 will disconnect because of extra field]
v26: can connect to >=v25 [will reject <=v24 because of missing field]

**Comment by gz-c** [comment]
@iketheadore is the first one done?

**Comment by iketheadore** [comment]
Yes, the first one is done, except the genesis hash checking as we can't parse out the genesis hash without adding new fields to INTR message, while the `encoder` doesn't support `omitempty` tag, adding new field would close the connections v24 to <=23.

**Comment by gz-c** [comment]
#1576 for omitempty struct tag
