### ISSUE TITLE
 go get github.com/skycoin/skycoin/... undefined: "math/rand".Shuffle

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skycoin#1550]
When trying to install skywire on a freshy created archlinux system
(after installing go & setting up gopath)

```
[cloud@sky ~]$ go get github.com/skycoin/skycoin/...
# github.com/skycoin/skycoin/src/daemon/pex
go/src/github.com/skycoin/skycoin/src/daemon/pex/pex.go:395:2: undefined: "math/rand".Shuffle
```

This has never happened before in the dozens of times I've done this... any suggestions or hints?

**Comment by iketheadore** [comment]
The `Shuffle` function in `math/rand` is not supported before go1.10, so maybe upgrade go to g1.10 might be able to fix the proble.

Also skywire uses `github.com/skycoin/skycoin` from it's vendor, you don't have to install `skycoin/skycoin` to run it.
