### ISSUE TITLE
Error in skycoin when creating and deleting a wallet with a specific seed and then creating with the same seed.

### ISSUE THREAD

**Issue by stdevEclipse** [skycoin/skycoin#1554]
Creating a wallet with a given specific seed, then deleting and unloading the wallet should allow creating a new wallet with the same seed.
There is a test in libc that is failing because of this. The test passes the first time but fails when executing again. First test is made with static library and second test with shared library. The node is not restarted between the two executions.

**Comment by iketheadore** [comment]
the `/wallet/unload` only unloads the wallet from in-memory wallet service, it doesn't delete wallet file.

**Comment by stdevEclipse** [comment]
Hi. You are right. But if unloading and deleting it should be allowed to create another wallet with the same seed. 
There is a test failing because of this.

**Comment by stdevEclipse** [comment]
Maybe this is not an error, maybe it is the test what has to be eliminated.

**Comment by gz-c** [comment]
The documentation for unload should be updated instead.  Unload then reload is not an intended use case.

**Comment by stdevEclipse** [comment]
@gz-c , the test case is: create with specific seed, then unload and delete. but the test is ran twice for the same server instance, and it fails the second time, because the server still has a reference to the first address of the deleted wallet.
@olemis, yes, that's something we can do. however the server is not supposed to be restarted.

**Comment by iketheadore** [comment]
@stdevEclipse, we can manually delete the wallet file, then call unload to remove from in-memory service.

**Comment by olemis** [comment]
If I understood correctly the thing is that the API endpoint leaves some dangling references to wallet (items) in-memory, which then clash once new wallet is created with similar parameters .

**Comment by olemis** [comment]
@stdevEclipse patch submitted in #1562 is not passing travis checks

**Comment by gz-c** [comment]
The API intentionally leaves dangling references in memory to avoid overwriting the wallet file that it knows is written on the disk. This endpoint is STRICTLY for assistance in testing and it behaves exactly how it should.
