### ISSUE TITLE
Consider removing src/util/logging from package coin dependencies

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1555]
The src/util/logging dependency in package coin causes logrus and its dependencies to be pulled in when using this package.

This interferes with gopherjs (https://github.com/skycoin/skycoin-lite/issues/9) and possibly other transpilation such as libskycoin.

Ideally, package coin has its dependencies minimized, this was always a goal of this package.

There are two kinds of logging statements in package coin:

* Panics
* Coin and coinhour math overflow warnings

The panics can be replace with `log.Panic` with no issue.

The overflow warnings are good to have, but possibly they could be moved to the caller.  If the returned errors are verbose enough, the caller can log the error when it occurs and it will have the same effect of notifying the operator of the warning.

**Comment by olemis** [comment]
FWIW , no big deal in `libskycoin` , nevertheless let's take a look into this .
