### ISSUE TITLE
Add valgrind memcheck in travis build

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#1578]
This will allow for visualizing memory leaks and memory allocation details prior to merging code in `develop` branch . 

If there is a way to configure this so as to block the merge in github , this might be useful (<= @gz-c needs to approve first though).

**Comment by olemis** [comment]
@stdevGeekmidget => https://github.com/richelbilderbeek/cpp/blob/master/content/CppMemcheck.md

**Comment by olemis** [comment]
it's possible to use [DrMemory](http://www.drmemory.org/) as well , if considered somehow better .

**Comment by gz-c** [comment]
@olemis since libskycoin was moved out, can this be closed here?
