### ISSUE TITLE
Skycoin failed to start due to pex.go error on develop branch

### ISSUE THREAD

**Issue by stdevOzkar** [skycoin/skycoin#1588]
Yesterday I've updated my local `develop` branch, and now I got this error:
`src/daemon/pex/pex.go:395:2: undefined: "math/rand".Shuffle`
master branch works like a charm
I execute skycoin this way:
 `make ARGS="--launch-browser=false" run`

**Comment by gz-c** [comment]
upgrade go to version 1.10
