### ISSUE TITLE
Failed to start node from docker image

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#1591]
error log:
```
[2018-05-30T08:48:22Z] PANIC [api]: Invalid addr [::]:6420
[2018-05-30T08:48:22Z] ERROR [main]: recover: &{0xc42014c140 map[_module:api] 2018-05-30 08:48:22.345054104 +0000 UTC m=+0.018335978 panic Invalid addr [::]:6420 <nil>}
stack:goroutine 1 [running]:
runtime/debug.Stack(0xc4201b70a8, 0x93bf20, 0xc42014d400)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
main.Run.func1()
	/go/src/github.com/skycoin/skycoin/cmd/skycoin/skycoin.go:576 +0x57
panic(0x93bf20, 0xc42014d400)
```

The following code would make the `host` turn into ipv6 format in docker, which would make the `wh.HostCheck` panic.

```go
func Create(host string, c Config, gateway Gatewayer) (*Server, error) {
        ...
	// If the host did not specify a port, allowing the kernel to assign one,
	// we need to get the assigned address to know the full hostname
	host = listener.Addr().String()
        ...
}
```

**Comment by gz-c** [comment]
Needs ipv6 address support?

**Comment by olemis** [comment]
@iketheadore thanks for the report . Could you please mention how are you running the container and what tag exactly are you running ?

**Comment by olemis** [comment]
I ask because you could use `--ip` to set a static IPv4 address ; but maybe there is a lot of context I am missing and this does not solve this issue .

**Comment by olemis** [comment]
Maybe the answer of [stackoverflow:29957143](https://stackoverflow.com/questions/29957143/make-docker-use-ipv4-for-port-binding) can help with working around this .

**Comment by olemis** [comment]
yet another trick you could try ...

Disable IPv6 inside the container like this 

```
# echo "net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
" >> /etc/sysctl.conf 

# sysctl -p
```

this might work too

**Comment by olemis** [comment]
@iketheadore what's the status of this issue ? Fixed ?

**Comment by iketheadore** [comment]
Yes, this has been fixed by adding ipv6 address support in [5a198ac6](https://github.com/skycoin/skycoin/commit/5a198ac632a76f74374f8a3fc7b64c73fe50b1e0)

**Comment by olemis** [comment]
@iketheadore 👍

**Comment by gz-c** [comment]
@iketheadore can the API can be communicated with too? i was thinking the host check would still fail
