### ISSUE TITLE
[docker] Docker dev image with Python tools pre-installed

### ISSUE THREAD

**Issue by stdevEclipse** [skycoin/skycoin#1599]
I have install the following software in latest docker image:
- Python Dev Package (2.7)
- Pip
- Tox.

It would be great to have these programs in future versions.

**Comment by olemis** [comment]
This should be done in a separate Docker Hub repository ( e.g. `skycoin/skycoindev-python` ) or tag ( e.g. `skycoin/skycoindev-cli:py3` ) .

**Comment by olemis** [comment]
Built in simelo/pyskycoin#12 , simelo/pyskycoin#21 .

**Comment by olemis** [comment]
For the moment the image is at https://hub.docker.com/r/simelotech/skycoindev-python/
