### ISSUE TITLE
[hexdumps] [encoder] Add support for omitempty tag to messages hexdumps generator

### ISSUE THREAD

**Issue by stdevEdu** [skycoin/skycoin#1603]
Current messages hexdump iterator doesn't support omitempty flag feature, introduced in issue #1576 and employed at PR #1595.

**Comment by stdevEdu** [comment]
Please, @olemis, assign me this issue.

**Comment by gz-c** [comment]
Skip the field marked `omitempty` for the purpose of the hexdump

**Comment by stdevEdu** [comment]
@gz-c, performed changes, so that all omitempty flagged fields are omitted.
