### ISSUE TITLE
Type annotations for hexdumps with configurable depth

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#1610]
Annotations implemented in #1241 are emitted for the direct descendants of the top-level value type. Therefore , if e.g. a struct contains another struct field then the later will be represented as an opaque byte array . Same holds for other complex types .

This issue should provide another version of the iterator emitting annotations for values of all fields in the type hierarchy up to a (configurable) depth.

**Comment by gz-c** [comment]
@olemis is this done or irrelevant? can i close it?
