### ISSUE TITLE
Skycoin client can't connect to the network behind an HTTP proxy.

### ISSUE THREAD

**Issue by lamg** [skycoin/skycoin#1662]
Which interfaces should be modified in order to provide HTTP proxy support?

**Comment by olemis** [comment]
@lamg have you tried with setting `http_proxy` and/or `https_proxy` environment variables ?

**Comment by stdevHan** [comment]
@lamg  First you should check if your proxy, give you access to the `6000`, which is the port that most peers.

**Comment by lamg** [comment]
@stdevHan My proxy only allows access to ports `443` and `80`, which is what is expected from an HTTP proxy. @olemis both `http_proxy` and `https_proxy` are set properly.

**Comment by olemis** [comment]
@lamg you need to try [corkscrew](https://www.techrepublic.com/blog/linux-and-open-source/using-corkscrew-to-tunnel-ssh-over-http/) in your client and maybe [sslh](https://www.unixmen.com/sslh-a-sslssh-multiplexer-for-linux/) in hour server . Please contact us via either [SkycoinDev Spanish channel](https://t.me/skycoindev_es) .
