### ISSUE TITLE
verifyCreatedTransactionInvariants should check for genesis block (i.BkSeq > 0)

### ISSUE THREAD

**Issue by mihis** [skycoin/skycoin#1664]
If blockchain contains only genesis block with single transaction, Visor.CreateTransaction will return error.

It seems, that the reason is the following check inside wallet.verifyCreatedTransactionInvariants https://github.com/skycoin/skycoin/blob/08bed793896013152869cb86786d9d2c35777b8a/src/wallet/wallet.go#L1375-L1377

coin.CreateUnspetns and coin.CreateUnspent will assign SrcTransaction non-null hash, only if provided block has BkSeq > 0.

https://github.com/skycoin/skycoin/blob/08bed793896013152869cb86786d9d2c35777b8a/src/coin/block.go#L203-L208

https://github.com/skycoin/skycoin/blob/08bed793896013152869cb86786d9d2c35777b8a/src/coin/block.go#L228-L236

**Comment by gz-c** [comment]
@therealssj does this affect the fiber setup script?
