### ISSUE TITLE
[Wallet] history page is not updated

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#1673]
The history page in wallet is not updated after spending, no new items would be added even if the wallet is restarted.

**Comment by mahansky** [comment]
If you make transactions between addresses that you own, it won't be shown in the transaction history.
Is that your case?

I think it's by design to filter out those transactions so you only see the relevant ones.

**Comment by iketheadore** [comment]
@gz-c how do you think about this, the history page filters out the transactions that send coins between addresses in local wallets.

**Comment by gz-c** [comment]
I think it should show them, I can't think of a reason not to show them

**Comment by iketheadore** [comment]
yes, I do think so, @mahansky please update to show them
