### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1688]
Several of the improvements made to the UI of the web wallet should be applied to the desktop wallet. The PRs in which the improvements are:

- https://github.com/skycoin/skycoin-web/pull/326
- https://github.com/skycoin/skycoin-web/pull/391 (When removing the pipe it will be necessary to change the text on the blockchain page, something that was not done in the web wallet)
- https://github.com/skycoin/skycoin-web/pull/384
- https://github.com/skycoin/skycoin-web/pull/374
- https://github.com/skycoin/skycoin-web/pull/371
- https://github.com/skycoin/skycoin-web/pull/318 (In this case it is only necessary to use the new version of `minus-red.png`)

**Comment by mahansky** [comment]
Any particular reason to remove the DateFromNow pipe? It's used in Networking as well as Blockchain, it's much more user friendly than reading the whole date time format.

**Comment by Senyoret1** [comment]
The reason why it was deleted in the web wallet is that it was only used in the blockchain page. The problem with the pipe was that we have no info about the clock used to set the block date, so the pipe often said "in a few seconds" or something similar, as if the block had been added in the future.

Now, looking at the networking page, it certainly seems that it is best not to eliminate the pipe, because on that screen there should be no problems (the same clock is used for the calculations). Maybe it's best to just not use it on the blockchain page.
