### ISSUE TITLE
Generated files should not be versionned

### ISSUE THREAD

**Issue by mpsido** [skycoin/skycoin#1692]
the Makefile rule "make build-ui" generates files in the branch that appear in the git log.
They should be removed from git and added in .gitignore

That caused a very difficult to debug travis build failure in #1686

Indeed the script should generate the desirated files by running make build-ui instead of using the files pushed on the repo.

Example of files that should not be versioned:

src/gui/static/dist/0.b3eb73070eae33abeb00.chunk.js
src/gui/static/dist/3rdpartylicenses.txt
src/gui/static/dist/assets/i18n/en.json
src/gui/static/dist/inline.38e95b90f0dc8379ea10.bundle.js
src/gui/static/dist/main.79d81016052c4c20c8a6.bundle.js
src/gui/static/dist/styles.9c529cc9b41581189358.bundle.css

**Comment by gz-c** [comment]
this is intentional

**Comment by mpsido** [comment]
Why ? Do you mean I should push these generated files at each of my commits ?
Why not run make build-ui instead ?

**Comment by gz-c** [comment]
I will update the generated files periodically.

We do not want to require nodejs in order to run the wallet from source.  A `go get` should be enough.
