### ISSUE TITLE
The screen stays blank after starting the wallet

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1695]
Several users have had the problem. Apparently several things may affect the backend and then the problem occurs (see the sticky message in the Telegram support group). To have a good UX, it is necessary to make the UI react properly, instead of showing a white screen.

Apparently, the main problem is that the backend stops responding correctly to requests made to the api. Because of that, when trying to get the list of wallets, an uncatched error occurs and then the whole web app fails, The request is done in:

https://github.com/skycoin/skycoin/blob/0a6a127224d16a8c438d6777fdb2d307b391d26a/src/gui/static/src/app/services/wallet.service.ts#L227-L229

In fact, if the wallet is started with the backend turned off, the white screen is displayed, but if `ApiService.get` is modified so that calls to `/wallets` always returns a list of fake wallets, the web app loads. The response can be simulated with this code:

```
get(url, params = null, options = {}) {
  if (url != 'wallets') {
    return this.http.get(this.getUrl(url, params), this.returnRequestOptions(options))
      .map((res: any) => res.json())
      .catch((error: any) => Observable.throw(error || 'Server error'));
  } else {
    return Observable.of([
      {
          "meta": {
              "coin": "skycoin",
              "filename": "2017_11_25_e5fb.wlt",
              "label": "test",
              "type": "deterministic",
              "version": "0.2",
              "crypto_type": "",
              "timestamp": 1511640884,
              "encrypted": false
          },
          "entries": [
              {
                  "address": "8C5icxR9zdkYTZZTVV3cCX7QoK4EkLuK4p",
                  "public_key": "0316ff74a8004adf9c71fa99808ee34c3505ee73c5cf82aa301d17817da3ca33b1"
              },
              {
                  "address": "23A1EWMZopUFLCwtXMe2CU9xTCbi5Gth643",
                  "public_key": "02539528248a1a2c4f0b73233491103ca83b40249dac3ae9eee9a10b9f9debd9a3"
              }
          ]
      }
    ]);
  }
}
```

The result of using that code without the backend is this screen:
![result](https://user-images.githubusercontent.com/34079003/42295146-61de2f30-7fb5-11e8-80a6-f6da3ac90398.png)

Showing a screen like that would be better than just showing a white screen, but it is not entirely adequate. Returning an empty array of wallets causes the web app to navigate to the wizard, which would not be entirely appropriate either. Probably the most appropriate solution, without requiring too many changes in the code, would be  to display a full-screen error message. Something like this could work:
![msg1](https://user-images.githubusercontent.com/34079003/42295153-6abc2d6e-7fb5-11e8-97fc-a72be81277a5.png)
![msg2](https://user-images.githubusercontent.com/34079003/42295156-6ec0642a-7fb5-11e8-969a-68df04a02a57.png)

With a screen like that it would be possible to give more information to the user. It would be also posible to add a link to a page on the website with more information, which could be updated periodically.

**Comment by gz-c** [comment]
What about when index.html can't load?

This is potentially similar to another issue where we discussed displaying a "loading" screen during startup. In that, we may need to bundle some asset with the electron app itself, not loaded from the daemon, in order to to do so.  However, that case only applies to the electron app and not when run in a normal browser.

**Comment by Senyoret1** [comment]
I suppose we'll have to take into account the two cases then, because, as you say, the two situations are different. However, the design could be the same, but with a change in the title, to be able to identify more easily what went wrong.
