### ISSUE TITLE
Continuous integration for Windows

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#1697]
Upgrade Appveyor builds to the same level of Travis CI for MacOS and GNU/Linux .

**Comment by olemis** [comment]
@stdevYuniers pls remind me to assign you this issue once you accept joining Skycoin org .

**Comment by stdevYuniers** [comment]
@olemis please, assign this issue to me

**Comment by gz-c** [comment]
Can this even be done?  Some of the tests rely upon shell scripts / unix behavior

**Comment by olemis** [comment]
Yes , [stdevNorge_t1697_ci_skycoin_appveyor branch](stdevNorge_t1697_ci_skycoin_appveyor) is for this .

**Comment by stdevStark** [comment]
@olemis I'll do it .

**Comment by stdevStark** [comment]
@stdevYuniers done in 362e476 .

**Comment by gz-c** [comment]
@olemis is this still going on or can i close it? I don't think its necessary if its that much work

**Comment by olemis** [comment]
I'll take a look , and come back to you shortly
