### ISSUE TITLE
Optionally enable nodejs integration in electron

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1701]
Ledger nano integration may require us to use the nodejs integration feature of Electron in order to integrate it into the wallet.

Nodejs integration is disabled because it is otherwise a security risk.

Investigate the ability to allow the user to run Electron with nodejs integration enabled, in order to support Ledger. This could be an option in the Electron menus.  In this case, the users preference can be saved using electrons storage mechanisms. This should not involve the daemon.

**Comment by gz-c** [comment]
@Senyoret1 what did we end up doing for the nodejs integration option?

**Comment by Senyoret1** [comment]
The integration with the hardware wallet worked without needing to activate the integration with node in the Electron window that displays the Angular app. However, it was necessary to deactivate the isolation between the Electron main process and the Electron window.

The code with the integration with the hw runs in the main process of Electron, which has integration with node by default. The code at this time works more or less like this:

Angular app (inside an Electron window) <-> Electron main process <-> hardware wallet

When finishing the daemon we will be able to erase all this code and reactivate the content isolation.

**Comment by gz-c** [comment]
OK, nodejs usage scheduled for removal upon completion of github.com/skycoin/hardware-wallet-daemon
