### ISSUE TITLE
[Hardware wallet] [New Feature] Device recovery integration

### ISSUE THREAD

**Issue by mpsido** [skycoin/skycoin#1708]
Create a way to perform a wallet recovery on device from the skycoin web app.
Device recovery is a feature allowing user to write back his mnemonic in the device in a safe way

**Comment by mpsido** [comment]
1) Create a button in wallet-detail that the user can click to run a backup.
2) The button should disapear if the backup had been done already
3) The hardware wallet should have a message to tell the PC if the backup had been done so that the web wallet can check it. Or we can use trezor's GetFeatures message.
4) Should work if a PIN code had been configured

**Comment by mpsido** [comment]
The main difficulty of this issue is to find a way to have the GUI stay updated about the user interaction with the device's buttons.
Each time the user confirms one word of the seed. He should see a form of progress bar.

**Comment by Senyoret1** [comment]
Done in https://github.com/skycoin/skycoin/pull/1945
