### ISSUE TITLE
Wallet synch process bar won't display after network recovery

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#1728]
The blockchain synch process bar in wallet will disappear if all connections are lost, and won't be shown again after the network is recovered.

**Comment by Senyoret1** [comment]
Is there any way to simulate or cause the problem at will? That would help to understand better what happens and to solve the problem.

**Comment by iketheadore** [comment]
The reproduce steps might be:
1. Delete data.db and start node from terminal to synch blocks from scratch
2. After blocks have been synchronized for a while, turn Wi-Fi off, and wait till the wallet synch process number disappear and show wallet balance
3. Then turn on the Wi-Fi, and you will see the blocks synch process are recovered from terminal logs, but the wallet UI won't show the synch process anymore.

**Comment by gz-c** [comment]
Can you show the response body of the wrong response?

What happens when the internet connection resumes?

**Comment by Senyoret1** [comment]
While the internet connection is active, the API endpoint returns a response like this:
```
{
    "current": 880,
    "highest": 94470,
    "peers": [
        {
            "address": "122.114.159.104:6000",
            "height": 94470
        },
        {
            "address": "104.237.142.206:6000",
            "height": 94470
        },
        {
            "address": "63.135.12.1:6000",
            "height": 94470
        }
    ]
}
```
Just after the internet connection is disconnected the endpoint continues returning the same, but after a while the peers start to disappear and when there is none the endpoint returns something like this:
```
{
    "current": 880,
    "highest": 880,
    "peers": []
}
```
The most important thing is that `highest` is changed and has that same value of `current`, so the wallet thinks that all blocks have been obtained.

After seeing this again, I could solve the problem by simply verifying if the `peers` array is empty and/or checking if the value of `highest` is lower than the highest value previously obtained. However, I don't know if you would still want to make changes in the node, so you decide.

**Comment by gz-c** [comment]
@Senyoret1 When peers is empty, doesn't the client show a "no connections" warning instead?

**Comment by Senyoret1** [comment]
@gz-c Prior to the changes made in https://github.com/skycoin/skycoin/pull/2139, the “no connections” warning was displayed and the wallet was shown as if it was already synchronized. When having connection again, the alert disappeared and the wallet was still showing the UI as synchronized.

With the changes, now the alert is shown and the wallet continues telling the user that the node is synchronizing.
