### ISSUE TITLE
[Hardware Wallet][New Feature] Pin code integration

### ISSUE THREAD

**Issue by mpsido** [skycoin/skycoin#1765]
Integrate PIN code input in webwallet for different messages:
* address generation
* transaction signature
* backup device (related to  #1708)

**Comment by mpsido** [comment]
* PIN code integration for address generation is almost done. But an error appears in browsers logs. And the generated address appears empty in the addresses list.
Need to refresh the page. Once the page is refreshed the problem do not appear because the device memorizes the PIN code in cache (address generation is not considered as a sensitive operation)

**Comment by mpsido** [comment]
* PIN code integration during wallet creation (one of the steps requires to generate addresses) is not relevant because we can wipe the device before address generation.

**Comment by mpsido** [comment]
The PIN code integration's main difficulty is we have a new "in between" PIN code request message received by the GUI during address generation or transaction signature.
The promises/observers that are waiting for address or signed transaction do not expect a 'PIN code needed' error in the current code

**Comment by mpsido** [comment]
for transaction signature, the user need to enter pin code for each address that is signing the transaction.... !
there is not one but many back and forth messages between the GUI and the daemon.

Need to find a proper way to construct a simple to use callback for this need.

will get worse if using many connected device wallet to sign the transactions

**Comment by mpsido** [comment]
Example of transaction:
![transaction](https://user-images.githubusercontent.com/18638060/44010338-5bc5a22e-9ee4-11e8-8a8b-08d2bbb16443.jpg)

And the back and forth processing required to process it:
![pin_code_for_transaction_uml](https://user-images.githubusercontent.com/18638060/44010337-5b439eaa-9ee4-11e8-8985-67c5ee140aae.jpg)

**Comment by mpsido** [comment]
wallets.go is a wrapper around a map: 
type Wallets map[string]*Wallet

It contains all the wallets created in webwallet's heap memory.

it can be accessed from service.go (example in the function NewAddresses), but that is reserved to the requests that actually modify a wallet.
In service.go there is a minimal number of imported packages

There rest of the requests are processed in visor.go.
this package it is in relation with the "databases" that keep track of skycoin blockchain.

The CreateTransaction function is in relation with the blockchain it shall not be moved out of there.

However we created a situation where the "wallet" needs to keep a short term memory of the ongoing requests that were not answered because PIN code is missing.
The transaction preparation is interrupted because of this and we need to find a proper to start back again right were it was stopped.

The initial idea of creating and storing a "Closure callback" and store it inside the wallet fails, because the wallet pointer we have in CreateTransaction is a "cloned wallet" (service.go 334).

**Comment by mpsido** [comment]
We can create a new package "hardware-wallet-service.go" that can act like a state machine for hardware wallets and can be called either from visor.go or straight from gateway.go
![hwwalletservice](https://user-images.githubusercontent.com/18638060/44200467-35c4ba00-a179-11e8-85ae-f677dea8351e.jpg)

**Comment by gz-c** [comment]
None of this belongs in go, it belongs in the frontend, so that it can work with the web wallet.  The only go code is for interacting with the device from the command line

**Comment by mpsido** [comment]
I am not so sure... 
The daemon has to be coded to "create" and "sign" transaction like it does in the current version in develop branch.
The difference here is that I have a device wallet that inserts more steps in the signature processing

**Comment by Senyoret1** [comment]
The front-end already has the PIN code integration working well.

**Comment by stdevStark** [comment]
@Senyoret1 can this be closed then ?
