### ISSUE TITLE
[Hardware Wallet][New Feature] Wipe the device from the web wallet

### ISSUE THREAD

**Issue by mpsido** [skycoin/skycoin#1769]
We should create a button in wallet details to wipe the device.
Warning the GUI may need to be reshaped because we are having a lot of new buttons.
see #1768 #1708 

During wallet creation we may want to have a check box to ask the user if he wants to wipe the connected wallet.

**Comment by Senyoret1** [comment]
Done in https://github.com/skycoin/skycoin/pull/1945
