### ISSUE TITLE
Slow API query for address through explorer

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1786]
Address query through explorer is slow due to large transactions in its transaction set:

https://explorer.skycoin.net/app/address/2K26ippbPRonfBAPFfZrD4bP88xVgghx38C/1

Need to diagnose the performance, and determine possible optimizations.  Has an impact on the explorer as well, but the underlying APIs are defined here.

**Comment by gz-c** [comment]
Relates to #2090

**Comment by iketheadore** [comment]
Fixed
