### ISSUE TITLE
Remember the data filled in Send page of wallet temporarily

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#1798]
The data filled in Send page in wallet will all gone when you come back after clicking other pages, like if I want to check address in Wallets page. This is annoying especially when do advanced spending. So remember the data filled temporarily should be more friendly.

**Comment by gz-c** [comment]
In which case do you find you need to check the wallets page for an address?

If the data is retained on the Send page, then there is no mechanism to clear to the page

**Comment by gz-c** [comment]
I have had the same issue before, I was thinking we could have a UI to select change address from the wallets, but it would also need to allow user to enter a custom change address
