### ISSUE TITLE
Docker images not prepared for running Web GUI

### ISSUE THREAD

**Issue by BigOokie** [skycoin/skycoin#1836]
Recently setup a Skycoin node running in Docker as per instructions provided on GitHub. Have been unable to connect to the Skycoin Node WebGUI. 

@olemis looked at this and noticed the Docker images were not prepared for running the Web GUI and requested I raise an issue for this.

**Comment by olemis** [comment]
The possibility of running the web wallet inside a container should be delivered in a separate image since that requires adding a browser and interaction with a windows sever.

**Comment by gz-c** [comment]
Don't put a browser in the dockerfile just expose the web GUI interface to the host system

**Comment by gz-c** [comment]
@olemis was this solved?
