### ISSUE TITLE
Coin Hours in pending transactions

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1866]
I'm not sure if it's an error or if it works correctly, but when calling the `/pendingTxs` endpoint with `verbose=1` the inputs do not have in `calculated_hours` the number of hours that the input had when the transaction was created, but the current amount. This means that if a transaction is pending for a long time, it is possible to see how the number of hours increases over time.

**Comment by gz-c** [comment]
The `calculated_hours` for unconfirmed transactions is calculated based upon the current time, to show approximately how many coin hours it would have if it were to be confirmed right now

**Comment by gz-c** [comment]
Added some documentation here: https://github.com/skycoin/skycoin/pull/1867
