### ISSUE TITLE
LoadWallets return error if duplicate wallet file is found

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1892]
When loading wallets, if two wallet files are duplicates (i.e. they have the same initial address), return an error.

After testing this, report if the desktop client reports an error to the user or not.

**Comment by J0nathan-S** [comment]
When loading duplicate wallet files and an error is thrown in that stage, it seems like the electron process isn't ending (Window constantly shows the loading screen), but I guess the Go-Process is, as seen in the attached logfile. 

There should definitely be a better error handling. 

[2018-09-19-102415-v0.24.1.log](https://github.com/skycoin/skycoin/files/2396127/2018-09-19-102415-v0.24.1.log)
