### ISSUE TITLE
[docker] Improve repo-info and docs for Docker dev images

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#1896]
- ~[dind image source](https://github.com/skycoin/skycoin/tree/develop/docker/images/dev-docker) is missing repo-info~
- [ ] All images are missing labels (see [wikiwi/docker-build image metadata](https://microbadger.com/images/wikiwi/docker-build) for a list of labels)
  *  org.label-schema.name
  *  org.label-schema.vcs-url
  *  org.label-schema.vendor
  *  the rest of [org.label-schema](http://label-schema.org/rc1/) labels.
- ~Check and automate `repo-info` generation for images generated from (at least) `master` branch~
- [ ] Mention [dind image](https://github.com/skycoin/skycoin/tree/develop/docker/images/dev-docker) in [development Docker images section](https://github.com/skycoin/skycoin/blob/develop/README.md#development-image) .
- [ ] Review docs about Docker images for completeness.

**Comment by stdevPavelmc** [comment]
Funny, the sub-issue check boxes on this issue don't let me check them (to show the status of completeness)... the unicorn is playing games with me.

1 & 4 are done, the others are in process.

**Comment by stdevPavelmc** [comment]
Never mind,

The ["org.label-schema.name" can omit the label if needed](http://label-schema.org/rc1/ ), in fact it's more a human friendly name, like bionic for Ubuntu.

I will use the last part of the image name in this case for the name, with the label: 'skycoindev-cli:dind' and add a description.

**Comment by olemis** [comment]
@stdevPavelmc see simelo/skycoin-repo-info#1 and simelo/skycoin-repo-info#2 for further details .

**Comment by olemis** [comment]
@stdevPavelmc you are right . Let's reopen this issue.
