### ISSUE TITLE
ALL option missing in -enable-api-sets

### ISSUE THREAD

**Issue by nutmix** [skycoin/skycoin#1926]
According to the help and docs, enable-api-sets should support "ALL":

`flag.StringVar(&c.EnabledAPISets, "enable-api-sets", c.EnabledAPISets, "enable API set. Options are **ALL**, READ, STATUS, WALLET, WALLET_SEED, DEPRECATED_WALLET_SPEND. Multiple values should be separated by comma")`

However, doing this:

`skycoin -enable-api-sets="ALL"`

results in:

`Invalid value in -enable-api-sets: "ALL"`

Reading the REST documentation, ALL and WALLET_SEED are not supported, so we need to updated the command line help.

**Comment by olemis** [comment]
@nutmix new changes are aimed at avoiding similar confusions in the future . `ALL` API set was removed but the name remained in the user docs. All supported API sets may be via enabled by providing `-enable-all-api-sets` cli argument.
