### ISSUE TITLE
Send disconnect packet before disconnecting from peer

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1957]
When disconnecting from a peer, send a packet which indicates the disconnect reason.

It should be safe to send this new packet since we are disconnecting anyway.  The remote peer will disconnect when it receives an unknown packet.

**Comment by olemis** [comment]
Related to #735 . Indeed , this would consist in sending `RJCT` message back to peers before disconnecting under reasons other than `INTR` mismatch .
