### ISSUE TITLE
api request: could the /api/v1/explorer/address accept multiple comma separated address-arguments?

### ISSUE THREAD

**Issue by Skvuddudutt** [skycoin/skycoin#1962]
As described here: https://github.com/skycoin/skycoin/blob/develop/src/api/README.md#get-address-affected-transactions

The mobile wallets uses this api to fetch tx-history for a wallet. This potentially requires many calls since it only accepts a single address as argument. In the future with coinjoin and maybe enforcement of no address-reuse this could potentially be totally non-viable with 100s of addresses.

Could this api be modified to allow specifying a list of addresses? Much like the current /api/v1/transactions endpoint (which is not useable for this purpose since it does not return the owning address of the inputs, even if Verbose is specified).

Edit: it makes more sense to adjust /api/v1/transactions to return input-owner, since the documentation says it is supposed to.

**Comment by gz-c** [comment]
Verbose `/api/v1/transactions` returns the input owner address, doesn't it?

**Comment by Skvuddudutt** [comment]
I havent been able to make it. Maybe I'm just dense but I've tried with verbose, verbose=1, verbose=true, etc and nothing worked.

**Comment by Skvuddudutt** [comment]
se for example here: https://node.skycoin.net/api/v1/transactions?addrs=7cpQ7t3PZZXvjTst8G7Uvs7XH4LeM8fBPD,6dkVxyKFbFKg9Vdg6HPg1UANLByYRqkrdY&verbose=true

anything I try only returns the inputs hashes
