### ISSUE TITLE
show seed only works for default wallet

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#1974]
show seed has no user input for wallet name and only works for default wallet
https://github.com/skycoin/skycoin/blob/491b6d50d1e9fa1660c38e5fc3ff3f4c92c7603f/src/cli/show_seed.go#L35-L44

**Comment by gz-c** [comment]
isn't is configured through `WALLET_NAME` env var?

**Comment by therealssj** [comment]
ah right. missed that in `LoadConfig`
