### ISSUE TITLE
Api endpoint to check the coinhour burn rate

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1980]
Because https://github.com/skycoin/skycoin/issues/1461 was moved to v0.26, It would be good to have an api endpoint to consult what the coinhour burn rate is, if it is modified in v0.25. This might be necessary for the web wallet to work well with other Fiber coins, since it would be easy to modify it to use the new coinhour burn rate of Skycoin if the node is running v0.25, but other coins could have a different coinhour burn rate, which would result in errors.

**Comment by gz-c** [comment]
This can go into the `/health` endpoint

**Comment by olemis** [comment]
IMO this belongs in blockchain metadata endpoint .

**Comment by gz-c** [comment]
blockchain metadata is included in the /health endpoint, so that's fine

**Comment by olemis** [comment]
Well , as far as I can see @stdevStark added it in health endpoint directly. Should we change that ?

**Comment by gz-c** [comment]
It's fine where it is
