### ISSUE TITLE
Translate the wallet

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#1981]
It will be necessary to add the option to change the language and test if it works correctly in all screens. Probably the option should not be active by default, until analyzing well its maintainability.

**Comment by therealssj** [comment]
there is definitely a maintainability issue here since we need to make sure we have people to translate the text if we make changes.
We could probably add chinese as an option for now imo since we have people in office that can be tasked to translate it easily.

**Comment by olemis** [comment]
@therealssj Transifex

**Comment by therealssj** [comment]
woah should have known that there is already an existing marketplace for this!

**Comment by olemis** [comment]
not the only one ... we could add Spanish / French / Portuguese translators .

**Comment by therealssj** [comment]
https://github.com/skycoin/skycoin/blob/develop/src/gui/static/src/assets/i18n/en.json
We already have a list of strings to translate

**Comment by Senyoret1** [comment]
There is even a Spanish version on the web wallet: https://github.com/skycoin/skycoin-web/blob/develop/src/assets/i18n/es.json , but the strings are not exactly the same in both wallets. In fact, the translation options are already working on the web wallet

**Comment by therealssj** [comment]
should swap out the strings in web wallet for the ones in desktop wallet given that its directly possible
