### ISSUE TITLE
Add SonarCloud integration on Travis CI

### ISSUE THREAD

**Issue by stdevYuniers** [skycoin/skycoin#2009]
SonarCloud is a cloud service offered by SonarSource and based on SonarQube that could bring a higher code quality to Skycoin.

Sonar is an automatic code review tool to detect bugs, vulnerabilities and code smells in our code. Many organizations and people use it.

It would be a nice step to enhance our code quality.

More info at:

- https://www.sonarqube.org/
- https://sonarcloud.io/about
- https://www.sonarqube.org/features/clean-code/
- https://www.sonarqube.org/features/issues-tracking/
- https://www.sonarqube.org/features/multi-languages/
- https://www.sonarqube.org/features/centralization/

**Comment by gz-c** [comment]
I think they just run the linters we do, except we'd have less control

**Comment by stdevYuniers** [comment]
@gz-c Use go linters is the best analysis tool for go lang.
I'm only suggest SonarCloud integration because we use more than one programing language, [TypeScript and SASS are too used](https://github.com/skycoin/skycoin/tree/develop/src/gui/static/src).

I have used Sonar for a long time and recommend use it.
