### ISSUE TITLE
Error in Go installation instructions

### ISSUE THREAD

**Issue by kf106** [skycoin/skycoin#2024]
curl -sSL https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer > gvm-installer && chmod a+x gvm-installer && source $HOME/.gvm/scripts/gvm

This instruction appears to be missing a `source gvn-installer` instruction. As it stands, on systems without gvm it returns `bash: gvm: No such file or directory`.

**Comment by gz-c** [comment]
@iketheadore can we get rid of gvm instructions? its not needed
