### ISSUE TITLE
Error in Skycoin make instructions

### ISSUE THREAD

**Issue by kf106** [skycoin/skycoin#2025]
The instructions, if followed verbatum, fail at this point:

## Run Skycoin from the command line
    cd $GOPATH/src/github.com/skycoin/skycoin
    make run

with the message:

    make: Nothing to be done for 'run'.

**Comment by therealssj** [comment]
yeah its `run-client`
I have updated the readme in (this)[https://github.com/skycoin/skycoin/pull/2018/files] PR already

**Comment by gz-c** [comment]
fixed by #2018
