### ISSUE TITLE
Document cli options for running public node

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2033]

**Comment by BigOokie** [comment]
Do you have specifics for what’s needed here? I might be able to put some time into this for you - depending on what’s needed.

**Comment by gz-c** [comment]
A section in the README which shows which cli options to use for a node with a public HTTP interface

**Comment by gz-c** [comment]
https://github.com/skycoin/skycoin/tree/develop/cmd/skycoin#run-a-public-api-node
