### ISSUE TITLE
Release Skycoin 0.25.0

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#2041]
- [x] Sync `master` and `develop` branches
- [x] Compile wallet
- [x] Update all version strings in the repo (grep for them) to the new version
- [x] Run `make check-coin`
- [x] Update `src/skycoin/skycoin.go`'s `dbVerifyCheckpointVersion` value (if needed)
- [x] Update `CHANGELOG.md`
- [x] Migrate https://github.com/simelo/skycoin-repo-info => https://github.com/skycoin/repo-info
- [x] Update repo-info location in README release notes
  * Repo info metadata moved onto a separate repository . Needs update in main README .
- [x] Merge into `develop` ( @gz-c we'll need your help with #2044 )
- [x] Pre-release testing ( WiP )
- [x] PR from `develop` to `master` ( @gz-c => #2051 )
- [x] Review release PR
- [x] Tag `master` with `v0.25.0` and sign it
- [x] Check that client runs properly from the `master` branch
- [x] Upload  release files (Travis or manually ?)

**Comment by olemis** [comment]
Location =  https://github.com/skycoin/repo-info

**Comment by gz-c** [comment]
https://github.com/skycoin/repo-info is available now

**Comment by olemis** [comment]
Issues found during pre-release testing: #2047 , #2045

**Comment by olemis** [comment]
done

**Comment by E-Dickerson** [comment]
Signatures for 0.25.0 binaries appear to have the correct filenames, but are listed under the wrong categories. Electron GUI under daemon, Standalone under CLI, CLI under electron, and Daemon under standalone.
