### ISSUE TITLE
The timestamp on Pending transactions panel shows incorrectly

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#2054]
The timestamp shows on Pending transactions panel is incorrect, it's different from explorer.skycoin.net, and different on windows and osx.

The timestamp on explorer is:
![image](https://user-images.githubusercontent.com/2589926/50388235-42c76a80-0764-11e9-9137-7f36ef8c4b02.png)

Timestamp on osx is:
![image](https://user-images.githubusercontent.com/2589926/50388255-9d60c680-0764-11e9-8469-2cdb85b36b9d.png)

Timestamp on windows is:
![image](https://user-images.githubusercontent.com/2589926/50388249-799d8080-0764-11e9-9880-c44c309ff1a0.png)

**Comment by gz-c** [comment]
The timestamp for pending transactions indicates the time the transaction was added to the unconfirmed pool, so it will be different in each node.
