### ISSUE TITLE
Add the commit hash and branch name to the docker compiled binaries

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2071]
The commit hash and branch name are missing from the binaries used in docker, e.g.

https://staging.node.skycoin.net/api/v1/health

This should be the `develop` branch. staging.node.skycoin.net runs from the docker develop image.

**Comment by stdevStark** [comment]
@olemis this is in the logs . Is this correct ?

```
Step 12/31 : RUN cd $GOPATH/src/github.com/skycoin/skycoin && echo "Building with GOLDFLAGS=$GOLDFLAGS GOARCH=$GOARCH GOARM=$GOARM CGO_ENABLED=$CGO_ENABLED GOOS=$GOOS " && go install -ldflags "${GOLDFLAGS}" ./cmd/... && sh -c "if test -d $GOPATH/bin/linux_arm ; then mv $GOPATH/bin/linux_arm/* $GOPATH/bin/; fi; if test -d $GOPATH/bin/linux_arm64 ; then mv $GOPATH/bin/linux_arm64/* $GOPATH/bin/; fi"
---> Running in 01794a831af7
Building with GOLDFLAGS=-X main.Commit=b25ecf74d1372e68ae40ad7ea49f6b37422e9a54 -X main.Branch=stdevStark_t2071_skycoin_docker_buildinfo GOARCH=arm GOARM=7 CGO_ENABLED=0 GOOS=linux
Removing intermediate container 01794a831af7
---> d016161df088
```

**Comment by olemis** [comment]
that looks good ... nonetheless [`dev-cli` build check](https://cloud.docker.com/redirect/?resource_uri=/api/audit/v1/action/9b2f94fa-495c-427f-b48e-8bcc3e457866/) is failing .

**Comment by olemis** [comment]
did you create a PR for this ?

**Comment by stdevStark** [comment]
yes #2076

**Comment by olemis** [comment]
it's been merged already , please create a new PR from same branch .

**Comment by stdevStark** [comment]
@olemis see #2100
