### ISSUE TITLE
Update metadata for Docker images

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#2073]
The tags listed in Docker image README are not up to date . Maybe better to keep data consistency by adding link to corresponding skycoin/repo-info metadata ?

**Comment by stdevStark** [comment]
I do not understand this . Can you please explain ?

**Comment by olemis** [comment]
@stdevStark see https://github.com/skycoin/repo-info

**Comment by olemis** [comment]
fixed by #2076
