### ISSUE TITLE
Windows desktop electron client sometimes shows "Error#1" on start

### ISSUE THREAD

**Issue by 200495** [skycoin/skycoin#2083]
When wallet update from 0.24.1 to 0.25.0 ,it become that.

**Comment by 200495** [comment]
![image](https://user-images.githubusercontent.com/23026128/50816417-7c4ec700-135b-11e9-9494-d608cbc005af.png)

**Comment by 200495** [comment]
Windows

**Comment by gz-c** [comment]
After quit wallet, wait a minute, then start new wallet

**Comment by 200495** [comment]
I have done it,but it still have problem.

**Comment by 200495** [comment]
After restart computer ,it become to normal.

**Comment by 200495** [comment]
> After quit wallet, wait a minute, then start new wallet
I have done it,but it still have problem.
I wait for 20 minutes,restart it and it still have problem.
After restart computer ,it become to normal.
It lack of user experience.

**Comment by 200495** [comment]
> After quit wallet, wait a minute, then start new wallet

I have done it,but it still have problem.
I wait for 20 minutes,restart it and it still have problem.
After restart computer ,it become to normal.
It lack of user experience.
