### ISSUE TITLE
Allow to add amounts in USD when creating transactions

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#2105]
In some cases, when sending coins it would be more convenient to enter the amounts in USD and have the system automatically perform the conversion to SKY.

**Comment by olemis** [comment]
An exchange will be needed in between to perform the conversion , right ? If so 

- will this require an option to configure it ?
- any API to consume ?

**Comment by Senyoret1** [comment]
It is simply to convert a value, like "I want to send the equivalent of 50 USD in SKY from my wallet to this address". We could simply use the USD price shown on the header to perform the calculation. That USD price is currently obtained from CoinMarketCap, so we should warn the user that the conversion is just an approximation.
