### ISSUE TITLE
Create API endpoints to store arbitrary data

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#2119]
The Angular wallet sometimes needs to save data. However, it is not possible to use `LocalStorage`, because the backend port changes in each execution, making the data inaccessible. Also, it would be good not to have to use Electron to access the file system.

To solve this it is necessary to create API endpoints to save data and read it. At least at the moment something very complex is not required, just being able to store arbitrary data (preferably a text string, to be able to write and read it easily from Javascript) and be able to identify the data in some way (probably an string serving as ID).

@mahansky , do you have any special requirements regarding this?

**Comment by mahansky** [comment]
Pretty much what you described, simple key-value (string-string) storage.

**Comment by gz-c** [comment]
#2032 is block by this

**Comment by gz-c** [comment]
This should be done before we release the HW wallet integration

**Comment by gz-c** [comment]
The endpoint should allow get, get, set, remove of a new JSON file stored in the data directory.  This JSON file contains a `{}`. Essentially, endpoints to modify a JSON dictionary. get and remove's argument is a list of keys. set's argument is a dict.

Should be a v2 endpoint. Add a new API set for it. Should only be enabled for client modes (standalone client, electron, run-client.sh).
