### ISSUE TITLE
Migrate to coinpaprika API

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2136]
They are deprecating the public API, https://pro.coinmarketcap.com/migrate/

Need to setup an account.
Due to the ratelimits, we may want to use a simple public server that hits the API every 5 minutes and caches the value.

**Comment by gz-c** [comment]
Or, we can use the Binance API, the price there will be good enough

**Comment by jaggedsoft** [comment]
You can also use coinpaprika's API without any need of setting up an api key or bothering with rate limits.

https://coinpaprika.com/coin/sky-skycoin/

https://api.coinpaprika.com/v1/tickers/sky-skycoin?quotes=BTC,ETH,USD

![image](https://user-images.githubusercontent.com/4283360/52485534-61b97900-2bb9-11e9-99b6-405a6148c974.png)

**Comment by jaggedsoft** [comment]
Alternatives: CoinGecko, https://nomics.com both free

**Comment by jaggedsoft** [comment]
Using the Binance API:
https://api.binance.com/api/v3/ticker/price?symbol=SKYBTC

Price is in BTC, you probably want USD.
You can get it from coinbase https://api.coinbase.com/v2/prices/BTC-USD/buy

Or you can download all symbols from binance like this https://api.binance.com/api/v3/ticker/price
Then multiply SKYBTC by BTCUSDT for the tether value.

**Comment by gz-c** [comment]
Ok, we can switch to coinpaprika
