### ISSUE TITLE
Run script to update Docker images' repo-info at release time

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#2137]
[Release instructions](https://github.com/skycoin/skycoin/blob/abf5eeb/README.md#update-the-version) include a step to update `repo-info` metadata of Docker images . Instructions should mention how to use [`update.sh`](https://github.com/skycoin/repo-info/blob/9e5e291/update.sh) script.

**Comment by stdevPavelmc** [comment]
Aka: argument step 5...

I think the most efficient way is to describe the upgrade procedure in the README.md of the https://github.com/skycoin/repo-info and just mention here (on step 5) the fact that you must update the images repo-info following the described procedure there...

What you think about this solution?

**Comment by olemis** [comment]
Sure . README in this repository is not meant to contain instructions for something that belongs in another repository.

**Comment by olemis** [comment]
@stdevPavelmc in this README just mention what needs to be done and include a link to the detailed instruxctions for `repo-info`.

**Comment by stdevPavelmc** [comment]
Going for it, WiP on https://github.com/skycoin/repo-info/issues/18
