### ISSUE TITLE
failed to open skycoin wallet

### ISSUE THREAD

**Issue by 200495** [skycoin/skycoin#2176]
![1550481831 1](https://user-images.githubusercontent.com/23026128/52940679-11ed6580-33a2-11e9-893b-c127e2cc91b1.jpg)
Failed to start skycoin
Error:spawn ./resources/app/skycoin.exe ENOENT

**Comment by 200495** [comment]
![1550481831 1](https://user-images.githubusercontent.com/23026128/52940866-832d1880-33a2-11e9-9f4f-c5ff4d5566e2.jpg)

**Comment by 200495** [comment]
0.25.1 windows10

**Comment by gz-c** [comment]
Which version did you download?

**Comment by 200495** [comment]
The version I use is https://downloads.skycoin.net/wallet/skycoin-0.25.1-gui-electron-win-setup.exe

**Comment by 200495** [comment]
I install it and then I can open it.But after I close skycoin ,I fail to open it again.

**Comment by Senyoret1** [comment]
It looks like the the node's executable file was deleted. It should be in {wallet instalation folder}/resources/app/skycoin.exe

**Comment by gz-c** [comment]
do you have anti virus software? it may have quarantined the exe
