### ISSUE TITLE
Trouble building with go install on develop branch

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skycoin#2201]
I'm repeating the steps for [installing skywire](https://github.com/skycoin/skywire#install) in this [archlinux PKGBUILD for skycoin](https://raw.githubusercontent.com/0pcom/skycoin-archlinux-packages/master/skycoin/PKGBUILD)

at this point in build
```
go install \
  -gcflags "all=-trimpath=${GOPATH}" \
  -asmflags "all=-trimpath=${GOPATH}" \
  -ldflags "-extldflags $LDFLAGS" \
  -v ./...
```
errors out like this:

```
# github.com/skycoin/skycoin/cmd/skycoin
skycoin/skycoin.go:85:3: unknown field 'MaxBlockTransactionsSize' in struct literal of type skycoin.NodeParameters
github.com/skycoin/skycoin/cmd/cli
==> ERROR: A failure occurred in build().
    Aborting...
```

But it works when I switch from `develop` to `master`

**Comment by gz-c** [comment]
From what folder are you running that command?

**Comment by gz-c** [comment]
I don't see that `go install` step in the skywire instructions, but how are the skywire install instructions related to skycoin?

**Comment by 0pcom** [comment]
From the skywire README.md
```
Unix systems

mkdir -p $GOPATH/src/github.com/skycoin
cd $GOPATH/src/github.com/skycoin
git clone https://github.com/skycoin/skywire.git

Build the binaries for skywire

cd $GOPATH/src/github.com/skycoin/skywire/cmd
go install ./...
```

`make run-client.sh` is launching the client, and what I'm trying to do is generate the binaries and install them at some location in the system... so it's appropriate to build the binaries without launching them with `go install` or `go build`

This process is defined in a PKGBUILD script, which is used by makepkg to generate the package which is installed by the package manager on archlinux.

The installed package works correctly for skycoin & skywire if they are creted successfully with makepkg. Since these are both written in GO I thought that the packagebuilds should not take radically different approaches from one another.

Also, Steve asked me to make this issue. I'm only offering the extra info for context.

**Comment by gz-c** [comment]
This is either a skywire problem or was a problem with the code on your system
