### ISSUE TITLE
Update API doc curl examples to remove backslashes from URLs

### ISSUE THREAD

**Issue by paulie1234** [skycoin/skycoin#2202]
Issue 
Getting 404 not found using the API for get transactions for addresses.  
https://github.com/skycoin/skycoin/blob/develop/src/api/README.md#get-balance-of-addresses  
 
Example: 
http://127.0.0.1:xxxxx/api/v1/balance/?addrs\=7cpQ7t3PZZXvjTst8G7Uvs7XH4LeM8fBPD,nu7eSpT6hr5P21uzw7bnbxm83B6ywSjHdq,2jBbGxZRGoQG1mqhPBnXnLTxK6oxsTf8os6 
 
Situation; Wallet is fully synced and there is a network connection. 
 
Fix 
Remove backslashes and build it up like below: 
 
http://127.0.0.1:xxxxx/api/v1/balance?addrs=7cpQ7t3PZZXvjTst8G7Uvs7XH4LeM8fBPD,nu7eSpT6hr5P21uzw7bnbxm83B6ywSjHdq,2jBbGxZRGoQG1mqhPBnXnLTxK6oxsTf8os6

**Comment by gz-c** [comment]
API doc curl examples should use single quotes around URLs instead of inserting backslashes so that the URL can be copied and pasted into a browser

**Comment by BigOokie** [comment]
There is a clear issue with the example referenced by @paulie1234 above, but it looks like an issue with the way that specific example has been written (structured). 

Most other examples are structured as below (taken from the API docs) - whereby each command parameter is shown on a seperate line and uses single quotes and a backslash to format this correctly.

Example:
```sh
curl -X POST http://127.0.0.1:6420/api/v1/wallet/newAddress \
 -H 'Content-Type: x-www-form-urlencoded' \
 -d 'id=2017_05_09_d554.wlt' \
 -d 'num=2' \
 -d 'password=$password'
```

Is it acceptable to continue using the above structure / format for multi-parameter examples? Single parameter examples should be on a single line. IMO it does improve readability of the doco.

**Comment by BigOokie** [comment]
I reviewed that document, and this was the only incorrectly formatted example (based on my previous assumptions)

**Comment by BigOokie** [comment]
Note - I haven't checked other documents.

**Comment by gz-c** [comment]
@BigOokie that example works for `POST` requests. I don't know how to split `GET` query params across lines
