### ISSUE TITLE
Move visor/verify.go into params or new package

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2209]
Since the blockchain verification parameters have been moved to package params, `visor/verify.go` can be moved to either the params package or to a new package.  This will fix some import cycle issues and allow packages like `wallet` and `transaction` import these verification routines.

Blockchain-based transaction verification will necessarily remain in package visor.

This refactor should allow `package wallet` and/or `package transaction` use these verification methods for sanity-checking their output. Currently, they reimplement their own sanity checks.

**Comment by nkryuchkov** [comment]
@gz-c , while working on this, I noticed that `src/util/fee_test.go` imports the `params` package to use `UserVerifyTxn` struct. But `visor/verify.go` also imports `fee` for some of its methods. This way being moved to params package `visor/verify.go` causes the cycling import. I think that the `params` is the right place for it, but I am not sure how I should handle this import
