### ISSUE TITLE
Remove wallet in electron app GUI

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#2226]
**Describe the solution you'd like**
Each wallet in the list should have a button to remove it .

**Possible implementation**
Even if [there is intentionally no API method to delete a wallet](t.me/skycoindev/4194) it'd be nice to , at least hide it . If the later is the way to go then it should be possible to select a specific wallet to un-hide it.

**Comment by therealssj** [comment]
I would go with hide. 
Letting the wallet delete files doesnt seem secure

**Comment by Senyoret1** [comment]
This would depend on https://github.com/skycoin/skycoin/pull/2126

**Comment by gz-c** [comment]
wontfix
