### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2242]
Add ability to change the UI language.

We already have the i18n support

**Comment by olemis** [comment]
@gz-c will this have a side effect to the hardware wallet ? I mean , if language of desktop GUI changes to , say , Italian will this change be applied upon the hardware wallet as well ?

**Comment by gz-c** [comment]
No

**Comment by Senyoret1** [comment]
Also mentioned in https://github.com/skycoin/skycoin/issues/1981 . I'll start working on this after finishing some pending things in relation to the hardware wallet. I've been thinking a bit about implementation and maintainability and I think that 2 additional things should be included:

- Comments in the file that contain the text string, giving some context and length limitations, in cases where it is necessary.

- A method (including some script) for following the changes made to the file with the English strings and to know that parts of the files with other languages are outdated. If this is not done, the process of updating the translations could be extremely slow and annoying.
