### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2243]
This is assigned to someone

**Comment by 200495** [comment]
Hi, can you tell me when the Chinese translation version would be completed or in which version the Chinese translation would be added to skycoin wallet?It is a good news!

**Comment by 200495** [comment]
Oh,I can supply a Chinese translation json file of GUI.
[ch.zip](https://github.com/skycoin/skycoin/files/3020857/ch.zip)
