### ISSUE TITLE
Fill /metrics endpoint with the data of /health endpoint

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#2245]
The `/v2/metrics` now returns the basic go status, we need more data to monitor node's status.

Some data in `/health` endpoint can be add to `/metrics`, like: 

```json
time_since_last_block
open_connections
outgoing_connections
incoming_connections
uptime
started_at
...
```

**Comment by olemis** [comment]
@iketheadore some time ago it was decided not to do this in `skycoin/skycoin` code so as to not include Prometheus instrumentation code all over skycoin code . That's what https://github.com/simelo/rextporter was implemented for.

**Comment by olemis** [comment]
> That's what https://github.com/simelo/rextporter was implemented for.

It's a Prometheus exporter that scrapes metrics out of REST API .

**Comment by iketheadore** [comment]
Oh, that's great, I will check it.

**Comment by gz-c** [comment]
We can't customize our prometheus endpoint to add the health metrics in prometheus format?

**Comment by iketheadore** [comment]
We can customize the /metrics endpoint to add health metrics. @olemis do you know why we decide to not add it in /metrics endpoint?

**Comment by olemis** [comment]
> We can't customize our prometheus endpoint to add the health metrics in prometheus format?

It's possible yes, but would be duplicate work . That's exactly what https://github.com/simelo/rextporter was for .

**Comment by olemis** [comment]
> We can customize the /metrics endpoint to add health metrics. @olemis do you know why we decide to not add it in /metrics endpoint?

Some time ago it was decided to implement a configuration like https://github.com/prometheus/node_exporter (a node scraper) rather than writing code in `skycoin/skycoin` for this .

**Comment by olemis** [comment]
The other reason was to reuse the same logic for monitoring multiple projects.

**Comment by olemis** [comment]
> Some time ago it was decided to implement a configuration like https://github.com/prometheus/node_exporter (a node scraper)

Sorry , not like `node_exporter` but like https://github.com/prometheus/mysqld_exporter i.e. an external service that scrapes metrics . The benefit of https://github.com/simelo/rextporter is that is scrapes any REST API . It's configurable .

**Comment by stdevAlDen** [comment]
@iketheadore let me know if you face any issue trying to run rextporter

**Comment by iketheadore** [comment]
OK, I tested it in my local docker environment(I wrote a Dockerfile to build the rextporter image), it worked fine and able to scrape the `health_seq` metrics. But if in the kubernetes, I don't know how to scrape multiple nodes that are in the same service, for instance, we have two backend skycoin api nodes in service of `http://skycoin-api-node.skycoin.svc.cluster.local`, each time we call it, we will get a response randomly from the two api nodes.

**Comment by olemis** [comment]
`rextporter` supports scraping multiple REST API instances . Does it work ? I might not be familiar with all the details.

**Comment by olemis** [comment]
> Does it work for you?

If so then @stdevAlDen can explain the details .

**Comment by iketheadore** [comment]
Base on the config file I think it supports multiple REST API instances, but the problem is we need to scrape multiple node instances through one k8s service api, our api nodes are load balanced by the k8s services.

**Comment by olemis** [comment]
>  we need to scrape multiple node instances through one k8s service api

wouldn't you have the same problem if implementing the metrics in `skycoin/skycoin` code ? In the end the problem seems that only one node is reachable from the other side of the load balancer , right?

**Comment by olemis** [comment]
I'm assuming load balancer is in between Prometheus and Skycoin nodes . if so maybe there is a chance for `rextporter` to be behind the load balncer (so as to query Skycoin nodes directly) and Prometheus talk to rextporter (through the load balancer or maybe not).

**Comment by iketheadore** [comment]
We're using the `service monitor` of `prometheus-operator` to scrape the metrics, it can get the metrics from each node through the k8s service.

**Comment by olemis** [comment]
> We're using the `service monitor` of `prometheus-operator` to scrape the metrics, it can get the metrics from each node through the k8s service.

There are two configurations possible :

- Prometheus operator queries a single `rextporter` instance that aggregates metrics from multiple Skycoin nodes
- Each Skycoin node is run together with a rextporter instance (same container or not) , `rextporter` scrapes node metrics via `localhost` and the operator consumes `rexporter` output .

**Comment by iketheadore** [comment]
OK, run the rextporter as a sidecar of each node might be able to work, I will have a test.

**Comment by olemis** [comment]
Just in case we'll prepare an image with both Skycoin and Rextporter bundled and pre-configured . In case you might prefer to do things this way.

**Comment by iketheadore** [comment]
We don't need image with Skycoin and Rextporter bundled.

**Comment by iketheadore** [comment]
Hmm, I'd prefer not to use the rextporter, it's too complicate comparing to just add data in /metrics endpoint.

**Comment by stdevAlDen** [comment]
> kubernetes

Try to make this configuration:
![diagram](https://user-images.githubusercontent.com/34870496/55010402-7f506f80-4fba-11e9-8ab6-e64d219cb04d.png)

`R1` (inside the cluster) should be configured to read metrics from each node, and `R2` should be configured to read metrics from `R1` as metrics forwader like this:
```toml
[[ResourcePaths]]
	Name = "metricsFordwader"
	Path = "/api/v2/metrics"
	PathType = "metrics_fordwader"
	httpMethod = "GET"
```

If the nodes can change dynamically a service discovery feature is required(not implemented yet).

@iketheadore it's this feasible for you?

**Comment by iketheadore** [comment]
Hmm, actually I've finished the code the day when I file this issue, it's under testing with the devops.
