### ISSUE TITLE
Unconfirmed txns in history view are not marked as unconfirmed

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2257]
To replicate: broadcast a transaction and quickly switch to the history tab. You'll see the transaction at the top, but it isn't labelled as unconfirmed.

**Comment by Senyoret1** [comment]
It worked well for me. Maybe the history must be opened faster or I did something in a different way...
![pending](https://user-images.githubusercontent.com/34079003/56086352-22124600-5e23-11e9-8f58-c94070e84a0d.png)

**Comment by gz-c** [comment]
I'll have to try again
