### ISSUE TITLE
OS X Travis build failing on e2e tests

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2275]
https://travis-ci.org/skycoin/skycoin/jobs/521624902#L9872

**Comment by gz-c** [comment]
It might be because of the recent change to use `services` in the travis.yml, which is not supported according to the logs @therealssj

**Comment by therealssj** [comment]
its related to this https://github.com/angular/webdriver-manager/issues/260

but its seems to have been fixed recently. I am not sure how to update webdriver-manager to the latest version though.

Here is an old solution: https://stackoverflow.com/questions/52830276/protractor-e2e-angular-6-web-ui-error-getaddrinfo-enotfound-chromedriver-st

**Comment by Senyoret1** [comment]
It was just a connection error in Travis . Restarting it solved the problem.

**Comment by Senyoret1** [comment]
@therealssj and I were checking the problem and it turned out to be just an connection error in Travis. Restarting it solved the problem.
