### ISSUE TITLE
The result of addressGen not save in wallet in '0.24.1' version

### ISSUE THREAD

**Issue by litterGuy** [skycoin/skycoin#2282]
Hi
My client version is 0.24.1, using the cli command line to generate the address addressGen but the generated address is not saved to the wallet file "wlt". But I have already transferred the currency to the generated address.

Ask me, how can I retrieve the currency of the generated address?
Comes with cli configuration:
![image](https://user-images.githubusercontent.com/2154539/56649220-4d185780-66b7-11e9-85a7-641718e2fbb9.png)

**Comment by therealssj** [comment]
do you have the seed ?

**Comment by litterGuy** [comment]
> do you have the seed ?

I have the seed of the wallet but did not generate the seed for that address.

**Comment by therealssj** [comment]
@litterGuy what do u mean u have the seed but not for that address?
The address is derived from the seed

**Comment by litterGuy** [comment]
The address generated by the addressGen command in the previous version is not stored in the wlt file. Why is it not in 0.24.1?
Can't the seed be found in other files? The address was generated using a wallet but could not find the seed？

**Comment by therealssj** [comment]
@litterGuy in current version also it is not stored in the wallet file. 
Did u ever load the address in the wallet?

**Comment by gz-c** [comment]
If you have the initial seed of the wallet you can generate all addresses from it.  Use "add address" in the GUI or use the `-n` parameter in CLI's `addressGen`.
