### ISSUE TITLE
/wallet/transaction should not require password if the unsigned flag is true

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2286]
Referencing a problem with #2221 
@Senyoret1

**Comment by Senyoret1** [comment]
If I understand correctly, this issue is for the change in how the API works. I will make the change in the UI after the API change is ready.

**Comment by iketheadore** [comment]
@gz-c @Senyoret1  I checked the code of `/api/v1/wallet/transaction` endpoint, it should not require password if `unsigned` flag is true. I wrote a test by sending `api.WalletCreateTransactionRequest` with `Unsigned: true` , it did not require a password and returned an unsigned transaction successfully.

**Comment by gz-c** [comment]
@Senyoret1 can you confirm, and then use that endpoint?

**Comment by Senyoret1** [comment]
Not sure about what the problem was when I tried to use it, maybe I made a misstake. I tested the endpoint and is working well, so I made the change
