### ISSUE TITLE
hardware wallet daemon build integration 

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#2291]
Options for daemon packaging:
https://github.com/skycoin/hardware-wallet-daemon/wiki/Daemon-packaging
 We have decided to go with route 7. 

https://github.com/skycoin/hardware-wallet-daemon/issues/40#issuecomment-481772077
As explained by @gz-c above we need to modify skycoin release build process to optionally build and include the hw daemon in the core package

**Comment by gz-c** [comment]
Question: how we will handle updates of the hw daemon, if it is bundled with the hw wallet?

Its probably easiest to start with a separate download and install process for the hw daemon

**Comment by gz-c** [comment]
We will not be bundling them, because that will tie the release cycle together, but they are not on the same release cycle.

The user will be required to download and run the hw daemon separately, if they wish to use the hw wallet.
