### ISSUE TITLE
Using the wallet/update API endpoint crashes

### ISSUE THREAD

**Issue by cryptrol** [skycoin/skycoin#23]
The following output to stderr happens :

    2015/01/30 09:49:47 http: panic serving 127.0.0.1:52314: interface conversion: *wallet.ReadableWallet is not wallet.Wallet: missing method AddEntry
goroutine 190 [running]:

**Comment by skycoin** [comment]
What platform, operating system?

**Comment by cryptrol** [comment]
Debian 7, 64bits.
It seemed a wrong assertion of the wallet interface but I didn't had time to look closer.

**Comment by skycoin** [comment]
fixed; do "git pull" and then try again
