### ISSUE TITLE
Check the size of the texts with the Chinese translation

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#2303]
As the UI was created in English, some labels/controls may be using a font size that is too small for the Chinese translation.

I checked and the smallest texts I found almost always had a size of 11px, which is just a little smaller than the recommended size of 12px, and that font size was only used in few places (mainly explanations, like in the advanced form and the backup page). Although from that point of view the design seems to be fine, It must be verified by someone else.

If a text is too small, it is possible to make it bigger only when using certain languages.

@gz-c this issue is more like a "reminder", but maybe it should be added to 0.26

**Comment by gz-c** [comment]
Seems fine
