### ISSUE TITLE
Multiple console errors (Safari)

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2319]
<img width="1490" alt="Screen Shot 2019-05-14 at 10 10 56 PM" src="https://user-images.githubusercontent.com/26845312/57704805-38ffbe80-7695-11e9-9033-d57069603564.png">

@Senyoret1 will some of these go away when we remove the hardware wallet code?

**Comment by gz-c** [comment]
<img width="1501" alt="Screen Shot 2019-05-14 at 10 15 56 PM" src="https://user-images.githubusercontent.com/26845312/57705168-e1ae1e00-7695-11e9-82d4-988ce54d829a.png">

This is the result after disabling hardware wallet integration.

I still see the "syscalls.md" warning. I believe this is due to gopherjs.  Gopherjs should not be used in the desktop wallet

**Comment by Senyoret1** [comment]
The 404 error messages are being automatically added to the console by the browser. I'm not sure about the errors with the CSP, I had not seen them before and I do not have access to a recent version fo Safari at this moment. Maybe @mahansky could check if everything continues working well.

About GopherJS, I created a PR for disabling it: https://github.com/skycoin/skycoin/pull/2322 . Currently it is only used for serializing the transactions of the hardware wallet, so I will try to create a serializer in TypeScript to be able to delete the library completely.

**Comment by gz-c** [comment]
The "ERROR" that appears after the 404 errors is related to the 404 errors. Excessive logging?

**Comment by gz-c** [comment]
The hoversee_inject errors are due to an extension and are fine

**Comment by gz-c** [comment]
@Senyoret1 note, after merging the skycoin-lite removal, the application loaded much faster

**Comment by gz-c** [comment]
Remaining issue is the error logging of the api/v2/data requests

**Comment by Senyoret1** [comment]
The extra error in the console is because the default behavior of Angular is to log all errors in the console (the first error is added automatically by the browser). Solved in https://github.com/skycoin/skycoin/pull/2327
