### ISSUE TITLE
skycoin-cli autocomplete in zsh is not working

### ISSUE THREAD

**Issue by stdevMac** [skycoin/skycoin#2340]
I am using `zsh` in Ubuntu 18.04 
When i tried of set up skycoin-cli autocomplete i get the next error:

```sh
$ PROG=skycoin-cli source $GOPATH/src/github.com/skycoin/skycoin/cmd/cli/autocomplete/zsh_autocomplete                                  
_arguments:comparguments:319: can only be called from completion function
_arguments:comparguments:319: can only be called from completion function

```

**Comment by olemis** [comment]
@stdevMac did you do exactly what is stated in the README ?

**Comment by stdevMac** [comment]
@olemis I follow exactly this https://github.com/skycoin/skycoin/blob/develop/cmd/cli/README.md#install

**Comment by gz-c** [comment]
@iketheadore can we remove the autocomplete?
