### ISSUE TITLE
Add the url for getting the lastest version number to health

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#2376]
This is related to https://github.com/skycoin/skycoin/issues/2043

As the wallet is going to get the number of the lastest version from a custom URL, to know if an update is available, that URL should be added to the `health` API endpoint. This is needed mainly for being able to easily configure the Fiber coins.

To clarify:

The version is downloaded from https://version.skycoin.net/skycoin/version.txt.  This issue is requesting that that URL be configurable.

**Comment by Senyoret1** [comment]
Thinking more about this, this is not appropriate. The `health` endpoint should include the data needed by the multicoin wallets for correctly showing info about the coin. The info about the updates is not related to the coin, but the wallet software itself, so this URL should be in a configuration file.

**Comment by gz-c** [comment]
It is needed, because most coins fork the code and reskin, they are on a different upgrade path.

**Comment by Senyoret1** [comment]
The problem is this:

Generic data about the coins, like the coin name, is useful everywhere. The desktop, web and mobile wallets should use the same name for the GUI, so it is good to have it in the health endpoint.

However, getting the lastest node version is only useful for the desktop wallet, for asking the user to download the lastest version. The web and mobile wallet would have a different version, so a different URL for getting the corresponding lastest version would be needed for each of those wallets.

Also, another problem is that the URL has to be added to the CSP, so getting it at runtime complicates things, at least for the Electron host whitelisting.

To keep things simple, every wallet should have its own URL in a config file. I’m starting to use the `app.config.ts` file of the desktop wallet just for that.

**Comment by gz-c** [comment]
That needs to be added to the fiber manual then
