### ISSUE TITLE
/api/v1/wallet/transaction 415 Unsupported Media Type

### ISSUE THREAD

**Issue by litterGuy** [skycoin/skycoin#2398]
Request process：
![image](https://user-images.githubusercontent.com/2154539/59019746-2edb7500-887b-11e9-9d5f-218005f89812.png)

I don't know why, using the same request method /api/v1/injectTransaction can be called successfully. The code is roughly as follows：
```
OkHttpClient client = new OkHttpClient.Builder()
                .readTimeout(60, TimeUnit.SECONDS)
                .addInterceptor(new LogInterceptor())
                .build();
        String url = getUrl(host, port, uri);
        String jsonString = o == null ? "" : JSON.toJSONString(o);

        String contentType = "application/json; charset=utf-8";

        MediaType mediaType = MediaType.parse(contentType);
        RequestBody requestBody = RequestBody.create(mediaType, jsonString);

        Map<String, String> hm = new HashMap<>();
        if (MapUtils.isNotEmpty(headerMap)) {
            hm.putAll(headerMap);
        }
        Headers headers = Headers.of(hm);

        Request request = new Request.Builder().url(url)
                .headers(headers)
                .header("Content-Type", "application/json")
                .post(requestBody).build();

        String result = null;
        try {
            Response response = client.newCall(request).execute();
            result = response.body().string();
        } catch (IOException e) {
            log.error("wallet request params is {}. exception: {}", JSON.toJSONString(o), e.getLocalizedMessage());
        }
```

ps：Wallet v0.26.0

**Comment by olemis** [comment]
What language is this? Java? Have you tried the Java client library?

**Comment by litterGuy** [comment]
Yes, the java jar package is okhttp3. The same result was used with the httpclient jar package.

**Comment by litterGuy** [comment]
Still because of the issue of Content-Type. Only the "application/json" is checked in the code, but the setting of charset is not considered.
Can't I change to include "application/json"?
code like that:
https://github.com/skycoin/skycoin/blob/ff754084df0912bc0d151529e2893ca86618fb3f/src/api/spend.go#L581-L584

**Comment by gz-c** [comment]
This was changed in the `develop` branch to ignore the value of `charset` in the `Content-Type` header (since json is always utf-8). See #2365
