### ISSUE TITLE
Unable to see the destination address on wallet

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/skycoin#2400]
As part of the hardware-wallet test I want to check if the destination address that I see in my device match with the one in the web app at the send stage (see picture)

![err](https://user-images.githubusercontent.com/34870496/59140491-30389a80-896c-11e9-9046-8b195537a9b6.png)

checkout at 7399c481b15517d2bb72b1ccf7feb621df3b5b7e

PD: Maybe this is not a bug but I just want you to consider this

**Comment by olemis** [comment]
@stdevalden what about transactions with many outputs ?

**Comment by Senyoret1** [comment]
We could show the info in the modal window, but I'm not totally sure we should. In fact, I would prefer the user to compare the data shown in the hw wallet screen to the original data in the original source (email, paper, etc.), not what the desktop wallet shows. This is to be consistent with the fact that the objetive of the hardware wallet is to be able to be safe even if the desktop wallet or the computer was compromised in any way.

**Comment by gz-c** [comment]
Maybe we need to display the transaction data in the modal, along with a message telling them that they need to compare this data to the data on the hardware wallet
