### ISSUE TITLE
Do not show all transactions in the history immediately

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#2402]
If the user has a lot of transactions, the history shows a very long list and that affects the performance. In fact, the application freezes for a few seconds if the list is too large. To avoid this, the history needs pagination or a "load more" button.

**Comment by gz-c** [comment]
Depends on #2090

**Comment by Senyoret1** [comment]
It could start to be implemented before #2090 with a similar approach to the one used in the explorer. The main problem is adding too many elements to the UI at the same time, so for the moment all the elements could be kept in memory and simply avoid adding all to the UI at the same time. It would not be a perfect solution, it would be better with #2090, but it would improve the performance a lot when the number of transactions is excessive.
