### ISSUE TITLE
Better error msg for when unable to connect with the hw wallet daemon

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#2473]
Currently, if the user tries to use the hw wallet and the GUI is unable to connect with the hw wallet daemon, the GUI says “Problem connecting to the Skywallet service.”. The message was ok when the plan was to include the daemon with the desktop wallet, but now that the plan is to distribute it independently, the error message should tell the user what to do.

A good sollution would be to add a download url, but what will the url be and what indications should be shown to the user for after opening the url?

**Comment by therealssj** [comment]
Add daemon downloads to https://www.skycoin.net/downloads/
Add link to the daemon section in the message
Or 
We create a separate product site for the daemon and add a download daemon section there and link that
