### ISSUE TITLE
Include the BIP21 prefix in the /health endpoint

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#2477]
When creating QR codes and URLs for requesting coins, the content is similar to this: `skycoin:[address]`. That is a simple example similar to `coinName + ':' + address`, but there could be coins with complex names (maybe with more than one word) and in that case just using the coin name may be a bad idea. Because of that, it would be good to add the URL prefix to the `/health` endpoint.

**Comment by iketheadore** [comment]
@Senyoret1 a new field `qr_uri_prefix` has been added to the `/health` endpoint.  Please have a check, thank you.
