### ISSUE TITLE
Do not close modal windows by clicking on the background

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#2480]
Currently, if a modal window is being shown and the user clicks on the background, the modal window is closed. The problem is that the hw wallet integration has a lot of relatively small windows and the current behavior has caused some of those windows to be closed by accident during pre-release testing. The current behavior is the default behavior of Angular Material and deactivating it might be a good idea to avoid problems with the UX.

**Comment by iketheadore** [comment]
Fixed by https://github.com/SkycoinProject/skycoin/pull/186
