### ISSUE TITLE
Corrupted files result in ERROR #1 for Linux

### ISSUE THREAD

**Issue by SkycnTrnsltns** [skycoin/skycoin#2486]
For unknown reasons client.json and peers.json get corrupted. 
When the wallet is opened this results in ERROR #1. No log files are written.

content of client.json (full text):
õ}1~@	®ô:ç¡VLmi

content of peers.json (example text)
3@*Ã!°6I¨Ne«@ø¿° 

Wallet Version: v0.26
Linux Version:
NAME="Linux Mint"
VERSION="19.2 (Tina)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.2"
VERSION_ID="19.2"

Error screenshot:
![error#1](https://user-images.githubusercontent.com/43423539/66713953-c2d0c680-edb0-11e9-8432-4f46b71e5620.png)

FIX: Get client.json and peers.json from a fresh .skycoin folder and simple copy them in the folder of the non working wallet.

**Comment by BigOokie** [comment]
Note that a similar issue was previously reported with Windows and a fix was applied as part of #2083 which is now closed.

**Comment by SkycnTrnsltns** [comment]
was this fix included in the v0.26 linux release?
