### ISSUE TITLE
Transaction violates soft constraint: Transaction coinhour fee minimum not met

### ISSUE THREAD

**Issue by lfj7282** [skycoin/skycoin#2492]
when i  do this  /api/v1/injectTransaction  get error
[2020-03-26T10:26:25+08:00] ERROR [daemon]: InjectUserTransactionTx failed error="Transaction violates soft constraint: Transaction coinhour fee minimum not met"
[2020-03-26T10:26:25+08:00] ERROR [api]: 400 POST /api/v1/injectTransaction 45.911631ms body="400 Bad Request - Transaction violates soft constraint: Transaction coinhour fee minimum not met"

this is my transaction detail
{
    "hexIn":[
        "0a8498ee44ce568da56631e64b6e87614282c463abaa19effb3b583d8983977e"
    ],
    "hexInnerHash":"a8f81ad08efe8dc6c7e4e764f3c389e2c6456c1d76784392f38d9ed21454d857",
    "inputAddress":[
        "2C2YnkpGqTCzLMHS6mTnUuwx8xqj1XGeE8"
    ],
    "length":0,
    "out":[
        {
            "base58Addr":"ArgqfWrdnVroFbvpreoGicrFHQVqFu84ddtSSWKZ",
            "coins":25976000,
            "coinsStr":"25.976000",
            "hours":1,
            "hoursStr":"1"
        },
        {
            "base58Addr":"8ngopZYFGb2Dazt6nQ9nZp2Dw2pdEMxY4KmUryg",
            "coins":2249288000,
            "coinsStr":"2249.288000",
            "hours":12055304,
            "hoursStr":"12055304"
        }
    ],
    "type":0
}

can someone help me,how to fix it.

**Comment by Senyoret1** [comment]
Sorry, but this repo is not being maintained. The updated code is in https://github.com/SkycoinProject/skycoin
