### ISSUE TITLE
Clean the desktop wallet TypeScript code

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#2526]
Senyoret1 commented on Dec 18, 2019

The TypeScript code of the desktop wallet should be improved, to make it easier to read and mantain. This includes removing old unused code and adding basic comments.

**Comment by iketheadore** [comment]
@Senyoret1 is this done?

**Comment by Senyoret1** [comment]
Yes, done in https://github.com/skycoin/skycoin/pull/2589

**Comment by iketheadore** [comment]
Great, thanks.
