### ISSUE TITLE
static builds with musl

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skycoin#2563]
https://github.com/skycoin/skywire/issues/614

https://github.com/skycoin/skywire/pull/634

this can be achieved with the following steps;
* add `musl-tools` or the appropriate musl package for the build environment
* use `CC=musl-gcc` as env or export
* `go build` with `--ldflags '-linkmode external -extldflags "-static"'`

**Comment by iketheadore** [comment]
We don't use cgo or have dependencies that are using cgo, do we still need musl?

**Comment by 0pcom** [comment]
This is replacing a 'glibc' or 'libc6' runtime dependency.

I have not seen the skycoin binary fail, but I pursued static compilation with musl because of issues I was having with compiling skywire on systems with more recent versions of glibc; while deploying them on armbian where glibc or libc6 was an older version.

Static compilation with musl solved that for me.

I'm unsure if there is a glibc runtime dependency for skycoin but I've changed all my PKGBUILDs of skycoin repos to use static compilation with musl just in case.

@SkycoinSynth had requested this

**Comment by iketheadore** [comment]
Does the `musl-tool` work on macOS and windows?

**Comment by 0pcom** [comment]
> Does the `musl-tool` work on macOS and windows?

I am not able to test it.

In theory it __may__ work in the linux subsystem for windows, but rudi was having trouble getting musl on macOS.

**Comment by iketheadore** [comment]
Yes, I got error when using musl on macOS as well, since the wallets need to be able to run on all platforms, and currently it worked well, perhaps we do not need it for wallets. Anyway, maybe we can use musl when building docker image.
