### ISSUE TITLE
Include the explorer in the desktop wallet

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#2570]
Including the explorer inside the desktop wallet would bring availability and security improvements. For doing this, this is needed:

- [ ] The changes for making the explorer work without the intermediate server have to be merged: https://github.com/SkycoinProject/skycoin-explorer/pull/31

- [ ] The node needs code for serving the UI.

- [ ] Steps must be added to the build process for getting and compiling the explorer.

- [ ] The UI needs changes for opening the local explorer and not the remote one.

**Comment by iketheadore** [comment]
Hi, please do not do this, we have removed the blockchain explorer from wallet years ago. And don't have plan to add it back yet. We need to focus on the improvement of the stability of exploer.skycoin.com.
