### ISSUE TITLE
skycoin-cli distributeGenesis ; Signature not valid for output being spent (fibercoin)

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skycoin#2582]
When attempting to distributeGenesis with a newly created 'fibercoin' blockchain (created with newcoin) 

```
skycoin-cli distributeGenesis <blockchain private key>
```
Fails in the following way
```
Error: 400 Bad Request - Transaction violates hard constraint: Signature not valid for output being spent
```

Reproducing this issue:

[NEWCOINDOC.md.txt](https://github.com/skycoin/skycoin/files/6012965/NEWCOINDOC.md.txt)

Note, the very last step of 'run a peer node' was done in a different way than was stated.

Both publisher and peer node are running on my local machine.

If there was a method for genesis distribution before `distributeGenesis` was created, please share it with me.

**Comment by iketheadore** [comment]
This is a problem about the document, when first time to run the new coin to generate signature, we should use `--genesis-address` flag to specific the genesis address we generated with `addressGen`. In the example of the doc, it does not use the flag, which makes the new coin use the skycoin's genesis address to generate the signature, and hence lead to the `Transaction violates hard constraint: Signature not valid for output being spent` error when doing distribution.
