### ISSUE TITLE
Fix github actions test errors

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#2587]
The virtual environment of github actions are now using chrome 86. However, the ui integration tests require chrome 89, we used to be able to run `sudo apt-get update and sudo apt-get upgrade google-chrome-stable -y` to upgrade the chrome, but apparently, recent tests were all failed in the `sudo apt-get update` command. 

Once https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20210309.1 is released, the chrome will be upgrade from 86 to 89.

**Comment by Senyoret1** [comment]
The e2e test use the latest version of Chrome by default, which can sometimes be problematic, specially when it tries to use a version that is so new that even Chrome has problem to get it via the updater. If this becomes a common problem, I can make the e2e tests use a specific version of Chrome, but changes will be needed to ensure Github uses always that exact version.
