### ISSUE TITLE
Docker implementation doesn't work as expected

### ISSUE THREAD

**Issue by dharmendrakariya** [skycoin/skycoin#2613]
I tried running node by docker container, but after it retrieves all the blocks at some point it gets stuck, and also on defined port i.e. ```6420``` I am not seeing any dashbord, it gives 404 page not found, also I checked inside the container but same result.

**Comment by iketheadore** [comment]
Please post the docker command you have used to run the node. Also, can you post the logs when it got stuck? 

The document on https://github.com/skycoin/skycoin#docker-image worked for me to start a node, but there's no dashboard at all, it's normal to get a 404 error. The docker image of skycoin/skycoin is skycoin node image, the wallet functions are not supported. I'll update the document about it. Sorry for the confusion.
