### ISSUE TITLE
Problems related to the temporal wallets

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#2630]
When using the `/api/v1/wallet/createTemp` API endpoint, the `password` and `encrypt` params are ignored and the wallets are always created unencrypted. However, it is possible to use the `/api/v1/wallet/encrypt` API endpoint for encrypting the wallet.

If the desired behavior is to prevent temporal encrypted wallets to be created, then the encryption options must be removed from the UI for those wallets and maybe the `/api/v1/wallet/encrypt` API endpoint should return an error. Otherwise, the `/api/v1/wallet/createTemp` API endpoint should encrypt the wallets just like the `/api/v1/wallet/create` API endpoint does.

Appart from this, the `/api/v1/wallet/createTemp` API endpoint should be added to the API documentation.

**Comment by iketheadore** [comment]
Yes, it is designed to do not encrypt temporary wallet. I'll update the API `/api/v1/wallet/encrypt` to ignore the temporary wallets. And update the API document.
