### ISSUE TITLE
Trouble building on  Ubuntu 14.04

### ISSUE THREAD

**Issue by vijayee** [skycoin/skycoin#31]
~/Workspace/src/github.com/vijayee/skycoin$ ./gui.sh build
Compiling with go
Building release files
build-tools.sh: line 22: golang-nw-pkg: command not found
nw-pkg build failed

How do you setup golang-nw-pkg to compile the gui?

**Comment by skycoin** [comment]
Do ./setup.sh first or go into ./compile and then get get dependencies. There is a script for fetching the dependencies
