### ISSUE TITLE
Duplication of balances

### ISSUE THREAD

**Issue by SkyAudit** [skycoin/skycoin#349]
If you load the address twice or three times, the total sum of the skycoin will also be doubled or tripled.

**Comment by skycoin-main** [comment]
Please check, if this was fixed in the last pull request. Try to duplicate again.

It should be fixed.

It will now check the first address in the deterministic wallet and prevent you from loading the same seed twice.

**Comment by iketheadore** [comment]
It's not fixed in PR #347 yet , I didn't pushed the changes, will see in my next PR

**Comment by iketheadore** [comment]
PR #358 has fixed the api for creating duplicate wallet, but frontend also need update, @nakulpandey please add notification when user try to load wallet from seed that's already in his wallet.

**Comment by iketheadore** [comment]
@nakulpandey , any updates about this?
