### ISSUE TITLE
Marketing Plan

### ISSUE THREAD

**Issue by SkyAudit** [skycoin/skycoin#356]
Actionable Marketing Plan to Grow Skycoin into a Billion Dollar Market Cap Coin

1. Website Overhaul

- [ ] Determine the website style that you want to emulate
*Scrolling sites are fairly popular
*Examples are: https://litecoin.com/ , https://www.decred.org/ , https://www.ethereum.org/ ,https://bitshares.org/

- [ ] Choose design firm that can meet our needs
*Examples: http://eeter.co/ (of Decred fame: https://medium.com/eeter/decred-developing-identity-and-design-system-for-a-digital-currency-17df76ab67c8_
*If you like a design, you can ask the community who designed the site
*Behance and Dribble are good sources to find designers

- [ ] Meet with designer to discuss branding strategy
*Redesign logo, choose colors, layout, UX layout for wallet, etc
*Do this ASAP to allow time for designers to come up with proposals

2. Telling the Skycoin story
*Start by Finding a Writer who can explain Bitcoin into an easy to understand manner
*Examples: https://antonopoulos.com/
*http://bitcoinprbuzz.com/copy-writing-and-content-creation-for-bitcoin/
*Can also approach writers of magazines like Cointelegraph

- [ ] Focus on translating the story of Skycoin for the average person
*Introduction
*Getting Started
*How it works
*What is Skycoin, Skywire, Obelisk, Skybank, Meshnet, Aether, Sky Ledger in lay person terms
*History of Skycoin
*VIsion of Skycoin
*Context of why Skycoin is needed (Loss of Net Neutrality)
*FAQ
*How to participate
*User Guides
*Technology

3. Create Roadmap and Planned Features.
*This is to highlight the direction of Skycoin

4. Create a Developer Resources Section
*Documentation
*Development Guide
*How to Contribute

5. Wallet Overhaul of UX
-Hire UX guy to make wallet visually more appealing and skinned

6. Take Marketing Seriously and Devout Time, Effort and Money into Improving Communication with Potential Investors, Contributors, and Users

- 

- 

- 

- 

-

**Comment by erichquist** [comment]
*Previous to
