### ISSUE TITLE
URGENT: Improving Skycoin Presentation and Communication 

### ISSUE THREAD

**Issue by SkyAudit** [skycoin/skycoin#359]
-Work in progress

**Comment by skycoin-main** [comment]
> https://bitcointalk.org/index.php?topic=380441.msg4092232#msg4092232

LOL. I have no idea who wrote this.

**Comment by skycoin-main** [comment]
>and repair Skycoin's damaged reputation 

Skycoin never had a "damaged reputation". You are talking about people who are too stupid to be able to read the white papers.

These people buy at the top and sell at the bottom every time and are have no idea what they are even buying. They only lose money, are unable to operate the equipment or write the software needed to achieve an effect in the world and are a liability, not an asset.

The majority of the altcoin speculators are absolutely toxic. It is an emotion driven, sentiment driven market with no fundamentals and where majority have no idea what they are even buying.

We are trying to improve the communication on the Skycoin website about what Skycoin is, but we are not ready to market to the CatCoin and lowest denominator crowd yet.
