### ISSUE TITLE
Display logs in the wallet UI

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#368]
The backend should expose logging to the client so that it can display it in a tab in the UI

**Comment by iketheadore** [comment]
If we want to have enough info for debugging the wallet, the frontend console logs also need to be shown in the tab. And we now have backend log in files.

**Comment by gz-c** [comment]
#625 implements the API to expose the backend logs

**Comment by gz-c** [comment]
The API in #625 was removed due to a crash. This issue is pending #364

**Comment by gz-c** [comment]
Not implementing
