### ISSUE TITLE
secp256k1-go2 tests should pass

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#402]
The tests in `cipher/secp256k1-go/secp256k1-go2` do not pass

**Comment by iketheadore** [comment]
I test the code, it panic in `ParsePubkey` method. 
![image](https://user-images.githubusercontent.com/2589926/27726463-30eddfcc-5dad-11e7-9d21-ece761fb2429.png)

The `pub` length must be 33 bytes, while the test `pubkey` is 65 bytes.

**Comment by gz-c** [comment]
There are the same failures in TestSignature, but even if you fix those, there are more failures afterwards, and those are not panics.

**Comment by iketheadore** [comment]
Hmm yes, @skycoin-main what should we do for that.
