### ISSUE TITLE
Add an API page in explorer

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#408]
Add an api page in explorer to describe the supported apis and usage.

**Comment by xano8437** [comment]
Just to clarify, you mean the explorer at explorer.skycoin.net? Guess I could add an API page based on the explorer.go file, or does someone have more extensive documentation?

**Comment by gz-c** [comment]
We should move these issues into the new repo, https://github.com/skycoin/skycoin-explorer

**Comment by iketheadore** [comment]
Oh, Just saw the explorer is separated into another repo.

**Comment by gz-c** [comment]
https://explorer.skycoin.net/api.html
