### ISSUE TITLE
Add indicator for whether a wallet has unconfirmed pending transactions

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#409]
Use api `/pendingTxs` to get the pending transaction.

**Comment by vyloy** [comment]
Could you tell me more details about the UI requirements?

**Comment by iketheadore** [comment]
Leave this issue till the redesign of wallet UX

**Comment by gz-c** [comment]
@samuelvisscher is this done?

**Comment by samuelvisscher** [comment]
No, but will pick it up

**Comment by mahansky** [comment]
Where should it be displayed? When/How should it be updated?

Maybe a small badge with number near the gear icon in the header and next to the "Pending Transactions" in the dropdown?

**Comment by samuelvisscher** [comment]
Probably you will want to look at the current error reporting in the header, and make this much more abstract

**Comment by gz-c** [comment]
@mahansky for new design changes, try to work off the existing one, otherwise up to you
