### ISSUE TITLE
Speed up the wallet loading time

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#410]
Usually it takes about 3~5 seconds in the following `loading` status, we must speed up the loading process and have a better user experience.

![image](https://user-images.githubusercontent.com/2589926/27759407-e244dcca-5e62-11e7-9238-558d21a5dd01.png)

**Comment by SkyAudit** [comment]
I also find that it takes even longer for your wallet balance to show up. For me, it says 0 Sky for a few minutes and then it updates with my current balance. Almost had a heart attack.

**Comment by xano8437** [comment]
https://github.com/skycoin/skycoin/pull/469 introduces speed improvements and https://github.com/skycoin/skycoin/pull/478 provides feedback on blockchain loading. Can be closed I believe.

**Comment by gz-c** [comment]
Yes seems responsive now
