### ISSUE TITLE
total received and total sent in blockchain explorer page is empty

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#418]
![image](https://user-images.githubusercontent.com/2589926/27787885-fee6fa40-6018-11e7-9825-2edc8fe31479.png)

![image](https://user-images.githubusercontent.com/2589926/27787915-1957ed94-6019-11e7-96a9-a8a58ab235b6.png)

![image](https://user-images.githubusercontent.com/2589926/27787826-cb1aad42-6018-11e7-82c6-9c2d9735d401.png)

**Comment by gz-c** [comment]
Is this in the wallet or the explorer?

**Comment by iketheadore** [comment]
we will remove it from wallet, so no need to fix this.
