### ISSUE TITLE
[V19 UI Send Screen]Default value of Wallet field at Send screen is wrong.

### ISSUE THREAD

**Issue by candyYMMA** [skycoin/skycoin#445]
Scenario:
Open skycoin Send tab.
No send activity was performed yet.
take a look at wallet field

Expected:
Value in DDL as default should be "select wallet" so user will know that in this field he should choose from which wallet to send skycoins.

Actual:
Undefined(All) - 0SKY appears.
When opening the DDL youcan only see the "Select Wallet".
user should see at at first and not when open the DDL or "Select Wallet" should be removed from the DDL.

[Link demonstracting the issue](https://ibb.co/hDvLpa)

**Comment by iketheadore** [comment]
Thanks

btw, can upload image directly here
