### ISSUE TITLE
[V19 UI Send Screen]Wallet question mark sign image

### ISSUE THREAD

**Issue by candyYMMA** [skycoin/skycoin#446]
Scenario:
Open skycoin Send tab.
No send activity was performed yet.
Take a look at [wallet field](https://ibb.co/kHLZhv)

Expected:
1. Sign appear in the correct location
2. Near wallet field there is a sign of ? , a balloon with explanation should appear when user does mouse hove on it. 

Actual:
1. I would think the sign should be to the right of wallet or right side of the field([thats how usually it is done](https://www.google.co.il/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjCkJ_z-YvVAhWRSxoKHbniCJsQjRwIBw&url=https%3A%2F%2Fux.stackexchange.com%2Fquestions%2F53148%2Fhaving-an-icon-to-replace-forgotten-username-and-password&psig=AFQjCNEP63pVrRjNShWAJZypQYCgkuyK9w&ust=1500230922243219))
2. Nothing appears when doing mouse hover on the sign.

**Comment by xano8437** [comment]
Question mark has been removed in:

https://github.com/skycoin/skycoin/issues/456

Please let me know if new question mark should be added, and if so what the tooltip should contain.

**Comment by gz-c** [comment]
Closing this, a decision on tooltips can be made during UX improvements
