### ISSUE TITLE
[V19 History Screen]address isn't getting searched

### ISSUE THREAD

**Issue by candyYMMA** [skycoin/skycoin#449]
Scenario:
Perform some sending and receiving activities.
Open skycoin History tab.
Put the address you last got money from
Hit Search button

Expected:
History appears filtered - only transactions with FROM OR TO of the input address appears.

Actual:
The History displayed exactly as before with no filter.
Search isnt working for address 
![hist_tab](https://user-images.githubusercontent.com/28111034/28251055-fa7242c0-6a7d-11e7-895f-75b2586dc3a0.png)
After Searching:
![hist_after_hit_search](https://user-images.githubusercontent.com/28111034/28251068-3ac724a8-6a7e-11e7-8890-243c8849b2ab.png)

**Comment by iketheadore** [comment]
Yes, the search function has broken for a long time.

**Comment by xano8437** [comment]
Can be closed since search bar is removed. If search bar should be re-introduced, please open new request
