### ISSUE TITLE
[V19 History Screen]Wallets balance does not appear the same as Amount in History tab

### ISSUE THREAD

**Issue by candyYMMA** [skycoin/skycoin#451]
Scenario:
Perform one send of 5 coins from A to B.(trx X)
Open skycoin wallets tab.
Check your B Wallet balance.(should be 5)
Compare the balance to the History Amount tab on trx X

Expected:
Amount value in History appears same as in Wallets  tab inside wallet- when expanded.

Actual:
Amount value in History appears not same as in Wallets tab inside wallet- when expanded. 
As can be seen here is 5 coins:
![image](https://user-images.githubusercontent.com/28111034/28387096-684eeae6-6cd6-11e7-8bc3-4752a1776b03.png)

Amount in History is 6:
![image](https://user-images.githubusercontent.com/28111034/28387314-33c7475e-6cd7-11e7-9ff3-65946501e53a.png)

**Comment by xano8437** [comment]
Does not appear to be present anymore with new wallet design
