### ISSUE TITLE
Can't open web in browser because load js resources  404

### ISSUE THREAD

**Issue by zhiyuan2007** [skycoin/skycoin#453]
1. code is newest, but when execute ./run.sh , open browser default ,but can not load all js resource , url is http://127.0.0.1:6420/
2. my env is mac pro sierra ,version is 10.12.5
3. anyone know the reason?
![wechatimg9](https://user-images.githubusercontent.com/897759/28416315-2378cf8e-6d19-11e7-864d-a1165f12baa1.jpeg)

**Comment by iketheadore** [comment]
The default branch is develop, you need to build static file before run the wallet, please checkout to master branch, and run ./run.sh, it should work.

**Comment by zhiyuan2007** [comment]
yes,  it works after build static file using following commands :
npm install
gulp build

thanks

**Comment by gz-c** [comment]
add these instructions to readme if not there
