### ISSUE TITLE
skycoin icon of wallet is different from the website

### ISSUE THREAD

**Issue by hanyh2004** [skycoin/skycoin#454]
which is right ?

**Comment by gz-c** [comment]
website is right

**Comment by hanyh2004** [comment]
https://github.com/skycoin/skycoin/blob/develop/electron/build/icon.icns.  The icon is right.but the latest release  is wrong.
![2017-07-21 20 30 54](https://user-images.githubusercontent.com/213808/28463548-8a9c9070-6e53-11e7-8540-fd71066439e1.jpg)

**Comment by xano8437** [comment]
Anything that needs to be done for this, besides building new release?

**Comment by gz-c** [comment]
i dont know why it didnt end up in the release, @iketheadore will this be fine?

we need instructions for doing release then we can check

**Comment by iketheadore** [comment]
The icon was update after the v19 released, we don't need to do anything else except building a new release.

**Comment by gz-c** [comment]
Fixed by #581

**Comment by gz-c** [comment]
The `icns` file wasn't fully updated, the one in `assets/osx` was still the old one and affected the `dmg` installer view in the image above.  But is fine now
