### ISSUE TITLE
[V19 Backup Wallets]Wallets name when undefined label appears empty

### ISSUE THREAD

**Issue by candyYMMA** [skycoin/skycoin#456]
Scenario:
Create new wallet and rename it to "Test".
Create another wallet.
Go to Wallet backup under the icon of Setting.

Expected:
First wallet "Test" label appears.
Wallet with Name undefined appears with the label " undefined"

Actual:
Label value is missing - it is just empty.
![image](https://user-images.githubusercontent.com/28111034/28657470-faa23414-72af-11e7-9dd7-c85bb7c8a650.png)

**Comment by xano8437** [comment]
Solved by https://github.com/skycoin/skycoin/pull/469
