### ISSUE TITLE
[V19 wallet coin_transfers]transfer between addresses in the same wallet doesn't show proper receiving address

### ISSUE THREAD

**Issue by candyYMMA** [skycoin/skycoin#457]
Platform:
Linux (Ubuntu 16.4)

Scenario:
Perform one send 1 coin from Addr A to Addr B within the same wallet.(trx X).
send 
from: 2Fbg..
to: 2816..
Check the trx in skycoin send tab.
Open skycoin wallets tab , check from and to are correct addresses.
Open skycoin history tab , check from and to are correct addresses.

Expected:
Send screen - address should appear as the destination address.
Wallets screen - coins should appear under address B balance.
History tab - address should appear as the destination address

Actual:
Send screen - adress appear as the sender/wallet's first address.
Wallets screen - there is no change in the wallets coins balance.
History tab - to and from are the same value - sender

**Wallets Screen:**
![image](https://user-images.githubusercontent.com/28111034/28724430-a30680d4-73c2-11e7-8da9-ba364f65d517.png)

**Send Screen:**
![image](https://user-images.githubusercontent.com/28111034/28724891-4ff13892-73c4-11e7-9301-66e506d2cda0.png)

**History Screen:**
![image](https://user-images.githubusercontent.com/28111034/28725180-617d9794-73c5-11e7-8619-21e1606199fe.png)

**Comment by xano8437** [comment]
Due to new UI not visible anymore, can be closed
