### ISSUE TITLE
[V19 Security Load_wallet]load wallet from non-existing seed

### ISSUE THREAD

**Issue by candyYMMA** [skycoin/skycoin#458]
Platform:
Windows 7(64 bit)

Scenario:
Click on Load wallet from Seed.
Insert Wallet's Name
Insert Wallet's Seed - a new non valid name.
Press Ok
Try opening the wallet created in another machine

Expected:
Error message should appear on the screen - "The seed you entered doesn't exists, please enter Valid seed".
Wallet should not be loaded or created at all.

Actual:
New wallet created with the given NON VALID seed.
Was able to open it on another Skycoin wallets app(on Linux)

**Wallets Screen:**
![image](https://user-images.githubusercontent.com/28111034/28749293-04e456b0-74cb-11e7-96ab-aae795db73fe.png)

**BackUp Wallets Screen**
![image](https://user-images.githubusercontent.com/28111034/28749274-91d85234-74ca-11e7-920a-573731372bb0.png)

**Comment by iketheadore** [comment]
The seed can be any string,  what's mean of NON VALID seed.

**Comment by xano8437** [comment]
If an API exists that tests if a wallet already exists (not possible I assume) / if an address already has a balance, we could already add the amount of addresses we are sure that should exist. I would rather close this and add a feature request for importing an existing wallet.

**Comment by xano8437** [comment]
Synth on Telegram:

> Yes. you have to scan for "gaps". Which is unused wallet addresses in between used wallet addresses and have max gap length of 4... but gets complicated for receiving addresses that are allocated but then not used.
> 
> And it means wallet gen cannot work well without blockchain loaded.

I assume this should be done by back-end. If so, I suggest that this is done whenever creating a wallet from a seed.

**Comment by gz-c** [comment]
I think Synth's reply was also directed towards the "send change output to new address" suggestion

**Comment by candyYMMA** [comment]
I meant non valid values - 1,2,3 (length is too short , should be 12 words, no?)
or something like ^%#^%"&''""
