### ISSUE TITLE
gnet default port 6000 is reserved on linux,wallet on linux desktop can't work

### ISSUE THREAD

**Issue by hanyh2004** [skycoin/skycoin#461]
see /etc/services  
 x11             6000/tcp        X               # the X Window System   

 skycoin  uses port 6000 as defualt port:

> //gnet uses this for TCP incoming and outgoing
>Port: 6000,

so the wallet on the linux desktop maybe not work properly

**Comment by gz-c** [comment]
6555 seems like good alternative choice

**Comment by gz-c** [comment]
@iketheadore do you think it is safe to change the default port?

**Comment by gz-c** [comment]
We should change it if it we can, however the peer lists will all become outdated.

If we change the port, then the default sync nodes will change their port on deployment.  Users with older clients will not be able to connect to them until they upgrade to get the new default peer list, which will cause reliability issues.  We can force the default sync node to keep binding to 6000, and then there won't be this problem. If we want to migrate, we can have half of them bind to 6000 and the other half bind to the new port, and on the next release, switch them all to the new port.

Most other clients are unreachable on their listen port so it doesn't really matter for them.

The peers.txt file will need updating from all of the people listed there. We should probably add notes to the peers.txt file to keep track of who owns which server. We could find it from the git history for now instead. We could contact them to upgrade their nodes and then we could update the port.

**Comment by gz-c** [comment]
Not changing this; port 6000 is not used on linux in practice, and anyone who is using linux should have the ability to use the `-port` flag
