### ISSUE TITLE
[V19 settings Wallets backup ]Wallets Directory path is incorrect on windows

### ISSUE THREAD

**Issue by candyYMMA** [skycoin/skycoin#467]
Create  wallet
Click on Settings icon
Click on Backup wallets

Expected:
Wallets Directory path is correct

Actual:
Wallets Directory path is correct on windows platform
Path looks like: C:\Users\User/.skycoin/wallets
while should be: C:\Users\User\.skycoin\wallets
![image](https://user-images.githubusercontent.com/28111034/29465413-e605e188-8441-11e7-8413-c41f640280b4.png)

**Comment by gz-c** [comment]
Maybe we should use this lib, https://github.com/mitchellh/go-homedir, does the home directory thing cross-platform without cgo

**Comment by gz-c** [comment]
@iketheadore is this fixed?

**Comment by iketheadore** [comment]
Fixed
