### ISSUE TITLE
[Linux] desktop file is lacking a Categories= entry

### ISSUE THREAD

**Issue by probonopd** [skycoin/skycoin#468]
The desktop file inside http://downloads.skycoin.net/wallet/skycoin-0.19.0-gui-linux-x64.AppImage is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).

Reference: https://github.com/AppImage/AppImageHub/issues/2

**Comment by probonopd** [comment]
Is this fixed in the latest available download, http://downloads.skycoin.net/wallet/skycoin-0.19.0-gui-linux-x64.AppImage? If not, please ping me once there is a new one so that I can repeat the test and add the AppImage to the AppImageHub central directory of available AppImages. Thanks!

**Comment by gz-c** [comment]
This is the new release, will be publishing it on the website shortly
https://downloads.skycoin.net/wallet/skycoin-0.20.2-gui-linux-x64.AppImage

**Comment by probonopd** [comment]
Could it be that it refuses to launch if there is no Internet connectivity?
https://travis-ci.org/AppImage/appimage.github.io/builds/287143771#L753

**Comment by gz-c** [comment]
It appears to have launched
https://travis-ci.org/AppImage/appimage.github.io/builds/287143771#L745

I can't think of a reason why it wouldn't launch without internet connectivity, but I don't have a linux desktop available to check.

When electron is started, it runs a the application (a separate binary) as a child process. This process exposes an http interface on localhost. The frontend javascript application runs as a webpage in electron, and makes API requests to localhost for state.

Is it possible that this initialization method does not cooperate with the test runner?

**Comment by gz-c** [comment]
https://travis-ci.org/AppImage/appimage.github.io/jobs/287143773#L687-L692
