### ISSUE TITLE
README cleanup

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#473]
- [x] gvm is not necessary anymore
- [x] make sure vendor instructions are clear
- [ ] make sure build instructions are clear
- [x] make webrpc, api docs more visible
- [ ] make sure no mistakes in docs
- [x] make sure webrpc docs are up to date
- [x] make sure api docs are up to date

**Comment by iketheadore** [comment]
gvm is used to install go, so we don't need to tell instructions of how to install go?

**Comment by gz-c** [comment]
gvm is unnecessary, homebrew is fine on osx, there are other options per platform
there are enough instructions elsewhere on installing go, we shouldnt repeat it here, maybe have a wiki page if we get asked a lot, but i dont think installing go is a problem for people anymore

**Comment by iketheadore** [comment]
alright

**Comment by gz-c** [comment]
Removed from milestone 0.20 because this is an ongoing task
