### ISSUE TITLE
Wallet Encryption

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#479]
Need to specify how we will do wallet encryption first.

**Comment by xano8437** [comment]
From the front-end wallet point-of-view I would need to know from GET /wallets which wallets are locked (probably by not receiving seed etc.), and could then require a password parameter for POST /wallet/spend.

**Comment by iketheadore** [comment]
Wallet encryption:
1. Split data into 256 bits(32 bytes) blocks (pad to 32 bytes with nulls at end)
2. Each block is encrypted by XORing the unencrypted block with SHA256(SHA256(password), SHA256(index, SHA256(nonce))
    - index is 256 bit number, and is 0 for the first block of 32 bytes, 1 for the second block of 32 bytes, 2 for third block
3. Combine those encrypted blocks in hex with comma, SHA256 nonce with it as checksum for error detection.
4. Use base64 encoded  <checksum(32 bytes)><nonce(32 bytes)><comma separated blocks in hex> as the finally encrypted string

**Comment by gz-c** [comment]
On final stages of this, remaining issues will be handled separately
