### ISSUE TITLE
Offline transaction signing

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#481]
This is needed for exchange integration

**Comment by xano8437** [comment]
For when is this expected? Would be great for the browser wallet also

**Comment by gz-c** [comment]
Have it marked for 0.20 milestone because it is important for exchange integration.  But we need to implement a general offline mode, that disables the blockchain sync

**Comment by gz-c** [comment]
Moving this to 0.21 so we can focus on 0.20 release.

**Comment by xano8437** [comment]
I have this one in the liteclient, maybe better to wait until I release that before starting on this one

**Comment by gz-c** [comment]
CLI's create rawtx will sign the transaction locally from a local wallet file, but still needs to call GetUnspentOutputs from a skycoin daemon.  Maybe this is sufficient.

To make this fully offline, one would need to implement a blockchain loader in their code.  This is already possible for golang apps, they can import the blockchain loader library and load it (maybe it needs some minor refactoring to allow this).  For other languages, they would need to implement that themselves, load the unspent outputs from the database file. And it would not be up to date.
