### ISSUE TITLE
[V20 Wallet] Add address doesn't work

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#490]
![image](https://user-images.githubusercontent.com/2589926/29695903-01abbbac-8978-11e7-8a82-598bd9a56781.png)

**Comment by xano8437** [comment]
Could not reproduce this myself, could you provide some additional info?

- Commit hash?
- Client (Electron, 127.0.0.1:6420 or dev server)?
- Reproduction steps?

**Comment by iketheadore** [comment]
* Commit: 0efc8cdaef9fed04b1f56e81ddc735fa655d4e3a
* Client 127.0.0.1:6420
* Platform: osx

Run ./run.sh in the root of the project, click add address in exist wallet will show the -loading..., the new address api is ok, it returns the address successfully.
