### ISSUE TITLE
[skycoin.gui:ERROR] Get balance failed: get unconfirmed spending failed when checking addresses balance

### ISSUE THREAD

**Issue by xano8437** [skycoin/skycoin#494]
When I check-out the latest version from dev I get the following error on /balance?addrs=xxx requests:

[skycoin.gui:ERROR] Get balance failed: get unconfirmed spending failed when checking addresses balance: get unconfirmed spend error:unconfirmed transaction's IN: [SOMEREFERENCE] is not in unspent pool

Address: http://127.0.0.1:6420
Git commit: 45f48541244bd8b2e1e1ccdf743f935db8669a47
OS: Windows 10

**Comment by xano8437** [comment]
After deleting data.db the problem is gone

**Comment by gz-c** [comment]
did you save copy of the bad db?
