### ISSUE TITLE
Change output should go to a new address

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#498]
Change generated from a transaction should go to a new deterministically-generated address in the wallet by default

**Comment by iketheadore** [comment]
If generate new address for changing by default, user might find all coins in the from address are gone, he need to refresh the wallet to load the new generated address in gui.

**Comment by xano8437** [comment]
I can renew addresses and balances after complete of send transaction in the front-end; refreshing should be no problem

**Comment by gz-c** [comment]
We can't do this until we do address scanning in the wallet

**Comment by gz-c** [comment]
This will need #2130 (HD Wallet support) to do best, although we may be able to do it without Bip44. Either way it causes some core UI/UX changes, which are probably best resolved together with the changes need for a BIP44 wallet.
