### ISSUE TITLE
Verify signatures failed when node start

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#509]
The following error might occur when node upgrade from 0.18.0 to 0.19.0+,
```
[skycoin.main:ERROR] Invalid block signatures: Verify signature of block in depth: 
2708 failed: no sig for <SIG>
```
To fix this issue, we need to parse the block again to fill the lost signature when node start.

**Comment by gz-c** [comment]
#512 fixes as much as it can be fixed

@iketheadore is it possible to detect when the data.db is corrupted and recreate it automatically?

**Comment by iketheadore** [comment]
We can check and recreate the data.db if it's corrupted, but need to do this before other modules are loaded.

**Comment by gz-c** [comment]
Might be important for next release, we still have people complaining about the error and they dont understand data.db deletion / hidden folder and might delete their wallet files too on accident
