### ISSUE TITLE
Replace "hours" with "coin hours" in the UI

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#526]
<img width="239" alt="screen shot 2017-09-15 at 11 40 11 am" src="https://user-images.githubusercontent.com/26845312/30465711-468320aa-9a0b-11e7-9189-18acb0544542.png">
<img width="141" alt="screen shot 2017-09-15 at 11 40 17 am" src="https://user-images.githubusercontent.com/26845312/30466051-a6dbea5c-9a0d-11e7-865b-15d73f320f20.png">

**Comment by montycrypto** [comment]
Can be closed due to #511
