### ISSUE TITLE
"Recent transactions" does not refresh if page open for a while

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#527]
When i leave the wallet UI open in the browser, after a while, when I send skycoin the recent transactions panel does not refresh.

<img width="832" alt="screen shot 2017-09-15 at 1 03 19 pm" src="https://user-images.githubusercontent.com/26845312/30467302-51124874-9a16-11e7-86a2-c67ec3b54088.png">

Is it possible that the background refresh gives up after a while?

Maybe this happens if i shutdown the skycoin node in the terminal for a bit, then restart it, but don't refresh the UI web page.

**Comment by montycrypto** [comment]
Left the UI open for an hour and could not reproduce. Might it be that the node turned off?

**Comment by gz-c** [comment]
I think the steps are:

**Comment by montycrypto** [comment]
Could fix this by locking the screen once the node is turned of, something along the lines of "Cannot connect with Skycoin, please (re)start the client." Sounds good?

**Comment by gz-c** [comment]
You can't renew the failure countdown on user activity?
