### ISSUE TITLE
Decide to use number or string for json "coins", "hours" values

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#539]
Javascript uses doubles for numbers parsed from json which have a max representable integer value of 9,007,199,254,740,992.

Given 6 decimal places for droplets, that means the max coin value is 9,007,199,254.  This is high enough for skycoin but maybe not for skyledger coins.  Also, if a higher number of decimal places was desired, the maximum would be even less.

Coin hours are measured in whole coins so should never reach the cap.

Using integers is probably fine, either way we must use the same type in all APIs, e.g.

https://github.com/skycoin/skycoin/blob/develop/cmd/cli/README.md#get-transaction
this uses string for "coins"

https://github.com/skycoin/skycoin/blob/develop/cmd/cli/README.md#check-address-balance
this uses int for "amount" (coins)

**Comment by jgh-** [comment]
Monetary numbers should be fixed-point integers.  If JavaScript uses double for json it's probably better to use a string representation and convert to integer.  Floating point can lead to unexpected results, which I don't think would be desirable for an application dealing with money.

**Comment by gz-c** [comment]
Will be using strings for everything
