### ISSUE TITLE
Sometimes balance does not "regenerate" properly after update.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skycoin#591]
**Shino Go, [14.10.17 20:01]**
My friend installed the new Skycoin wallet on mac. His wallet became "0". I'm assuming it's probably because he skipped a wallet version?

Maybe we need an option in wallet to reset all data?

**Steve, [14.10.17 20:03]**
we need more information on the "0" issue

**Steve, [14.10.17 20:03]**
if the db is corrupt its supposed to automatically rebuild it

**Steve, [14.10.17 20:07]**
cd /Applications/Skycoin.app/Contents/MacOS
./Skycoin > ~/Desktop/skycoin-log.txt

**Steve, [14.10.17 20:07]**
tell him to do that in terminal, wait for the app to start, quit the application, then send the ~/Desktop/skycoin-log.txt file

**Comment by montycrypto** [comment]
Also heard 2 other complaints about this. Syncing stops at any random block (heard of cases 117-2600). After deleting data.db it retries syncing, but always broke again at any other random block.

**Comment by gz-c** [comment]
I think this was fixed with 0.20.3
If anyone still has problems, tell them to delete data.db from ~/.skycoin
