### ISSUE TITLE
Add option for external API

### ISSUE THREAD

**Issue by montycrypto** [skycoin/skycoin#598]
For the mobile wallet, web wallet and various other future implementations (exchanges for example), I would like to request an external API flag. When this is set to true, the node will expose (at the very least) the injectTransaction and outputs REST endpoints at a yet-to-be-determined port. This would allow any interested parties to simply run a reverse proxy through nginx to create their own back-end. Currently we need to run a custom Go/NodeJS script for this.

**Comment by gz-c** [comment]
```
  -web-interface-addr string
    	addr to serve web interface on (default "127.0.0.1")
  -web-interface-cert string
    	cert.pem file for web interface HTTPS. If not provided, will use cert.pem in -data-directory
  -web-interface-https
    	enable HTTPS for web interface
  -web-interface-key string
    	key.pem file for web interface HTTPS. If not provided, will use key.pem in -data-directory
  -web-interface-port int
    	port to serve web interface on (default 6420)
```

These options don't work?

**Comment by montycrypto** [comment]
I would assume that the web interface also include wallet functions, which I would need to be specifically excluded. Or does it only include stateless methods?

**Comment by gz-c** [comment]
We can add options to disable sets of functions.  Although if you aren't loading a wallet it doesn't matter

**Comment by gz-c** [comment]
#648
