### ISSUE TITLE
Allow multiple addresses for GET /explorer/address

### ISSUE THREAD

**Issue by montycrypto** [skycoin/skycoin#599]
From the web client and mobile clients I will want to retrieve a list of related transactions. Currently I have to make a large number of requests for this. Optimally I could pass multiple addresses as argument, similar to how GET /outputs works

**Comment by gz-c** [comment]
May include part of this in the #420 API Cleanup [probably rename /explorer/address to something else]

**Comment by iketheadore** [comment]
I will add a new api `/transactions?addrs=$addrs` for this, the `/explorer/address` is using by the explorer, change it would break the explorer I think.

**Comment by samuelvisscher** [comment]
@iketheadore @therealssj @gz-c this has been a problem for quite a while, can someone look at this?

**Comment by therealssj** [comment]
Add this to 0.23?

**Comment by iketheadore** [comment]
It's already fixed in `/transctions?addrs=` endpoint.

**Comment by gz-c** [comment]
@iketheadore can you update the changelog with this

**Comment by iketheadore** [comment]
yes, I will create a PR to update the changelog.

**Comment by gz-c** [comment]
`/wallet/transactions` is only for a specified wallet file.  This does not satisfy the need
