### ISSUE TITLE
Refactor gui http interface into a struct

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#631]
The gui http interface still uses some global vars,
the package should expose a configurable struct,
and provide a proper shutdown mechanism

**Comment by Vavilen** [comment]
@gz-c , could you give me more details about this issue?
Which global vars do you mean? Just for example.

**Comment by gz-c** [comment]
The logger can stay as a global

The `Launch*` methods should not call `serve()`

The `Shutdown()` method should be a struct method

The caller (in `cmd/skycoin/skycoin.go`) should do something like:

```go
s := Create()
...
go s.Serve()
....
s.Shutdown()
```

And in the `go s.Serve()` goroutine, manage it with a `sync.WaitGroup` (you will see other goroutines do this, e.g. `wg.Add(1)`)

**Comment by Vavilen** [comment]
@gz-c , please, look at my PR: [#727](https://github.com/skycoin/skycoin/pull/727)

**Comment by gz-c** [comment]
#791
