### ISSUE TITLE
Test /wallet/spend

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#636]

**Comment by Vavilen** [comment]
@gz-c , I think the test covers this case: https://github.com/skycoin/skycoin/blob/41be95959901370b6fd7766b2c7c5a978c5476c3/src/wallet/service_test.go#L573

**Comment by gz-c** [comment]
@Vavilen that covers the real spending logic but doesn't test the handler itself, to check the query arguments processing.

**Comment by Vavilen** [comment]
@gz-c so, is it a test for HTTP handler not the CreateAndSignTransaction function exactly as and others /wallet/* tests?

**Comment by gz-c** [comment]
Yes, only the http handlers, the wallet package will test its own methods.

We may need to use an interface for `Gateway` to do this testing easier

**Comment by Vavilen** [comment]
@gz-c , please, assign this issue to me.
