### ISSUE TITLE
Connection Pool Rules: Fix full connection pool catch 22

### ISSUE THREAD

**Issue by skycoin-manager** [skycoin/skycoin#652]
- nodes use peer-exchange to get list of servers
- if connection pool of the default peers is full, then peer will be disconnected before receiving node list
- therefore the node will never reach peers with and will be unable to download the blockchain

Add
- skycoin.net/peers.txt

Have node on startup, download skycoin.net/peers.txt
- add peers to peer list, to bootstrap
- add command line option in networking tab to disable "fetch bootstrap peers from skycoin.net"
- add checkbox in settings for disable "fetch bootstrap peers from skycoin.net"

- Disabled by default in source
- enabled by default in distributed/skycoin (windows installation)

**Comment by gz-c** [comment]
The requirements listed here have been converted to other issues, see #672 #673 #674

>add checkbox in settings for disable "fetch bootstrap peers from skycoin.net"
This issue requires a lot more work starting with #675, do not do this step yet.
