### ISSUE TITLE
Connection Pool: Connection Pool Size

### ISSUE THREAD

**Issue by skycoin-manager** [skycoin/skycoin#653]
Increase connection pool size (double to 32 or 64)

**Comment by gz-c** [comment]
This should be a configurable option if it is not

**Comment by Vavilen** [comment]
It looks like MaxConnections parameter changing does not give any effect.
The connections count increase without any control even if I pass the parameter here
https://github.com/skycoin/skycoin/blob/1fec1f06083f8046e9b66f17501d44b5629a490a/src/daemon/gnet/pool.go#L278
The connections counter just increments and nothing more.
Am I right?

**Comment by gz-c** [comment]
How many connections are there?

**Comment by gz-c** [comment]
When you run it, `MaxConnections` is set to 16, see cmd/skycoin/skycoin.go

**Comment by Vavilen** [comment]
Here [click](https://github.com/skycoin/skycoin/blob/29974b4a517efdf976efe9432caa49b2d55b432e/src/daemon/gnet/pool.go#L93) we can see 128 connections, but the parameter is never used, if I`m not mistaken.

**Comment by Vavilen** [comment]
I made changeable the MaxConnections param from cmd/skycoin/skycoin.go and passed as an config field into the daemon/gnet/pool.go, but it cannot limit the connections count.

**Comment by iketheadore** [comment]
The peerlist max size is managed here: https://github.com/skycoin/skycoin/blob/develop/src/daemon/pex/pex.go#L139:2

**Comment by gz-c** [comment]
#709
