### ISSUE TITLE
Timer/Instrumentation

### ISSUE THREAD

**Issue by skycoin-manager** [skycoin/skycoin#655]
1> Add timer for main loop. Measure times between when main loop exits sleep and finishes execution
- print message if more than 200 ms passes between start and finish of main loop

2> Add timer in the networking loop
- measure time between calls to update/dispatch of networking messages
- print message if more than 500 ms passes between updates

**Comment by gz-c** [comment]
What is the main loop?

**Comment by gz-c** [comment]
Split up to #659, #660

**Comment by Ch3ck** [comment]
Hello, @gz-c I'm interested in working on this project. I submitted a PR for a readme url fix. I'll tak a look at the issues.
