### ISSUE TITLE
Implement string and byte array encryption function

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#663]
Wallet encryption:

Split data into 256 bits(32 bytes) blocks (pad to 32 bytes with nulls at end)

Each block is encrypted by XORing the unencrypted block with SHA256(SHA256(password), SHA256(index, SHA256(nonce))

index is 256 bit number, and is 0 for the first block of 32 bytes, 1 for the second block of 32 bytes, 2 for third block

Combine those encrypted blocks in hex with comma, SHA256 nonce with it as checksum for error detection.

Use base64 encoded  <checksum(32 bytes)><nonce(32 bytes)> as the finally encrypted string

**Comment by iketheadore** [comment]
Add length prefix to indicate the unencrypted data length.

Xor gives result even the password is not correct, so we need to add hash of the unencrypted data to do verification. 

So the data will be <length prefix(4 bytes)><data hash(4 bytes)><data>, and then encrypt the whole data.

**Comment by amltoken** [comment]
Only encrypt []byte, do not use strings for encryption ops.

**Comment by gz-c** [comment]
#698
