### ISSUE TITLE
Save peer list failed

### ISSUE THREAD

**Issue by montycrypto** [skycoin/skycoin#682]
When I run `bash run.sh` on Windows using the latest dev commit, I receive the following error:

2017/11/28 11:24:39 save peer list failed: rename C:\Users\Sam\.skycoin\peers.txt C:\Users\Sam\.skycoin\peers.txt.bak: The process cannot access the file because it is being used by another process.

If I manually delete peers.txt.bak it starts up once fine, next time error occurs again.

OS: Windows 10

**Comment by gz-c** [comment]
Is another process using it?

**Comment by montycrypto** [comment]
No, the error persists after rebooting the computer
