### ISSUE TITLE
Remove old/outdated peers from peerlist when full

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#710]
When the peerlist fills and we want to add more new peers, remove the oldest LastSeen peers to make room.

Only remove peers if they are older than some amount (different from the current old peer expiration, maybe 8 hours, instead of 1 week).

**Comment by stdevHan** [comment]
@gz-c how can i know old age of the `peer` by the `LastSeen`

**Comment by olemis** [comment]
@stdevHan @stdevHan isn't this already done somewhere in the code base ? Find the locations in code where LastSeen is used .

**Comment by gz-c** [comment]
`AddPeer()` will call `findOldestUntrustedPeer()` for removal, if that peer is at least older than a certain amount of time (currently 1 day)
