### ISSUE TITLE
Add linters from golangci-linter

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#718]
List of linters:
https://github.com/golangci/golangci-lint#supported-linters

Need to add them one by one, from the default list:

Create a new issue for each linter before working on it.

- [x] govet
- [x] errcheck
- [x] staticcheck
- [x] unused
- [x] gosimple
- [x] structcheck
- [x] varcheck
- [x] ineffassign
- [x] deadcode
- [x] typecheck
- [x] golint
- [x] gas
- [ ] ~~interfacer~~ [willfully ignoring]
- [ ] ~~unconvert~~ [willfully ignoring]
- [ ] ~~dupl~~ [willfully ignoring]
- [ ] ~~goconst~~ [willfully ignoring]
- [ ] ~~gocyclo~~ [willfully ignoring]
- [ ] ~~gofmt~~ [superseded by goimports]
- [x] goimports
- [ ] ~~maligned~~ [willfully ignoring]
- [x] megacheck
- [ ] depguard (could be useful for blacklisting github.com/pkg/errors, but requires golangcli-lint to use a config file)
- [x] misspell
- [ ] ~~lll~~ [willfully ignoring]
- [x] unparam
- [x] nakedret
- [ ] ~~prealloc~~ [willfully ignoring]

**Comment by Vavilen** [comment]
@gz-c Can I use config file to add settings?
https://github.com/alecthomas/gometalinter#configuration-file
Or do I need to add the linters separately in the Makefile?

**Comment by gz-c** [comment]
@Vavilen add them to makefile for now
