### ISSUE TITLE
Handle trailing newline in create wallet's seed text box

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#725]
If pasting a seed copied from a text file, it may have a newline appended.

The create wallet's seed input box is a textarea and not an `<input>`.  Pasting into an `<input>` would trim/ignore the trailing whitespace, but pasting into a textarea does not trim it.

Decide how to handle this, options include:

* Show a warning to the user if they have a trailing newline
* Always trim 1 trailing newline from the seed in the textarea
* Use an `<input>` box

This should be handled client-side, not in the backend.

**Comment by samuelvisscher** [comment]
I strongly prefer to not allow spaces/whitelines at the end, and trim them automatically

**Comment by gz-c** [comment]
@samuelvisscher ok
