### ISSUE TITLE
Send peers to client before disconnecting due to full peers

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#735]
When a node receives a connection and its connection limit is reached, send more peers to the connection before disconnecting it.

This message must come after the introduction message.

**Comment by olemis** [comment]
@gz-c I sketched a solution to this issue in 0c3f3f7 . It's not tested yet . Nonetheless , could you please review ? I just want to be sure it's on the right track . Thanks in advance .

**Comment by stdevStark** [comment]
@olemis can you check 4e47534 ?

**Comment by olemis** [comment]
Travis failed

**Comment by olemis** [comment]
Please fix [these errors](https://travis-ci.org/simelo/skycoin/jobs/414645614#L5822-L5938) .

**Comment by olemis** [comment]
@gz-c will review #1773 eventually.
