### ISSUE TITLE
[Explorer] On the Address and Tx page dates should be expressed in human readable format not Epoch time.

### ISSUE THREAD

**Issue by entity5459** [skycoin/skycoin#753]
[Explorer] On the Address and Tx page dates should be expressed in human readable format not Epoch time.

Example 

https://explorer.skycoin.net/app/address/KTsUZH8Se9aAYpAt4QnTnfUPTZ8iL9W5Np

![image](https://user-images.githubusercontent.com/29479102/34076598-0685f7e2-e327-11e7-98e8-963d935267c7.png)

**Comment by montycrypto** [comment]
Solved with https://github.com/skycoin/skycoin-explorer/pull/71
