### ISSUE TITLE
[Explorer] Address history page needs clear indicator if funds are incoming or outgoing.

### ISSUE THREAD

**Issue by entity5459** [skycoin/skycoin#754]
[Explorer] Address history page needs clear indicator if funds are incoming or outgoing. 

I would suggest organizing it similar to blockchain.info with sending address or addresses on the left and receiving address or addresses on the right with colored arrow indicating whether the transaction is incoming or outgoing. Showing the actually inputs is also not really that important to people using this page. They just want to see where the funds came from and are going. I would suggest removing it.

Blockchain.info Example:

![image](https://user-images.githubusercontent.com/29479102/34076483-8ea68bf4-e323-11e7-91e0-3811da6d37e7.png)

explorer.skycoin.net

![image](https://user-images.githubusercontent.com/29479102/34076545-a14865d2-e325-11e7-87bf-c404b9e7f9f1.png)

**Comment by therealssj** [comment]
These issues are related to the explorer which has a separate repository [here]https://github.com/skycoin/skycoin-explorer), could you please reopen these there?
