### ISSUE TITLE
how to setup my own test/development environment

### ISSUE THREAD

**Issue by linwh0814** [skycoin/skycoin#769]
I have setup and install golang and the skycoin environment, and it can runs normally with the "make run "command. 

But what I really want to do is to setup my test/development environment, if there are any guide or document to describe how to setup my own skycoin? thank you very much!

**Comment by gz-c** [comment]
Setting up the golang and skycoin environment is the dev environment.

If you need more tools there are some make commands like `make install-linters`, if you're running the lint tests.

Or you can use the dev dockerfiles which will have a full dev environment prepared
