### ISSUE TITLE
Add vet -shadow linter from gometalinter

### ISSUE THREAD

**Issue by Vavilen** [skycoin/skycoin#773]

**Comment by Vavilen** [comment]
go vet -shadow ./src/...
src/api/cli/add_private_key.go:96: declaration of "err" shadows declaration at src/api/cli/add_private_key.go:91
src/api/cli/checkdb.go:41: declaration of "err" shadows declaration at src/api/cli/checkdb.go:35
exit status 1
src/cipher/encoder/encoder.go:875: declaration of "v" shadows declaration at src/cipher/encoder/encoder.go:847
exit status 1
src/daemon/daemon.go:414: declaration of "err" shadows declaration at src/daemon/daemon.go:385
src/daemon/daemon.go:505: declaration of "err" shadows declaration at src/daemon/daemon.go:385
exit status 1
src/daemon/gnet/pool.go:348: declaration of "err" shadows declaration at src/daemon/gnet/pool.go:319
src/daemon/gnet/pool.go:356: declaration of "err" shadows declaration at src/daemon/gnet/pool.go:319
src/daemon/gnet/pool.go:373: declaration of "err" shadows declaration at src/daemon/gnet/pool.go:319
src/daemon/gnet/pool.go:384: declaration of "err" shadows declaration at src/daemon/gnet/pool.go:319
src/daemon/gnet/pool.go:388: declaration of "err" shadows declaration at src/daemon/gnet/pool.go:319
src/daemon/gnet/pool.go:425: declaration of "err" shadows declaration at src/daemon/gnet/pool.go:415
exit status 1
src/gui/explorer.go:83: declaration of "err" shadows declaration at src/gui/explorer.go:75
exit status 1
src/util/file/file.go:265: declaration of "err" shadows declaration at src/util/file/file.go:263
exit status 1
src/visor/blockchain.go:301: declaration of "err" shadows declaration at src/visor/blockchain.go:295
src/visor/db.go:38: declaration of "err" shadows declaration at src/visor/db.go:23
src/visor/blockchain_test.go:782: declaration of "err" shadows declaration at src/visor/blockchain_test.go:765
src/visor/blockchain_test.go:860: declaration of "err" shadows declaration at src/visor/blockchain_test.go:842
src/visor/blockchain_test.go:867: declaration of "err" shadows declaration at src/visor/blockchain_test.go:842
src/visor/blockchain_test.go:913: declaration of "err" shadows declaration at src/visor/blockchain_test.go:895
src/visor/visor_test.go:95: declaration of "err" shadows declaration at src/visor/visor_test.go:92
src/visor/visor_test.go:131: declaration of "err" shadows declaration at src/visor/visor_test.go:128
src/visor/visor_test.go:245: declaration of "err" shadows declaration at src/visor/visor_test.go:148
src/visor/visor_test.go:255: declaration of "err" shadows declaration at src/visor/visor_test.go:148
exit status 1
src/visor/blockdb/unspent.go:233: declaration of "err" shadows declaration at src/visor/blockdb/unspent.go:212
src/visor/blockdb/blockchain_test.go:366: declaration of "err" shadows declaration at src/visor/blockdb/blockchain_test.go:358
src/visor/blockdb/unspent_test.go:72: declaration of "err" shadows declaration at src/visor/blockdb/unspent_test.go:71
src/visor/blockdb/unspent_test.go:357: declaration of "err" shadows declaration at src/visor/blockdb/unspent_test.go:350
src/visor/blockdb/unspent_test.go:441: declaration of "err" shadows declaration at src/visor/blockdb/unspent_test.go:434
src/visor/blockdb/unspent_test.go:446: declaration of "err" shadows declaration at src/visor/blockdb/unspent_test.go:434
src/visor/blockdb/unspent_test.go:604: declaration of "err" shadows declaration at src/visor/blockdb/unspent_test.go:579
exit status 1
src/visor/bucket/bucket.go:159: declaration of "v" shadows declaration at src/visor/bucket/bucket.go:158
src/visor/bucket/bucket_test.go:141: declaration of "err" shadows declaration at src/visor/bucket/bucket_test.go:138
exit status 1
src/visor/historydb/historydb_test.go:182: declaration of "err" shadows declaration at src/visor/historydb/historydb_test.go:177
src/visor/historydb/historydb_test.go:189: declaration of "err" shadows declaration at src/visor/historydb/historydb_test.go:177
src/visor/historydb/historydb_test.go:196: declaration of "err" shadows declaration at src/visor/historydb/historydb_test.go:177
src/visor/historydb/historydb_test.go:398: declaration of "err" shadows declaration at src/visor/historydb/historydb_test.go:388
src/visor/historydb/historydb_test.go:408: declaration of "err" shadows declaration at src/visor/historydb/historydb_test.go:388
exit status 1
src/wallet/service_test.go:95: declaration of "err" shadows declaration at src/wallet/service_test.go:80
exit status 1
make: *** [lint] Error 1

**Comment by Vavilen** [comment]
I found a lot of false positives, like [this one](https://github.com/golang/go/issues/19490)

**Comment by gz-c** [comment]
>Thanks for the report. The -shadow flag is known to have many false positives. That is why it is marked as experimental.

Ignore `-shadow` for now.

You can add a make command:

```
check-more: check
    go vet -shadow ./src/... ./cmd/...
```

And fix the errors that are not false positives

**Comment by Vavilen** [comment]
@gz-c , I`ve made some changes. Please, check my PR.

**Comment by gz-c** [comment]
`go vet -shadow` is experimental and has too many false positives
