### ISSUE TITLE
All client APIs should have a way to identify fatal and retryable errors

### ISSUE THREAD

**Issue by t3rm1n4l** [skycoin/skycoin#776]
Currently, the APIs return an error for network errors as well as application specific errors like "invalid transaction". It should retry for network errors. But, for errors like "invalid transaction", there is no point of retrying and it will never succeed.

**Comment by gz-c** [comment]
AFAIK In the cases where a network error occured, a different status code is returned, e.g. `/api/v1/injectTransaction` returns a 503 on network error
