### ISSUE TITLE
Richlist command, show top N addresses by unspent outputs

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#786]
Should exclude distribution addresses from the list

**Comment by zhiyuan2007** [comment]
PR https://github.com/skycoin/skycoin/pull/796

uri: /richlist
args: n(int) & include-distribution(bool)
return values: [{address: ..., coins: ..., locked: bool}]

sorting order:
balance highest to lowest
locked=true sorted higher than locked=false
address, alphabetically
