### ISSUE TITLE
CLI command to verify if transaction is spendable

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#788]
The `decodeTransaction` or `transaction` commands might already do this. If this is the case, then update the documentation for them.

Otherwise, add a new command `verifyTransaction` that checks the transaction against the blockchain (similar to the checks that `InjectTxn` make)

**Comment by gz-c** [comment]
This can use the `/api/v2/transaction/verify` endpoint

**Comment by githubsands** [comment]
Can you assign me to this issue?
