### ISSUE TITLE
"show seed" API

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#813]
API endpoint to reveal seed of a wallet

`GET /wallet/seed?id={id}&password={password}`

```json
{
    "wallet_id": "abc123",
    "seed": "..."
}
```

**Comment by entity5459** [comment]
Why would anyone needs this? This seems like a big security risk on poorly configured systems.

**Comment by gz-c** [comment]
Its not at any more risk than any other wallet API call (like spending)

**Comment by gz-c** [comment]
When people want to backup their seed now, they have to dig through their filesystem to find the hidden data folder where skycoin stores wallets (~/.skycoin on linux/osx, elsewhere on windows).

We have  "backup wallet" feature currently that "downloads" the wallet file into their downloads folder, so they can open it and get the seed out (which also confuses some people because the wallet file has `.wlt` extension and it doesnt open in a text editor by default, although it is a JSON file)

This is a standard feature in wallets

**Comment by therealssj** [comment]
If the use case is going to be showing the seed to the user then we can just have then wallet read the file and show the seed

**Comment by imbuonarroti** [comment]
Please helpme. gz-c. 
I lost my seed superwallet because computer broken. I have transection ID and my wallet address. please seve my coin (suncooin ICO. I join ICo 2017.10.15  and take coin 2017.10.16). my wallet bloken.  please.

**Comment by olemis** [comment]
FWIW , I do not think we should implement this via the API , like @therealssj said

**Comment by olemis** [comment]
The password will be encrypted , or at least obfuscated , right ? How ?

**Comment by olemis** [comment]
I mean , anything already implemented for this ?

**Comment by gz-c** [comment]
This is now part of #665 

This will be disabled by default, but enabled when running as a desktop client.  The endpoint will require the wallet password and only work for encrypted wallets.

**Comment by gz-c** [comment]
wip

**Comment by gz-c** [comment]
#1189
