### ISSUE TITLE
Transaction should always be recorded

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#817]
>[skycoin.daemon:WARNING] Failed to record transaction 73f0d9819b25ec319ab5bef6e4c10b6074fb360b937ff97fba38cc6958991354: unspent output of 73873ecef87c9157fc9ae30fb5075693ba962d4fe165b5c3c797c2a68f0ac048 does not exist

"Failed to record" <-- this condition does not exist (TX is always recorded, just not propagated if unspendable)
- if TX is announced by hash, we check if we have it
- if we do not have it, we record it
- if it is valid (can be executed), then we rebroadcast it
- we recheck transactions for validity every block

**Comment by gz-c** [comment]
Eventually it would fill with invalid txns

The main problem is that we are broadcasting an invalid txn
We should not broadcast if they are invalid right now, the only case this matters is when the node is not fully synced, that node would fail to rebroadcast certain valid transactions that are based upon unspent outputs from the part of the blockchain they have not synced.
