### ISSUE TITLE
errors in logfile

### ISSUE THREAD

**Issue by knekke** [skycoin/skycoin#818]
Hi,
I'm running skycoin on Fedora26 and while everything seems to be working I get a lot of errors in the logoutput. I tried Standalone, Installer and a custom build from the dev branch, but always the same output.
Here some samples:
`
...
[skycoin.daemon:ERROR] daemon.Visor.InjectTxn error: unspent output of 8439b81d0428ab1bba2e9575c399a2d978d7b7ad3450aa73fded0947678f37f8 does not exist
[skycoin.daemon:ERROR] Visor request func failed: unspent output of 8439b81d0428ab1bba2e9575c399a2d978d7b7ad3450aa73fded0947678f37f8 does not exist
[skycoin.daemon:WARNING] Failed to record transaction 967a2ef53b4bdc26e180cf6baf1216fd74e988e082b81ea20788c7b40f4d2baf: unspent output of 8439b81d0428ab1bba2e9575c399a2d978d7b7ad3450aa73fded0947678f37f8 does not exist
...
[skycoin.daemon:DEBUG] Got 0 blocks since 8340
...
`
Google revealed nothing...

**Comment by gz-c** [comment]
This is benign, its an invalid txn that is repropagating through the network. #817 is created to address this problem

**Comment by olemis** [comment]
@gz-c if this is the case , should we close this issue as duplicate ?
