### ISSUE TITLE
No checksum & signatures for the wallet files.

### ISSUE THREAD

**Issue by toldenburger** [skycoin/skycoin#826]
I can't see any checksum and signatures for the wallet applications.

Especially for software that hold large amounts of funds it is important to add these to prevent downloading bad software.

**Comment by gz-c** [comment]
related: https://github.com/skycoin/skycoin.net/issues/180

**Comment by gz-c** [comment]
Added for latest release, will be added for future releases ongoing https://github.com/skycoin/skycoin/releases/tag/v0.22.0
