### ISSUE TITLE
Move docker scripts to skycoin/skycoin

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#827]
Move code in [docker image repository](https://github.com/skycoin/docker-img) onto skycoin/skycoin . Initially under `src/scripts/docker/images/mainnet` (<= @gz-c is this ok ? other suggestion `src/docker/images/mainnet`)

**Comment by olemis** [comment]
Cc @stdevMauricio

**Comment by gz-c** [comment]
Not in `src/` folder, start in repo root, maybe `docker/images/`

**Comment by olemis** [comment]
@stdevMauricio can we close this issue ?

**Comment by stdevMauricio** [comment]
I think so. My only concern is the hardcoded version in the Dockerfile. Should I change it?

**Comment by olemis** [comment]
Docker files in develop branch already . @gz-c may we close this branch ?
