### ISSUE TITLE
Implement a cli option to specify peers list.

### ISSUE THREAD

**Issue by stdevMauricio** [skycoin/skycoin#834]
I'm currently implementing the testnet in docker and the peer list in that case would be virtual (the testnet nodes). Right now is hardcoded, so it would be nice if it could be specified in the command line while launching the daemon.

**Comment by olemis** [comment]
This is already possible 

@stdevMauricio by specifying CLI `--data-dir` option the daemon will configure the PEX to load `peers.txt` from the path specified as argument .

Please try that.
