### ISSUE TITLE
Skycoin daemon only accepts IP addresses in the peers list.

### ISSUE THREAD

**Issue by stdevMauricio** [skycoin/skycoin#835]
I'm currently implementing the testnet in docker and the nodes IP addresses are dynamic. Docker makes a DNS record in its nets for every container, so it would be trivial to make a list of machine names, but the skycoin daemon only accepts IP addresses in the peers list. Changing it to be able to resolve names would make it possible to implement a docker testnet.

**Comment by olemis** [comment]
@stdevMauricio have you actually tried to use names instead of IP addresses ? If so what (error) message do you get ? It seems to me that both IP and names should work .

**Comment by olemis** [comment]
Besides this , it is possible to [assign static IP address thorugh Docker compose](https://stackoverflow.com/questions/39493490/provide-static-ip-to-docker-containers-via-docker-compose) .

Considering my comments above I'd rather close this issue as a `wontfix` . What d'u think @gz-c ?

**Comment by therealssj** [comment]
From what I could infer from the codebase there is only support for ipv4 addresses.
If I try to use a domain name it throws out `Invalid address domain.com: Invalid address`

imo there should be support for DNS resolution so instead `wontfix` maybe we should just change the issue to add support for domains and ipv6 addresses?

**Comment by gz-c** [comment]
I'll make new issues for supporting domains and ipv6 addresses, but they are low priority if the situation with docker is resolved

**Comment by gz-c** [comment]
#874, #875
