### ISSUE TITLE
Implement a cli option to make a daemon work as an initial seed for testing

### ISSUE THREAD

**Issue by stdevMauricio** [skycoin/skycoin#842]
A cli option is necessary in order to tell some testnet nodes they will act as initial seeds.

**Comment by olemis** [comment]
Cc @stdeEdu

**Comment by olemis** [comment]
@stdevMauricio this is already implemented . Please use `-master` option in Skycoin CLI .

**Comment by olemis** [comment]
This is a `wonfix` btw . I did not add the label . @gz-c should I ?

**Comment by gz-c** [comment]
@olemis label not needed
