### ISSUE TITLE
Getting CORS error when running Skycoin from Docker

### ISSUE THREAD

**Issue by Xumeiquer** [skycoin/skycoin#845]
Hi, 
I followed the README to create the docker image and running skycoin fron the docker image. Everything went well until I try to create a wallet, because I get a CROS (Access-Control-Allow-Origin) error.

I am running skycoin docker behind Traefik reverse proxy.

Is there any configuration that I should change?

**Comment by ernestomr87** [comment]
the corsproxy module is a tool that is used to solve problems with the CORS, the only thing you have to do is install it globally, run it in a terminal and modify the endpoints so that you replace http://localhost:3000/api for http://localhost:1337/localhost: 3000/api.

**Comment by Xumeiquer** [comment]
Hi, 
I think you made a mistake on your recomendation or I don't get it.

The main idea about using docker is to avoid intalling it globally. 
It should have an option to change that behaviour and allow other or several domains.

**Comment by ernestomr87** [comment]
I'm sorry, I was wrong about the problem.

**Comment by gz-c** [comment]
We do not support docker for the browser client wallet functionality. Not sure we want to add CORS configuration and risk mistakes in it just for this purpose. A solution external to the skycoin node would be preferred

**Comment by olemis** [comment]
I'd suggest to keep this open for a while since maybe CORS proxy deployment can be automated to improve the current situation.

Cc @stdevMauricio

**Comment by olemis** [comment]
Initially, In my opinion this is related to #1901 . Maybe there's a chance for this error to go away once #1902 will be merged . Let's try that first .

**Comment by gz-c** [comment]
@olemis status of this issue?

**Comment by olemis** [comment]
No one assigned ... I do not think there is somebody working on this
@stdevStark , could u pls take a look ?
