### ISSUE TITLE
Wallet history tab does not show decimal values

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#848]
Making small transactions of values like `0.25` show up as Amount `0` in the history tab 
<img width="1034" alt="screen shot 2018-01-14 at 7 59 20 pm" src="https://user-images.githubusercontent.com/8619106/34916937-7870c522-f965-11e7-8f29-242ae60602ac.png">

I have not tested it with values greater than 1, I am guessing it just shows integer values hence the 0

**Comment by therealssj** [comment]
@samuelvisscher

**Comment by samuelvisscher** [comment]
This issue was related to old wallet
