### ISSUE TITLE
Replace github.com/op/go-logging with logrus

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#858]
https://godoc.org/github.com/sirupsen/logrus

This is used in teller and skywire

**Comment by stdevCCC** [comment]
Logrus and go-logging are not using the same logging levels, the Logurs equivqlent to go-logging's "Critical" should be "Fatal", but "Fatal" calls a system exit. How should we handle the current "Critical" calls?

**Comment by gz-c** [comment]
Switch "Critical" to "Error"

**Comment by gz-c** [comment]
We may need to reserve "Error" for "Critical" and switch most of the current "Error" to "Warn"

**Comment by gz-c** [comment]
https://github.com/spf13/jwalterweatherman

This might be a better option

**Comment by olemis** [comment]
Ok. We'll be using this lib instead .

**Comment by olemis** [comment]
@stdevLandy since `logrus` levels are integer numbers and others have been able to include further levels (e.g. [`Trace` logging level in contanerd](https://github.com/containerd/containerd/pull/2106/files) let's stick to that .

**Comment by olemis** [comment]
sirupsen/logrus#733 has been created as a starting point to fix this .
