### ISSUE TITLE
Backing up wallet only contains seed, bug?

### ISSUE THREAD

**Issue by briancaine** [skycoin/skycoin#862]
Backing up a wallet from the skycoin web interface produces a JSON file containing `{"seed": "seed goes here"}`.

The [backup.components.ts file](https://github.com/skycoin/skycoin/blob/develop/src/gui/static/src/app/components/pages/settings/backup/backup.component.ts#L27) is responsible for that.

However, in the Go source code, [wallet.ReadableWallet](https://github.com/skycoin/skycoin/blob/develop/src/wallet/readable.go#L72) expects `{"meta": { ... }, "entries": [ ... ]}`, which matches the format of the file I have in `~/.skycoin/wallets`. (The seed ends up being a member of `meta`.)

They both use the `.wlt` extension. It tripped me up when I was messing with teller.

Not sure if it's a huge issue or not, just bringing it to someone's attention.

**Comment by gz-c** [comment]
This "backup wallet" mechanism is to be removed in the next wallet release, #813

**Comment by briancaine** [comment]
Fair enough.
