### ISSUE TITLE
Load Wallet should not request a new seed

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#863]
In `Load Wallet` I do not see the point of having the field populated with a `seed` already
<img width="577" alt="screen shot 2018-01-17 at 3 04 26 pm" src="https://user-images.githubusercontent.com/8619106/35035586-e4288bfe-fb97-11e7-8804-c597bcd7c442.png">

cc: @samuelvisscher

**Comment by samuelvisscher** [comment]
Agreed, will fix this
