### ISSUE TITLE
Advanced spend CLI

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#872]
Add an internal spend method that allows the following parameter choices:

Inputs:
    User can choose:
        - a specific wallet
            - application will combine all unspents from the wallet and choose which to spend automatically
        - one or more addresses in a wallet
            - application will combine all unspents from these addresses and choose which to spend automatically
        - one or more unspents from addresses in a wallet
            - user chooses the unspents

Outputs:
    User can choose:
        - One or more destination addresses
        - Coins to send to each destination address
        - Hours to send to each destination address (optional, will distribute hours evenly otherwise)

Then, create two cli methods, `advancedSend` and `advancedCreateRawTx`:

`advancedSend <wallet> <destinations> [-addresses $addr1,$addr2] [-unspents $uxid1,uxid2]`

<wallet> is the wallet file
<destinations> is a JSON string of the format `[{"addr":"...","coins":"123.456789","hours":"0"},...]`.  "hours" is optional and defaults to "0".
-addresses is an optional comma-separated list of addresses to spend from. These addresses must be in the wallet file
-unspents is an optional comma-separated list of unspent output uxIDs to spend from. These unspents must be associated with addresses in the wallet file.

Example:

```sh
advancedSend my.wlt \
    '[{"addr":"bxpUG8sCjeT6X1ES5SbD2LZrRudqiTY7wx","coins":"1.000000","hours":"10"},{"addr":"bxpUG8sCjeT6X1ES5SbD2LZrRudqiTY7wx","coins":"1.000000"}]' \
    -addresses cGPHG23We5otc5ME7EqPNKnzZe7CVm3Fjx,2E88wjND2uLGM6QCXpEDEJ29RuScXZVRLJW
```

Any suggestions to improve this proposed CLI API are welcome

**Comment by therealssj** [comment]
When I am sending from multiple addresses how would you like to decide the change the address?
The first one?

**Comment by therealssj** [comment]
This is my current idea
- Format 1 :- sending only to single address

```
skycoin-cli advancedSend -f my.wlt \
-a $fromaddr1, $fromaddr2 -s $coinhour_distribute_cap \
-u $unspent1,$unspent2 $toAddr $amt
```

- Format 2 :- sending to multiple addresses
```
skycoin-cli advancedSend -f my.wlt \
-a $fromaddr1, $fromaddr2 -s $coinhour_distribute_cap \
-u $unspent1,$unspent2 \
-m '[{"addr":"bxpUG8sCjeT6X1ES5SbD2LZrRudqiTY7wx","coins":"1.000000","hours":"10"},{"addr":"bxpUG8sCjeT6X1ES5SbD2LZrRudqiTY7wx","coins":"1.000000"}]' \
$amt
```

The only addition here from your suggestions is the `-s` parameter
It allows simple definition of how many coins hours I want to send
If the user doesn't want to tell individual coin hour spending for all the addresses then he can just define the max coin hours he wants to send using the `-s` flag

**Comment by gz-c** [comment]
First version, omit the `$coinhour_distribute_cap`, we can add that into a second revision.

The coinhour sending has several questions, e.g. if the `$coinhour_distribute_cap` cannot be satisfied, do we abort or continue?  Should we have a parameter for a % coinhour distribution?

It'll be easier to focus on send from many, send to many first, then add parameters to tweak how the coinhours are sent

**Comment by therealssj** [comment]
`$coinhour_distribute_cap` needs be below 50% otherwise we abort is what I have done right now

The question about not being able to satisfy the `coinhours` can be raised for multiple sending as well `[{"addr":"bxpUG8sCjeT6X1ES5SbD2LZrRudqiTY7wx","coins":"1.000000","hours":"100000"}]`
what if I dont have `100000` coinhours, I will abort right?

**Comment by gz-c** [comment]
Yes, there are a number of conditions that must be satisfied and there are verification methods in the code for this

**Comment by gz-c** [comment]
The spend methods should fail with an error if you had provided spend amounts like that

**Comment by therealssj** [comment]
```
[{"addr":"$addr1","coins":"1.000000","hours":"10"},{"addr":"$addr2","coins":"2.000000"},{"addr":"$addr3","coins":"3.000000"}]
```

Do `$addr2` and `$addr3` get 0 coin hours or `remaininghours` after giving 10 to `$addr1` are distributed evenly?

**Comment by gz-c** [comment]
If hours not specified, default to 0.

The advanced spend method does not auto-distribute hours

**Comment by gz-c** [comment]
We can get back to this when we finish make the CLI's interface mirror the API's

For createTransaction, the CLI can do this offline, or send a request to the API
