### ISSUE TITLE
What about to change static api.service.ts url to auto fit in the url in the browser?

### ISSUE THREAD

**Issue by cuu** [skycoin/skycoin#876]
in skycoin/src/gui/static/src/app/services/api.service.ts 
**line 12**, **develop** branch

```
private url = location.protocol+'//'+location.hostname+(location.port ? ':'+location.port: '')+"/";
```

I think this is  more convenient  to run  than just make it to 127.0.0.1 without any security issues

**Comment by gz-c** [comment]
@samuelvisscher  ?

**Comment by gz-c** [comment]
@cuu what is more convenient about it?

**Comment by cuu** [comment]
@gz-c  easier to host skycoin on different machine in NAT, once I setup skycoin, could not load the page correctly because a lot of resources loaded failed because of the url above is only for localhost

So maybe it is more convenient to fit the url based on the URL in user's browser
not just localhost only

**Comment by gz-c** [comment]
Oh, won't work anyway because of Host header check, must be localhost

**Comment by gz-c** [comment]
Moved to #1258

**Comment by gz-c** [comment]
Although, I would not want to encourage users to do this since it exposes their wallet on their LAN
