### ISSUE TITLE
Allow specific address to be checked for validity.

### ISSUE THREAD

**Issue by stdevOzkar** [skycoin/skycoin#884]
Create and endpoint to check the validity of a wallet address(validity as in valid, and validity for real wallets).
`URI: /address/<string:addr>/
Method: GET`
example:
`curl http://127.0.0.1:6420/address/7cpQ7t3PZZXvjTst8G7Uvs7XH4LeM8fBPD`
result:
`isValid:True`
example:
`curl http://127.0.0.1:6420/address/nu7eSpT6hr5P21uzw7bnbxm83B6ywSjHdq`
result:
`isValid:False`

**Comment by gz-c** [comment]
What is this for?

**Comment by olemis** [comment]
It's for `[GET] api/addresses/{address}/is-valid` API endpoint in Lykke integration specs.

**Comment by olemis** [comment]
Not needed
