### ISSUE TITLE
Test gateway wallet methods return error when wallet api disabled

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#887]
#877 Adds -disable-wallet-api CLI option.

This configures the daemon Gateway to return ErrWalletApiDisabled.

However, the tests only cover the HTTP endpoints, and mock the response from Gatewayer, so the Gateway methods themselves are not tested to block the wallet API when tested.  That is, the tests check that the HTTP handlers will return a 403 when it receives ErrWalletApiDisabled from the daemon Gateway, but they do not test that the Gateway returns ErrWalletApiDisabled when it is disabled in the config.

**Comment by Vavilen** [comment]
Done:
- gw.GetWallet
- gw.GetWallets
- gw.GetWalletUnconfirmedTxns

**Comment by gz-c** [comment]
@Vavilen which pr?

**Comment by Vavilen** [comment]
#1025
