### ISSUE TITLE
Skycoin-lib boilerplate

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#902]
Implement the basics of a shared library code to expose Skycoin functions for (re)use from within other programming languages .

**Comment by olemis** [comment]
@gz-c where should we put source code for such lib ? Does `/src/lib` works for you ? Or maybe better `/lib`?

**Comment by gz-c** [comment]
@olemis if its golang code that will be imported, then `src/lib/` is fine, if its alien code, then `/lib` would be ok
