### ISSUE TITLE
Restoring wallet does not show coins until restart

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#904]
When I restore a wallet using a seed I don't see the coins till I do the restart
Tried on latest branch as well, same behaviour

**Comment by gz-c** [comment]
I saw this bug too. Happened when I did a fresh full sync.  `/balance?addrs=` was returning a 500 but I didn't see an error in the logs.

**Comment by gz-c** [comment]
Can't replicate this easily but it does happen

**Comment by samuelvisscher** [comment]
Just to be clear, this appears to be a back-end bug?

**Comment by gz-c** [comment]
@samuelvisscher Yes, a 500 error coming from there

**Comment by therealssj** [comment]
```
[skycoin.gui:ERROR] Get balance failed: get unconfirmed spending failed when checking addresses balance: get unconfirmed spend error:unconfirmed transaction's IN: 8439b81d0428ab1bba2e9575c399a2d978d7b7ad3450aa73fded0947678f37f8 is not in unspent pool
```
this is the error I could see in log

It happend when I deleted the `~/.skycoin` folder and then tried to restore the wallet while the block chain was syncing

**Comment by gz-c** [comment]
@therealssj is this still valid

**Comment by therealssj** [comment]
@gz-c fixed now.
