### ISSUE TITLE
Problems with /explorer/address

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#918]
Doing some changes to the explorer I found that `/explorer/address` is returning an incorrect number of hours in the inputs. In the following image (taken from a modified version of the explorer) you can see an example:
![input](https://user-images.githubusercontent.com/34079003/35548473-04f210fe-0556-11e8-91cc-07fae095dd21.png)

In the image you can see that q6UjfkBA... received an output with 380 coins and 269 on 1/25/18, 7:35 AM. On 1/26/18, 5:48 AM the address used that same output as an input in a new transaction and it says that the input had 269 hours, the same amount as when it was received, but the outputs resulting from the transaction have more than 2000 hours each, which means that the input clearly had much more than 269 hours when it was used.

The results shown in the image correspond to transactions 6 and 7 of the followind call to the node's api: http://127.0.0.1:8001/api/address?address=q6UjfkBAhB8s9DjWnLKjgkTVs8j5a6bt4f

Modifications should be made so that `/explorer/address` returns the correct number of hours of the inputs or, if that is not possible, eliminate the number of hours of the inputs in the responses returned by the endpoint. Additionally, I would like to know if it is viable to solve the problem, to make some decisions in the development of the explorer.

I'm not sure about how to fix the problem, but the following data may be helpfull: the code that handles the `/explorer/address` endpoint is on line 147 of /src/gui/explorer.go. The problem seems to be on line 185, because `gateway.GetUxOutByID(id)` (function that is called to obtain the data of the inputs) always returns the number of hours the outputs had when they were received.

**Comment by gz-c** [comment]
Must not be recalculating the CoinHours based upon block execution time

**Comment by gz-c** [comment]
#920

**Comment by gz-c** [comment]
@therealssj can you confirm if this is done?

**Comment by gz-c** [comment]
#919 and #920 cover this issue

The problem stated here is because the hours are the original input hours and not the calculated hours
