### ISSUE TITLE
Transaction inputs data

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin#919]
Various api endpoints returning transaction data return only the hash of the inputs, but it is necessary to return more data, so that the api can be used in a more practical way. The inputs data should include the owning address, the coins and the hours. The endpoints with the problem are `/block`, `/blocks`, `/transaction` and `/pendingTxs` (there could be others, but those are the ones I've been using).

However, the change could break the compatibility with the systems that are currently using the api, because the current response have the following format:

```
"inputs": [
    "0922a7b41d1b76b6b56bfad0d5d0f6845517bbd895c660eab0ebe3899b5f63c4",
    "d73cf1f1d04a1d493fe3480a00e48187f9201bb64828fe0c638f17c0c88bb3d9",
    "16dd81af869743599fe60108c22d7ee1fcbf1a7f460fffd3a015fbb3f721c36d"
],
```

It would be ideal to change them to respond with the same format used by `/explorer/address`:

```
"inputs": [{
    "uxid": "0922a7b41d1b76b6b56bfad0d5d0f6845517bbd895c660eab0ebe3899b5f63c4",
    "owner": "2Q2VViWhgBzz6c8GkXQyDVFdQUWcBcDon4L",
    "coins": "7.000000",
    "hours": "851106"
}],
```

However, this change could give compatibility problems. Therefore, another alternative would be the following, which should work correctly:

```
"inputs": [
    "0922a7b41d1b76b6b56bfad0d5d0f6845517bbd895c660eab0ebe3899b5f63c4",
    "d73cf1f1d04a1d493fe3480a00e48187f9201bb64828fe0c638f17c0c88bb3d9",
],
"inputs_data": [
    {
        "owner": "2Q2VViWhgBzz6c8GkXQyDVFdQUWcBcDon4L",
        "coins": "7.000000",
        "hours": "851106"
    },
    {
        "owner": "2Q2VViWhgBzz6c8GkXQyDVFdQUWcBcDon4L",
        "coins": "8.000000",
        "hours": "751106"
    }
],
```

I would like to know @gz-c 's opinion regarding which option to take.

Additionally, before making any changes, it is necessary to take into account the problem that `/explorer/address` currently has and wait to see what alternative is available: https://github.com/skycoin/skycoin/issues/918

**Comment by gz-c** [comment]
We can add "inputs_data", but each object in that array should have "uxid" in it.

When we clean up the API we'll remove "inputs" and rename "inputs_data" to "inputs"

**Comment by Senyoret1** [comment]
Working on it.

**Comment by stdevEclipse** [comment]
The required change is that endpoint /blocks returns a result similar to /explorer/address.
That can be done. However, I don't know how costly it would be finding these data as I guess it resides outside transaction object in the database. I think, I am not quite sure.

**Comment by Senyoret1** [comment]
Not just `/blocks`, but also `/block`, `/transaction` and `/pendingTxs`. When the issue was filed, the problem was that the explorer needs to show the number of coins and hours of the inputs, something that currently is not possible to do optimally with the data that these endpoints return. However, now it is also needed for the desktop wallets and the web wallet. With regard to the impact on performance, I dont know.

**Comment by stdevEclipse** [comment]
OK. I think it can be optimized later on.

**Comment by gz-c** [comment]
Since the /v2/ api has been started, we'll likely do it in there

**Comment by stdevEclipse** [comment]
Already working on /v1/.

**Comment by stdevEclipse** [comment]
Already made the requested change for enpoint /blocks. It was necessary to add a field to visor.ReadableTransaction and some tests are failing because of this. For the other endpoints it will be necessary further changes to other structures, for example: coin.SignedBlock

**Comment by gz-c** [comment]
You will have to make a new struct in the api package which wraps a visor.ReadableTransaction and adds the new fields, to avoid changing the ReadableTransaction struct

**Comment by gz-c** [comment]
and no struct in package coin should be changed at all

**Comment by stdevEclipse** [comment]
OK.

**Comment by stdevEclipse** [comment]
I see that PR #928 is the same thing.
Didn't this solve issue #919?
Well, I guess not.

**Comment by gz-c** [comment]
It was too much effort to merge #928

**Comment by stdevEclipse** [comment]
This is what I am doing to create endpoint api/v2/blocks
After:
webHandlerV1 := func(endpoint string, handler http.Handler) {
	if c.enableUnversionedAPI {
		webHandler(endpoint, handler)
	}
	webHandler("/api/v1"+endpoint, handler)
}

I add this:
webHandlerV2 := func(endpoint string, handler http.Handler) {
	if c.enableUnversionedAPI {
		webHandler(endpoint, handler)
	}
	webHandler("/api/v2"+endpoint, handler)
}

Then, I add this handler:
webHandlerV2("/blocks", getBlocksV2(gateway))

After this, I am able to make different calls, api/v1/blocks, and api/v2/blocks, they go to different methods.
But one of the usual tests is failing (make test). Which is odd because this test is supposed to use Gateway mock.

**Comment by gz-c** [comment]
@stdevEclipse to read all data in one call, add a single method to visor.Visor, which will query all necessary data in a single read transaction

**Comment by stdevEclipse** [comment]
And one method to gatewayer interface.

**Comment by stdevEclipse** [comment]
My aim is read all required data (including transaction input with Address, Coins, Hours) in one access to database. But I think this is not possible. Blocks are saved:
	dbutil.PutBucketValue(tx, BlocksBkt, hash[:], encoder.Serialize(b))
Where b is a variable of type coin.Block. Because this type doesn't contain required extra information and it is saved with encoder.Serialize. I believe an extra search in database is needed by doing a call to GetUxOutByID, which will make another call to GetBucketObjectDecoded with the hash of the uxOut. 
  Resuming, the required data reside in a different hashable object in database.
  Correct me if I am wrong.

**Comment by stdevEclipse** [comment]
@gz-c, this is ready for review

**Comment by olemis** [comment]
@stdevEclipse review happens in the PR ... which is ?
