### ISSUE TITLE
docker version not working (on windows at least)

### ISSUE THREAD

**Issue by nutmix** [skycoin/skycoin#927]
The documentation says this:

```
$ docker volume create skycoin-data
$ docker volume create skycoin-wallet
$ docker run -ti --rm \
    -v skycoin-data:/data \
    -v skycoin-wallet:/wallet \
    -p 6000:6000 \
    -p 6420:6420 \
    -p 6430:6430 \
    skycoin/skycoin
```
If this is run in windows e.g. with git bash ( with -ti changed to -i) or via cmd, it always gives this error:

```
Unable to find image 'skycoin/skycoin:latest' locally
```

**Comment by skycoin-karl** [comment]
[https://github.com/skycoin/skycoin/tree/develop/docker/images/mainnet](https://github.com/skycoin/skycoin/tree/develop/docker/images/mainnet)

```
$ docker build -t skycoin .
```

**Comment by nutmix** [comment]
It seems the issue is where the docker command is run from. I was running it from the root of the project.

The following works:

$ docker run -i --rm -v skycoin-data:/data -v skycoin-wallet:/wallet -p 6000:6000 -p 6420:6420 -p 6430:6430 skycoin

**Comment by olemis** [comment]
@nutmix @skycoin-karl I do not understand very well why is this happening . The command in the docs should pull [skycoin/skycoin image](https://hub.docker.com/r/skycoin/skycoin/) from Docker hub.

**Comment by olemis** [comment]
@nutmix your issue is quite similar to moby/moby#19859 . Please check your Docker setup .
