### ISSUE TITLE
Check Origin and Referer header

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#931]
Similar to #891 

https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Verifying_Same_Origin_with_Standard_Headers

If the Origin header is present, check that value
else if the Referer header is present, check that value,
if neither are present, reject

**Comment by therealssj** [comment]
Will need to update tests as well for this
