### ISSUE TITLE
[cosmetic] "About Skycoin" menu item not working

### ISSUE THREAD

**Issue by nutmix** [skycoin/skycoin#936]
Low priority.

**Applies to:** Windows 64 bit installer download V.0.21.1

**How to reproduce:**
1. launch the app via start menu ("skycoin App")
1. click on skycoin menu header in top left of app window
1. click on "About Skycoin".

**Expected behaviour:**
Some sort of pop up with some about Skycoin info, or opening a browser to skycoin.com.

**Actual behaviour:**
Nothing happens.

![image](https://user-images.githubusercontent.com/5080942/35730467-8a4c68b2-0812-11e8-8d28-189ecbe6fd35.png)

**Comment by samuelvisscher** [comment]
@gz-c what would you like this button to do?

**Comment by gz-c** [comment]
I don't know why its showing up in the menu bar. 

@iketheadore do you know where that comes from?

**Comment by iketheadore** [comment]
It's created in electron-main.js:
![image](https://user-images.githubusercontent.com/2589926/37815490-06b92c38-2eaa-11e8-9427-e8a9e922b3d9.png)

**Comment by gz-c** [comment]
ok we should remove it, only have quit

**Comment by iketheadore** [comment]
The `About Skycoin` menu item is removed.

**Comment by gz-c** [comment]
This is still present in the Windows build

**Comment by mahansky** [comment]
Just did a windows/amd64 build (skycoin-0.23.1-rc2-gui-win-setup) and it's not there (it was removed 2 months ago, so v23 should not have it)
