### ISSUE TITLE
electron app not displaying error message

### ISSUE THREAD

**Issue by skycoin-karl** [skycoin/skycoin#940]
After pressing "Send" the red box appears at the bottom of the window. No matter how I resize the window it just stays fixed at the bottom.

<img width="1311" alt="screen shot 2018-02-04 at 1 26 31 pm" src="https://user-images.githubusercontent.com/35973405/35780809-47f9504e-09af-11e8-8005-b09cc4e56d12.png">

**Comment by gz-c** [comment]
Fixed already
