### ISSUE TITLE
CreateRawTx fails: filtering UxOuts doesn't distribute CoinHours

### ISSUE THREAD

**Issue by skycoin-karl** [skycoin/skycoin#945]
Calling `cli.CreateRawTx` like so:

```go
tx, err := cli.CreateRawTx(s.Client, s.Wallet, s.From, s.From[0], to)
if err != nil {
	return nil, err
}
```

`s.From` contains 1 address with a balance of 10.001 SKY:

```
([]string) (len=1 cap=1) {
	(string) (len=34) "MBEdZD3V9UMUFaSTLRW1APdJ6WUUqU17Mm"
}
```

`to` contains 2 addresses, with a desired send amount of 5 SKY each:

```
([]cli.SendAmount) (len=2 cap=2) {
	(cli.SendAmount) {
		Addr: (string) (len=35) "8vENogZsADL1aEktfaoYKNPcthfgfwxVMU",
		Coins: (uint64) 5000000
	},
	(cli.SendAmount) {
		Addr: (string) (len=35) "3ZQhhQxpyZ8v1yWLr7oSZ9dNz1NiqDxhFe",
		Coins: (uint64) 5000000
	}
}
```

The error returned by `cli.CreateRawTx` is `Transaction has zero coinhour fee`. This is happening because the filter implemented in [#943](https://github.com/skycoin/skycoin/pull/943) filters out the unused `coin.UxOut` but doesn't distribute the CoinHours.

While the filter is a simple solution, the underlying problem seems to be multiple `coin.UxOuts` being generated for one address. 

Here is the `coin.UxArray` before being filtered:

```
(coin.UxArray) (len=2 cap=2) {
	(coin.UxOut) {
		Head: (coin.UxHead) {
			Time: (uint64) 1517854435,
			BkSeq: (uint64) 13924
		},
		Body: (coin.UxBody) {
			SrcTransaction: (cipher.SHA256) (len=32 cap=32) {
				00000000  29 dd 53 40 8d 3e 66 1b  f1 ff 68 eb 69 c3 88 87  |).S@.>f...h.i...|
				00000010  92 b2 b5 c2 b2 66 5c 57  85 63 25 11 88 87 07 78  |.....f\W.c%....x|
			},
			Address: (cipher.Address) MBEdZD3V9UMUFaSTLRW1APdJ6WUUqU17Mm,
			Coins: (uint64) 1000,
			Hours: (uint64) 2280
		}
	},
	(coin.UxOut) {
		Head: (coin.UxHead) {
			Time: (uint64) 1517854835,
			BkSeq: (uint64) 13933
		},
		Body: (coin.UxBody) {
			SrcTransaction: (cipher.SHA256) (len=32 cap=32) {
				00000000  db e9 c9 46 2e a8 4c 1d  1e 1c 9f a3 1a 72 63 df  |...F..L......rc.|
				00000010  33 07 a3 cf 37 87 a3 ef  1f c9 da d2 8a 27 ef ea  |3...7........'..|
			},
			Address: (cipher.Address) MBEdZD3V9UMUFaSTLRW1APdJ6WUUqU17Mm,
			Coins: (uint64) 10000000,
			Hours: (uint64) 4
		}
	}
}
```

As you can see, there is a `coin.UxOut` with 0.001 SKY and 2280 CoinHours. The other `coin.UxOut` contains 10 SKY and 4 CoinHours. The filter removes the `coin.UxOut` with the unnecessary coins but this also removes most of the CoinHours.

Here is the `coin.UxArray` after being filtered:

```
(coin.UxArray) (len=1 cap=1) {
	(coin.UxOut) {
		Head: (coin.UxHead) {
			Time: (uint64) 1517854835,
			BkSeq: (uint64) 13933
		},
		Body: (coin.UxBody) {
			SrcTransaction: (cipher.SHA256) (len=32 cap=32) {
				00000000  db e9 c9 46 2e a8 4c 1d  1e 1c 9f a3 1a 72 63 df  |...F..L......rc.|
				00000010  33 07 a3 cf 37 87 a3 ef  1f c9 da d2 8a 27 ef ea  |3...7........'..|
			},
			Address: (cipher.Address) MBEdZD3V9UMUFaSTLRW1APdJ6WUUqU17Mm,
			Coins: (uint64) 10000000,
			Hours: (uint64) 4
		}
	}
}
```

The 4 CoinHours quickly drops to 0 after 1-2 more transactions. Meanwhile, 0.001 SKY is left behind with 2280 CoinHours.

**Comment by therealssj** [comment]
This is by design I reckon
The order for selecting unspents is 
- unspent with most coins
- unspent with zero coins
- unspent with non zero coins

We will mostly solve this issue through advanced spend https://github.com/skycoin/skycoin/issues/872

**Comment by skycoin-karl** [comment]
@therealssj Okay. #872 looks like it would fix this. This issue is medium-priority as it still interferes with some `cli.CreateRawTx` calls but only once CoinHours gets to zero.

**Comment by gz-c** [comment]
Yes this is by design, `cli createRawTransaction` uses a spend policy of minimizing coin hours burned.  This policy is chosen with exchanges in mind, which have a higher transaction frequency.

It only affects the use case of "cycle coins between addresses over and over" which isn't a real world use case.  It's supposed to run out of coin hours eventually, coin hours a rate limiting mechanism.
