### ISSUE TITLE
API integration tests

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#948]
Need integration tests for the HTTP API.

The blockchain APIs will be easier to test than the wallet APIs which modify data.

For the blockchain API integration tests, we could automate this in travis.  The skycoin node would need an option (if it does not have one) to disable the p2p networking.  We would include a default blockchain data.db test file, from which the blockchain APIs could read from.

API method checklist:

- [x] `/version`
- [x] `/outputs`
- [x] `/outputs?addrs=`
- [x] `/outputs?hashes=`
- [x] `/coinSupply`
- [x] `/block?hash=`
- [x] `/block?seq=`
- [x] `/blocks`
- [x] `/last_blocks`
- [x] `/blockchain/metadata`
- [x] `/blockchain/progress`
- [x] `/balance?addrs=`
- [x] `/uxout?uxid=`
- [x] `/address_uxouts`
- [x] `/wallet`
- [x] `/wallets`
- [x] `/wallet/create`
- [x] `/wallet/newAddress`
- [x] `/wallet/balance`
- [x] `/wallet/transactions`
- [x] `/wallet/update`
- [x] `/wallet/folderName`
- [x] `/wallet/spend`
- [x] `/wallet/newSeed`
- [x] `/network/connection`
- [x] `/network/connections`
- [x] `/network/defaultConnections`
- [x] `/network/connections/trust`
- [x] `/network/connections/exchange`
- [x] `/pendingTxs`
- [x] `/transaction`
- [x] `/transactions`
- [x] `/transactions?confirmed=true`
- [x] `/transactions?confirmed=false`
- [x] `/injectTransaction`
- [x] `/resendUnconfirmedTxns`
- [x] `/rawtx`
- [x] `/explorer/address`
- [x] `/richlist`
- [x] `/addresscount`

**Comment by gz-c** [comment]
Important tests are:

* `/coinSupply`
* `/block`
* `/blockchain/progress`
* `/balance?addrs=`

**Comment by gz-c** [comment]
`/coinSupply` is tested now (#967)

Test those others based upon the initial work in `src/gui/integration/`

**Comment by iketheadore** [comment]
I will write the others.

**Comment by gz-c** [comment]
Added tests for the above endpoint in #971

**Comment by gz-c** [comment]
Continue testing all endpoints.

Spend tests will need to run separately, they cannot be run against the stable blockchain and cannot be automated in travis.  Test all of the other endpoints first

**Comment by Vavilen** [comment]
@gz-c, I'll start from other wallet endpoints.

**Comment by olemis** [comment]
FWIW disable networking option 

```sh

$ make run-help
[...]
  -disable-networking
    	Disable all network activity
[...]
```

**Comment by gz-c** [comment]
The HTTP API Client is finished, you can use it to implement the remaining integration tests.

Avoid tests that modify state (POST requests) until last.
Do wallet-related tests separately.

**Comment by gz-c** [comment]
All GUI integration tests are done except for wallet operations and /injectTransaction which relies upon a raw transaction
