### ISSUE TITLE
cli's createRawTransaction should not split coinhours equally

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#951]
People are abusing the automatic coinhour split, withdrawing 1 sky from exchanges repeatedly to get more coin hours. 

Change the default behavior of cli createRawTransaction to send at most coin hours equal to the number of sky to the destination address.  e.g. if sending 30 coins, send at most 30 coin hours (send less, if less would be sent when splitting hours between change and destination).

**Comment by gz-c** [comment]
"People are abusing the automatic coinhour split, withdrawing 1 sky from exchanges repeatedly to get more coin hours."

Strategies:

- Send 0 coin hours to destination, regardless of coins 
The coins would be unspendable by the withdrawer until their output generated a coin hour.  This would take a long time for small balances.

- Send 1 coin hours to the destination, regardless of coins
Some people may still make as many small withdrawals as possible to maximize their coin hours, even if they would only get an extra 10.

- Send coin hours to the destination proportional to the coins
There is no incentive to withdraw repeatedly. Coins < 0 would receive 0 hours.

**Comment by therealssj** [comment]
I believe sending coinhours proportional to the coins with a minimum of 1 coinhour would be a good strategy 

- Sending 0 coinhours might end up locking small amounts in addresss
- Sending 1 coin hour always is good to solve exchange issue but then we limit legit users from sending coinhours to other people ( if we a cut a release with this solution)

5iqaunt allows decimal withdrawals so I think they allow <1 coin withdrawls

**Comment by gz-c** [comment]
If we send 0 coin hours with <1 coin withdrawals they won't be spendable for some time (0.001 would take 1000 hours which is 42 days).  Possibly set the minimum to 1.  This could still encourage some users to withdraw the smallest amount possible repeatedly, but the exchange can enforce a minimum withdrawal amount. And if the exchange has a withdrawal fee, people don't do this. The exchange could also ratelimit withdrawals. Some of this has to be solved on the exchange's end.

Rules:

- Coin hours equal to coins, as a maximum
- Minimum 1 coin hour
- These rules apply as long as the burn fee and change output amounts are still satisfied

**Comment by gz-c** [comment]
#955
