### ISSUE TITLE
visor.Visor.GetSignedBlocksSince does not return genesis block

### ISSUE THREAD

**Issue by mihis** [skycoin/skycoin#960]
Sometimes it is necessary to fetch genesis block from high level code. For example, working on skycoin/services#12, I need to extract genesis block of new coin and create unspent outputs with coin.CreateUnspent to send initial volume to distribution addresses.

However visor.Visor.GetSignedBlocksSince(seq=0, ct=1) always returns empty slice, because (seq=0 and ct > 0)  is an edge case.

Also docs for daemon.Visor.GetSignedBlocks claim that it "returns numbers of signed blocks since seq". However docs for visor.Visor.GetSignedBlocks metntion that it "returns N signed blocks more recent than Seq"

**Comment by gz-c** [comment]
`GetBlock(0)` doesn't work?

**Comment by gz-c** [comment]
This method intentionally does not return the genesis block. I updated the docstring here #962

**Comment by mihis** [comment]
@gz-c 

**func (vs *Visor) GetBlock(seq uint64) (*coin.SignedBlock, error)**

is method of **visor.Visor**, which is private field of **daemon.Visor**. In startup code (like cmd/skycoin/skycoin.go) daemon.Visor is created, not visor.Visor. And in such case there is no straightforward way to access blocks except **daemon.Visor.GetSignedBlocksSince**.

**Comment by gz-c** [comment]
Then add a method to `daemon.Visor` that exports `visor.Visor.GetBlock` in the same way that `daemon.Visor.GetSignedBlocksSince` does
