### ISSUE TITLE
usage of blockchain.Blockchain.GetBlockBySeq can lead to panic 

### ISSUE THREAD

**Issue by mihis** [skycoin/skycoin#961]
Usage of blockchain.Blockchain.GetBlockBySeq(seq) can lead to panic if (seq > number of blocks in blockchain-1). At least it happens if (seq=1 and blockchain has only genesis block). In this case both return values are nil. This behavior is unexpected and can lead to nil pointer dereference. For example, it can happen in uncareful implementation of visor.Visor.GetSignedBlocksSince (see #960).

**Comment by mihis** [comment]
Also, this #616 sounds like the same problem.

**Comment by gz-c** [comment]
There is no problem, caller should not dereference nil
