### ISSUE TITLE
[lib] Export cipher and cli functions to be reused via libskycoin

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#968]
Cipher and CLI functionality will be needed elsewhere . It should be available for reuse in libskycoin .

Cc @gz-c feel free to highlight functions to be exported this way

**Comment by gz-c** [comment]
It depends on how much you want to export versus how much you want to implement in the code using libskycoin.

At minimum you will want to export the cipher methods.  You could potentially reimplement the CLI methods as needed.

Looking at the teller code, which uses the cli library natively to sign transactions:

`cli.CreateRawTxFromWallet` would be the main cli method to export.

For `cipher`:

`cipher.GenerateKeyPair`
`cipher.DecodeBase58Address`
`cipher.GenerateDeterministicKeyPairs`

But likely most of the public methods in `cipher/address.go`, `cipher/hash.go`, `cipher/crypto.go` should be exported.

**Comment by samuelvisscher** [comment]
This would also be great for the Java, Objective-C and Javascript libraries produced through GopherJS and GoMobile.

**Comment by olemis** [comment]
@samuelvisscher do you need client libs for those languages ? We could build some as well (and test'em).
