### ISSUE TITLE
Flaky TestGetTransactions

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#978]
Sometimes fails like this, sometimes passes:

```
--- FAIL: TestGetTransactions (0.02s)
    --- FAIL: TestGetTransactions/400_-_invalid_`addrs`_param (0.00s)
	Error Trace:	transaction_test.go:769
	Error:      	Not equal: 
	            	expected: "400 Bad Request - parse parameter: 'addrs' failed: Invalid base58 character"
	            	actual: "400 Bad Request - parse parameter: 'addrs' failed: Invalid address length"
```

**Comment by therealssj** [comment]
possible bug in the base58 library?

**Comment by gz-c** [comment]
I may have changed something related to this specific endpoint which is causing the failure, it just started now after i changed it, in the gui package

**Comment by gz-c** [comment]
https://github.com/skycoin/skycoin/pull/971/files

Changed a few things in `gui/transaction.go`, is probably the cause

**Comment by therealssj** [comment]
Fixed in https://github.com/skycoin/skycoin/pull/1015
