### ISSUE TITLE
CLI integration test should confirm coinhour cap behavior

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#982]
The behavior was added by #955

**Comment by therealssj** [comment]
This would be a part of the testing `send` and related commands

We would need to test this scenario in live conditions.
How do you suggest we take the required inputs: `sender address` and `receiver address` 

I assume we take the wallet as an environment variable and hard code the coin amount.
Do we take the same route for other required inputs and use environment variables for them?

**Comment by gz-c** [comment]
wallet as an env var: yes
hardcoded coin amounts: yes, less than 1, 1, more than 1 coin

can use envvars for other required inputs for now, its the easiest way to pass it through

**Comment by gz-c** [comment]
@therealssj @iketheadore is this one done?

**Comment by therealssj** [comment]
I dont we have written any cli tests yet which test `send` etc.
Pending issue: https://github.com/skycoin/skycoin/issues/1019
