### ISSUE TITLE
UI lacks feedback of successful send

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#983]
The old UI would update a list of sent transactions in the same view as the send view.

Now, there is no visual feedback that the send was successful.

**Comment by samuelvisscher** [comment]
Should it redirect to transactions, should I add a recent transactions panel, or show a pop-up to notify?

**Comment by gz-c** [comment]
I prefer showing the recent transactions on the same send page at the bottom if possible
Otherwise switching to the history tab
No popups

**Comment by gz-c** [comment]
Not sure we should do this. I'm used to it now, the send button does have some feedback
