### ISSUE TITLE
-address-prefix option

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#988]
Add an option `-address-prefix`
This will be used as a string prefix to all addresses in `cipher/address.go`

**Comment by gz-c** [comment]
@olemis We need this for testnet to have distinct addresses. We will use for other skyledger coins later as well

**Comment by olemis** [comment]
I am not sure I understood correctly . Is this to filter out all address in a network segment different than specified ?

**Comment by gz-c** [comment]
for example, on the official test net all address can start with T or TEST, this is to avoid user error between different instance of the blockchain

**Comment by olemis** [comment]
Oh ! You mean Skycoin addresses ... I was thinking of IP addresses . Sorry

**Comment by olemis** [comment]
@stdevStark pls take a look at [BTC address prefixes](https://en.bitcoin.it/wiki/List_of_address_prefixes)

**Comment by olemis** [comment]
@stdevEclipse pls take a look into this

**Comment by gz-c** [comment]
Note, this is still hypothetical/experimental

**Comment by gz-c** [comment]
If we use address prefixes, it will be for testnet, and we'll have a `-testnet` flag that will set everything appropriately
