### ISSUE TITLE
[GUI] Wallet displays the wrong balance

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#990]
Sometimes the wallet shows the wrong balance like this:

![image](https://user-images.githubusercontent.com/2589926/36100925-d7615e4a-1042-11e8-85e5-843e85536a27.png)

**Comment by gz-c** [comment]
@Senyoret1 do you know how to fix this? it was fixed in explorer

**Comment by Senyoret1** [comment]
@gz-c . In the explorer it was fixed by formatting the number with the following pipe: `v | number:'1.0-6'`. It was not fixed originally by me.
